// Generated by seans-mfe-tool. Do not edit — regenerated on every `remote:generate`.
//
// A GraphQL client for this MFE's BFF (ADR-096 §7, ADR-099).
//
// Generic — `query::<T>(document)` — because the documents are the
// developer's (`src/features/*_query.rs`): the BFF's schema is composed by
// Mesh from `data.sources` at build time, so codegen cannot know it.

use std::collections::BTreeMap;
use std::sync::Arc;

use serde::de::DeserializeOwned;
use serde_json::{Map, Value};

use super::error::MfeError;
use super::mfe_base::{graphql_error_messages, GraphQlPost, MfeTransport};

pub struct BffClient {
    endpoint: String,
    transport: Arc<dyn MfeTransport>,
}

impl BffClient {
    /// The manifest's BFF endpoint, baked at generation (ADR-053).
    pub const DEFAULT_ENDPOINT: &'static str = "http://localhost:5005/graphql";

    pub fn new(endpoint: impl Into<String>, transport: Arc<dyn MfeTransport>) -> Self {
        BffClient { endpoint: endpoint.into(), transport }
    }

    /// `BFF_URL` if set, else the manifest's endpoint — the precedence the web
    /// connector uses. An MFE and its BFF are one deployable unit on one
    /// origin, so a relative path would resolve against the host.
    pub fn with_default_endpoint(transport: Arc<dyn MfeTransport>) -> Self {
        let endpoint = std::env::var("BFF_URL").unwrap_or_else(|_| Self::DEFAULT_ENDPOINT.to_string());
        Self::new(endpoint, transport)
    }

    pub fn endpoint(&self) -> &str {
        &self.endpoint
    }

    /// Run `document` and decode its `data` into `T`.
    ///
    /// Fails on any GraphQL error, including alongside partial data: a caller
    /// decoding into a type should not silently receive half a response. The
    /// `query` capability answers with both instead — the deliberate half of
    /// the difference (ADR-096 §Boundaries).
    pub async fn query<T: DeserializeOwned>(&self, document: &str, variables: Option<Value>) -> Result<T, MfeError> {
        let mut payload = Map::new();
        payload.insert("query".to_string(), Value::String(document.to_string()));
        if let Some(variables) = variables {
            payload.insert("variables".to_string(), variables);
        }
        let request = serde_json::to_vec(&Value::Object(payload)).map_err(|e| MfeError::Decode { message: e.to_string() })?;
        let body = GraphQlPost::send(Some(self.transport.as_ref()), &self.endpoint, request, &BTreeMap::new()).await?;

        let decoded: Value = serde_json::from_slice(&body).map_err(|e| MfeError::Decode { message: e.to_string() })?;
        let errors = graphql_error_messages(&decoded);
        if !errors.is_empty() {
            return Err(MfeError::GraphQl { messages: errors });
        }
        match decoded.get("data") {
            Some(data) if !data.is_null() => {
                serde_json::from_value(data.clone()).map_err(|e| MfeError::Decode { message: e.to_string() })
            }
            _ => Err(MfeError::GraphQl { messages: vec!["response carried no data".to_string()] }),
        }
    }
}
