// Generated by seans-mfe-tool. Do not edit — regenerated on every `remote:generate`.
//
// The data provider, backed by this MFE's BFF (ADR-096 §7, ADR-099).
//
// Each method sends the document in `src/features/<capability>_query.rs` —
// developer-owned, because the schema is Mesh's. Deleting one of those files
// breaks this one; `mfe:validate` names the file and the fix
// (`native-capability-query`).

#[allow(unused_imports)]
use super::bff_client::BffClient;
#[allow(unused_imports)]
use super::data_provider::MeridianCrewServicesDataProvider;
#[allow(unused_imports)]
use super::error::MfeError;
#[allow(unused_imports)]
use super::mfe_base::BoxFuture;
#[allow(unused_imports)]
use super::types::*;

pub struct BffMeridianCrewServicesDataProvider {
    client: BffClient,
}

impl BffMeridianCrewServicesDataProvider {
    pub fn new(client: BffClient) -> Self {
        BffMeridianCrewServicesDataProvider { client }
    }

    pub fn client(&self) -> &BffClient {
        &self.client
    }
}

impl MeridianCrewServicesDataProvider for BffMeridianCrewServicesDataProvider {
    fn crew_roster(&self) -> BoxFuture<'_, Result<CrewRosterOutputs, MfeError>> {
        Box::pin(self.client.query(crate::features::crew_roster_query::DOCUMENT, None))
    }
    fn pay_status(&self) -> BoxFuture<'_, Result<PayStatusOutputs, MfeError>> {
        Box::pin(self.client.query(crate::features::pay_status_query::DOCUMENT, None))
    }
}
