// Generated by seans-mfe-tool. Do not edit — regenerated on every `remote:generate`.
//
// The manifest, rendered into Rust at generation time (ADR-099).
//
// The Swift lane re-derives this at `swift build` time through an SPM plugin,
// so Xcode never builds from a stale table. Cargo's equivalent — a build.rs
// parsing JSON — would put a JSON parser in the build graph of every host for
// a file `check:mfe-drift:check` already proves matches the manifest. So this
// is rendered once, here, and the drift gate is what keeps it honest.

#[allow(unused_imports)] // the phase enum is unused when the manifest declares no hooks
use super::mfe_base::{MfeHookSpec, MfeLifecyclePhase};

pub const NAME: &str = "meridian-crew-services";
pub const VERSION: &str = "1.0.0";
pub const CRATE_NAME: &str = "meridian-crew-services";
pub const BFF_ENDPOINT: Option<&str> = Some("http://localhost:5005/graphql");

/// The manifest's `type` (`remote`, …), as `describe` reports it.
pub const MANIFEST_TYPE: &str = "remote";

/// The manifest this crate was generated from, as pretty JSON — what `schema`
/// returns and `describe` parses (ADR-101), as `BaseRemoteMFE` returns
/// `this.manifest`.
pub const MANIFEST_JSON: &str = r#"{
  "name": "meridian-crew-services",
  "version": "1.0.0",
  "type": "remote",
  "language": "typescript",
  "framework": "react",
  "bundler": "rspack",
  "targets": {
    "swift": {
      "deploymentTarget": "17.0",
      "swiftToolsVersion": "5.9"
    },
    "rust": {
      "edition": "2021",
      "wasm": true
    }
  },
  "description": "Meridian Station crew services — roster, certifications, pay status",
  "owner": "meridian-station",
  "tags": [
    "meridian",
    "crew",
    "services",
    "react"
  ],
  "category": "services",
  "endpoint": "http://localhost:5005",
  "remoteEntry": "http://localhost:5005/remoteEntry.js",
  "discovery": "http://localhost:5005/.well-known/mfe-manifest.yaml",
  "capabilities": [
    {
      "CrewRoster": {
        "type": "domain",
        "description": "Crew roster with certifications from StationOS joined with payroll standing from StellarLedger"
      }
    },
    {
      "PayStatus": {
        "type": "domain",
        "description": "Compact pay-status card for the console status rail — held and scheduled payroll at a glance"
      }
    },
    {
      "Load": {
        "type": "platform",
        "lifecycle": {
          "before": [
            {
              "onLoadBegin": {
                "handler": "onLoadBegin",
                "description": "Log load lifecycle entry"
              }
            }
          ],
          "after": [
            {
              "onLoadComplete": {
                "handler": "onLoadComplete",
                "description": "Log load success and available components"
              }
            }
          ],
          "error": [
            {
              "onLoadError": {
                "handler": "onLoadError",
                "description": "Log load failure",
                "contained": true
              }
            }
          ]
        }
      }
    },
    {
      "Render": {
        "type": "platform",
        "lifecycle": {
          "before": [
            {
              "onRenderBegin": {
                "handler": "onRenderBegin",
                "description": "Log render lifecycle entry"
              }
            }
          ],
          "after": [
            {
              "onRenderComplete": {
                "handler": "onRenderComplete",
                "description": "Log render success"
              }
            }
          ],
          "error": [
            {
              "onRenderError": {
                "handler": "onRenderError",
                "description": "Log render failure",
                "contained": true
              }
            }
          ]
        }
      }
    }
  ],
  "dependencies": {
    "runtime": {
      "react": "^18.0.0",
      "react-dom": "^18.0.0"
    },
    "design-system": {
      "@mui/material": "^5.14.0"
    }
  },
  "data": {
    "sources": [
      {
        "name": "StationOS",
        "handler": {
          "openapi": {
            "source": "./specs/station-os.yaml",
            "operationHeaders": {
              "Authorization": "Bearer {context.jwt}",
              "X-Request-ID": "{context.requestId}"
            }
          }
        },
        "transforms": [
          {
            "hoistField": [
              {
                "typeName": "Query",
                "pathConfig": [
                  "GetCrew",
                  "Data"
                ],
                "newFieldName": "crew"
              },
              {
                "typeName": "Query",
                "pathConfig": [
                  "GetCertifications",
                  "Data"
                ],
                "newFieldName": "certifications"
              }
            ]
          }
        ]
      },
      {
        "name": "StellarLedger",
        "handler": {
          "openapi": {
            "source": "./specs/stellar-ledger.yaml",
            "operationHeaders": {
              "Authorization": "Bearer {context.jwt}",
              "X-Request-ID": "{context.requestId}"
            }
          }
        },
        "transforms": [
          {
            "hoistField": [
              {
                "typeName": "Query",
                "pathConfig": [
                  "listPayroll",
                  "result"
                ],
                "newFieldName": "payroll"
              }
            ]
          }
        ]
      }
    ],
    "serve": {
      "endpoint": "/graphql",
      "playground": true
    },
    "mockSwitch": {
      "enabled": true
    }
  }
}"#;

/// [`MANIFEST_JSON`], parsed.
pub fn manifest() -> serde_json::Value {
    serde_json::from_str(MANIFEST_JSON).unwrap_or(serde_json::Value::Null)
}

/// The domain capabilities this target implements, in manifest order.
pub const DOMAIN_CAPABILITIES: &[&str] = &["CrewRoster", "PayStatus"];

/// One capability as the manifest declares it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CapabilityEntry {
    pub name: &'static str,
    pub kind: &'static str,
    pub description: &'static str,
}

/// Every capability `describe` reports: the platform ones the manifest
/// declares, plus the domain ones this target implements.
pub const CAPABILITIES: &[CapabilityEntry] = &[
    CapabilityEntry {
        name: "CrewRoster",
        kind: "domain",
        description: "Crew roster with certifications from StationOS joined with payroll standing from StellarLedger",
    },
    CapabilityEntry {
        name: "PayStatus",
        kind: "domain",
        description: "Compact pay-status card for the console status rail — held and scheduled payroll at a glance",
    },
    CapabilityEntry {
        name: "Load",
        kind: "platform",
        description: "",
    },
    CapabilityEntry {
        name: "Render",
        kind: "platform",
        description: "",
    },
];

/// The manifest's lifecycle hooks, flattened (ADR-040, ADR-098 §5).
pub const HOOKS: &[MfeHookSpec] = &[
    MfeHookSpec {
        capability: "Load",
        phase: MfeLifecyclePhase::Before,
        hook: "onLoadBegin",
        handlers: &["onLoadBegin"],
        contained: false,
    },
    MfeHookSpec {
        capability: "Load",
        phase: MfeLifecyclePhase::After,
        hook: "onLoadComplete",
        handlers: &["onLoadComplete"],
        contained: false,
    },
    MfeHookSpec {
        capability: "Load",
        phase: MfeLifecyclePhase::Error,
        hook: "onLoadError",
        handlers: &["onLoadError"],
        contained: true,
    },
    MfeHookSpec {
        capability: "Render",
        phase: MfeLifecyclePhase::Before,
        hook: "onRenderBegin",
        handlers: &["onRenderBegin"],
        contained: false,
    },
    MfeHookSpec {
        capability: "Render",
        phase: MfeLifecyclePhase::After,
        hook: "onRenderComplete",
        handlers: &["onRenderComplete"],
        contained: false,
    },
    MfeHookSpec {
        capability: "Render",
        phase: MfeLifecyclePhase::Error,
        hook: "onRenderError",
        handlers: &["onRenderError"],
        contained: true,
    },
];
