// Generated by seans-mfe-tool. Do not edit — regenerated on every `remote:generate`.
//
// The platform contract, rendered into Rust (ADR-099).
//
// Every value below comes from `packages/contracts/src/platform-contract.ts`,
// the canonical framework-neutral contract (ADR-041, ADR-042, ADR-080). It is
// rendered, never hand-written: a hand-kept Rust copy would drift the first
// time a state or capability was added, and nothing would catch it.

/// The six lifecycle states. Mirrors `MFE_LIFECYCLE_STATES`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum MfeLifecycleState {
    Uninitialized,
    Loading,
    Ready,
    Rendering,
    Error,
    Destroyed,
}

impl MfeLifecycleState {
    /// Every state, in contract order.
    pub const ALL: [MfeLifecycleState; 6] = [
        MfeLifecycleState::Uninitialized,
        MfeLifecycleState::Loading,
        MfeLifecycleState::Ready,
        MfeLifecycleState::Rendering,
        MfeLifecycleState::Error,
        MfeLifecycleState::Destroyed,
    ];

    /// The contract's spelling of this state.
    pub fn as_str(self) -> &'static str {
        match self {
            MfeLifecycleState::Uninitialized => "uninitialized",
            MfeLifecycleState::Loading => "loading",
            MfeLifecycleState::Ready => "ready",
            MfeLifecycleState::Rendering => "rendering",
            MfeLifecycleState::Error => "error",
            MfeLifecycleState::Destroyed => "destroyed",
        }
    }

    /// The legal edges out of this state, mirroring `MFE_LIFECYCLE_TRANSITIONS`.
    ///
    /// A transition not listed here is a programming error and fails at the
    /// boundary rather than corrupting state silently (ADR-042).
    pub fn transitions(self) -> &'static [MfeLifecycleState] {
        match self {
            MfeLifecycleState::Uninitialized => &[MfeLifecycleState::Loading],
            MfeLifecycleState::Loading => &[MfeLifecycleState::Ready, MfeLifecycleState::Error],
            MfeLifecycleState::Ready => &[MfeLifecycleState::Loading, MfeLifecycleState::Rendering, MfeLifecycleState::Destroyed],
            MfeLifecycleState::Rendering => &[MfeLifecycleState::Ready, MfeLifecycleState::Error],
            MfeLifecycleState::Error => &[MfeLifecycleState::Loading, MfeLifecycleState::Destroyed],
            MfeLifecycleState::Destroyed => &[],
        }
    }

    pub fn can_transition_to(self, to: MfeLifecycleState) -> bool {
        self.transitions().contains(&to)
    }
}

/// The ten platform capabilities. Mirrors `PLATFORM_CAPABILITIES`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum MfeCapability {
    Describe,
    Load,
    Render,
    Refresh,
    Emit,
    Query,
    Schema,
    AuthorizeAccess,
    Health,
    UpdateControlPlaneState,
}

impl MfeCapability {
    /// Every capability, in contract order.
    pub const ALL: [MfeCapability; 10] = [
        MfeCapability::Describe,
        MfeCapability::Load,
        MfeCapability::Render,
        MfeCapability::Refresh,
        MfeCapability::Emit,
        MfeCapability::Query,
        MfeCapability::Schema,
        MfeCapability::AuthorizeAccess,
        MfeCapability::Health,
        MfeCapability::UpdateControlPlaneState,
    ];

    /// The contract's spelling of this capability.
    pub fn as_str(self) -> &'static str {
        match self {
            MfeCapability::Describe => "describe",
            MfeCapability::Load => "load",
            MfeCapability::Render => "render",
            MfeCapability::Refresh => "refresh",
            MfeCapability::Emit => "emit",
            MfeCapability::Query => "query",
            MfeCapability::Schema => "schema",
            MfeCapability::AuthorizeAccess => "authorizeAccess",
            MfeCapability::Health => "health",
            MfeCapability::UpdateControlPlaneState => "updateControlPlaneState",
        }
    }

    /// States the capability may be invoked from. Empty means any state,
    /// including `destroyed` — only `emit` is that permissive.
    pub fn pre_states(self) -> &'static [MfeLifecycleState] {
        match self {
            MfeCapability::Describe => &[MfeLifecycleState::Uninitialized, MfeLifecycleState::Loading, MfeLifecycleState::Ready, MfeLifecycleState::Rendering, MfeLifecycleState::Error],
            MfeCapability::Load => &[MfeLifecycleState::Uninitialized, MfeLifecycleState::Ready, MfeLifecycleState::Error],
            MfeCapability::Render => &[MfeLifecycleState::Ready],
            MfeCapability::Refresh => &[MfeLifecycleState::Ready],
            MfeCapability::Emit => &[],
            MfeCapability::Query => &[MfeLifecycleState::Ready],
            MfeCapability::Schema => &[MfeLifecycleState::Ready],
            MfeCapability::AuthorizeAccess => &[MfeLifecycleState::Ready],
            MfeCapability::Health => &[MfeLifecycleState::Uninitialized, MfeLifecycleState::Loading, MfeLifecycleState::Ready, MfeLifecycleState::Rendering, MfeLifecycleState::Error],
            MfeCapability::UpdateControlPlaneState => &[MfeLifecycleState::Ready, MfeLifecycleState::Rendering],
        }
    }

    /// State entered before execution, e.g. `load` → `loading`.
    pub fn enter_state(self) -> Option<MfeLifecycleState> {
        match self {
            MfeCapability::Describe => None,
            MfeCapability::Load => Some(MfeLifecycleState::Loading),
            MfeCapability::Render => Some(MfeLifecycleState::Rendering),
            MfeCapability::Refresh => None,
            MfeCapability::Emit => None,
            MfeCapability::Query => None,
            MfeCapability::Schema => None,
            MfeCapability::AuthorizeAccess => None,
            MfeCapability::Health => None,
            MfeCapability::UpdateControlPlaneState => None,
        }
    }

    /// State entered on success.
    pub fn exit_state(self) -> Option<MfeLifecycleState> {
        match self {
            MfeCapability::Describe => None,
            MfeCapability::Load => Some(MfeLifecycleState::Ready),
            MfeCapability::Render => Some(MfeLifecycleState::Ready),
            MfeCapability::Refresh => None,
            MfeCapability::Emit => None,
            MfeCapability::Query => None,
            MfeCapability::Schema => None,
            MfeCapability::AuthorizeAccess => None,
            MfeCapability::Health => None,
            MfeCapability::UpdateControlPlaneState => None,
        }
    }

    /// State entered on failure.
    pub fn error_state(self) -> Option<MfeLifecycleState> {
        match self {
            MfeCapability::Describe => None,
            MfeCapability::Load => Some(MfeLifecycleState::Error),
            MfeCapability::Render => Some(MfeLifecycleState::Error),
            MfeCapability::Refresh => None,
            MfeCapability::Emit => None,
            MfeCapability::Query => None,
            MfeCapability::Schema => None,
            MfeCapability::AuthorizeAccess => None,
            MfeCapability::Health => None,
            MfeCapability::UpdateControlPlaneState => None,
        }
    }
}
