// Generated by seans-mfe-tool. Do not edit — regenerated on every `remote:generate`.
//
// The native `do_*` hooks (ADR-099) — the Rust sibling of
// `packages/runtime/src/base-remote-mfe.ts` and of the Swift lane's
// `NativeMFEBase`.
//
// Correspondence with BaseRemoteMFE:
//
//   fetchContainer(remoteEntry)  →  NO ANALOGUE (static linking)
//   mountComponent(id, el)       →  NativeMfe::mount     [implementation hook]
//   unmount(containerId)         →  NativeMfe::unmount
//   getSharedDependencies()      →  NO ANALOGUE
//
// Two rows cross to nothing, and both for the reason ADR-096 §4 gives: they
// are federation machinery, not contract. Swift at least has `Bundle.load()`
// to call; a Rust crate is linked into its host at build time, Rust has no
// stable ABI to load one at runtime, and so `load` here is exactly the
// contract's own description of it — validate config — with no acquisition
// step in front.
//
// Rust has no class inheritance, so this layer is a trait with a blanket
// implementation: anything that is a `NativeMfe` gets every `do_*` hook below.

use std::collections::BTreeSet;
use std::sync::{Arc, Mutex};
use std::time::Instant;

use super::data_provider::MeridianCrewServicesDataProvider;
use super::error::MfeError;
use super::manifest_metadata;
use super::mfe_base::{BoxFuture, MfeContext, MfeCore, MfeHooks};
use super::mfe_lifecycle::{MfeCapability, MfeLifecycleState};
use super::types::*;

/// What an implementation supplies. Everything else is the blanket
/// `MfeHooks` implementation below.
pub trait NativeMfe: Send + Sync {
    /// The injected data seam (ADR-096).
    fn provider(&self) -> &Arc<dyn MeridianCrewServicesDataProvider>;

    /// Capability ids currently mounted, mirroring `mountedComponent`.
    fn mounted(&self) -> &Mutex<BTreeSet<String>>;

    /// Mount a capability. The native analogue of `mountComponent`.
    fn mount(&self, capability_id: &str) -> Result<(), MfeError>;

    /// Tear down a mounted capability. The native analogue of `unmount`.
    fn unmount(&self, capability_id: &str) {
        self.mounted()
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner())
            .remove(capability_id);
    }
}

/// The static tables must agree with the manifest this crate was generated
/// from. They cannot disagree without someone having edited a generated file,
/// so this is a loud failure rather than a recovery path.
fn validate_capability_table(core: &MfeCore) -> Result<(), MfeError> {
    if manifest_metadata::NAME.is_empty() || core.identity().name.is_empty() {
        return Err(MfeError::InvalidState {
            from: core.state(),
            attempted: MfeCapability::Load,
            allowed: vec![MfeLifecycleState::Uninitialized],
        });
    }
    Ok(())
}

impl<T: NativeMfe> MfeHooks for T {
    /// Initialization — connect, warm caches, validate config.
    fn do_load<'a>(&'a self, core: &'a MfeCore, _context: &'a MfeContext) -> BoxFuture<'a, Result<LoadResult, MfeError>> {
        Box::pin(async move {
            let started = Instant::now();
            validate_capability_table(core)?;
            Ok(LoadResult {
                success: true,
                available_capabilities: manifest_metadata::DOMAIN_CAPABILITIES.iter().map(|c| c.to_string()).collect(),
                duration_ms: started.elapsed().as_millis() as u64,
            })
        })
    }

    fn do_render<'a>(&'a self, core: &'a MfeCore, context: &'a MfeContext) -> BoxFuture<'a, Result<RenderResult, MfeError>> {
        Box::pin(async move {
            let Some(capability_id) = context.capability_id.clone() else {
                return Err(MfeError::InvalidState {
                    from: core.state(),
                    attempted: MfeCapability::Render,
                    allowed: vec![MfeLifecycleState::Ready],
                });
            };
            self.mount(&capability_id)?;
            self.mounted()
                .lock()
                .unwrap_or_else(|poisoned| poisoned.into_inner())
                .insert(capability_id.clone());
            Ok(RenderResult { success: true, capability_id })
        })
    }

    /// Data reload in place. The provider owns the fetch; there is nothing
    /// delivery-mechanism-specific to do here.
    fn do_refresh<'a>(&'a self, _core: &'a MfeCore, _context: &'a MfeContext) -> BoxFuture<'a, Result<(), MfeError>> {
        Box::pin(async { Ok(()) })
    }

    fn do_authorize_access<'a>(&'a self, _core: &'a MfeCore, _context: &'a MfeContext) -> BoxFuture<'a, Result<bool, MfeError>> {
        Box::pin(async { Ok(true) })
    }

    fn do_health<'a>(&'a self, core: &'a MfeCore, _context: &'a MfeContext) -> BoxFuture<'a, Result<HealthResult, MfeError>> {
        Box::pin(async move {
            let state = core.state();
            Ok(HealthResult { healthy: state != MfeLifecycleState::Error, state: state.as_str().to_string() })
        })
    }

    /// Self-registration, answered from the generated table with no I/O.
    fn do_describe<'a>(&'a self, core: &'a MfeCore, _context: &'a MfeContext) -> BoxFuture<'a, Result<DescribeResult, MfeError>> {
        Box::pin(async move {
            Ok(DescribeResult {
                name: core.identity().name.clone(),
                version: core.identity().version.clone(),
                capabilities: manifest_metadata::CAPABILITIES
                    .iter()
                    .map(|c| CapabilityMetadata {
                        name: c.name.to_string(),
                        kind: c.kind.to_string(),
                        description: c.description.to_string(),
                    })
                    .collect(),
            })
        })
    }

    fn do_schema<'a>(&'a self, _core: &'a MfeCore, _context: &'a MfeContext) -> BoxFuture<'a, Result<SchemaResult, MfeError>> {
        Box::pin(async { Ok(SchemaResult { sdl: None }) })
    }

    /// Telemetry emission. NOT implemented in the native lane: there is no
    /// telemetry service to deliver to, and answering `accepted: true` would
    /// claim a delivery that never happened (ADR-096 §Boundaries).
    fn do_emit<'a>(&'a self, _core: &'a MfeCore, _context: &'a MfeContext) -> BoxFuture<'a, Result<EmitResult, MfeError>> {
        Box::pin(async {
            Err(MfeError::NotImplemented {
                capability: MfeCapability::Emit,
                detail: "no telemetry transport — BaseMFE emits through deps.telemetry, which this lane has no analogue for".to_string(),
            })
        })
    }

    /// Control-plane push. NOT implemented: `BaseMFE.attachControlPlane` takes
    /// a daemon WebSocket client and there is no native counterpart.
    fn do_update_control_plane_state<'a>(
        &'a self,
        _core: &'a MfeCore,
        _context: &'a MfeContext,
    ) -> BoxFuture<'a, Result<ControlPlaneStateResult, MfeError>> {
        Box::pin(async {
            Err(MfeError::NotImplemented {
                capability: MfeCapability::UpdateControlPlaneState,
                detail: "no control-plane transport — BaseMFE.attachControlPlane(wsClient) has no native analogue".to_string(),
            })
        })
    }
}
