// Generated by seans-mfe-tool. Do not edit — regenerated on every `remote:generate`.
//
// The native `do_*` hooks (ADR-099) — the Rust sibling of
// `packages/runtime/src/base-remote-mfe.ts` and of the Swift lane's
// `NativeMFEBase`.
//
// Correspondence with BaseRemoteMFE:
//
//   fetchContainer(remoteEntry)  →  NO ANALOGUE (static linking)
//   mountComponent(id, el)       →  NativeMfe::mount     [implementation hook]
//   unmount(containerId)         →  NativeMfe::unmount
//   getSharedDependencies()      →  NO ANALOGUE
//
// Two rows cross to nothing, and both for the reason ADR-096 §4 gives: they
// are federation machinery, not contract. Swift at least has `Bundle.load()`
// to call; a Rust crate is linked into its host at build time, Rust has no
// stable ABI to load one at runtime, and so `load` here is exactly the
// contract's own description of it — validate config — with no acquisition
// step in front.
//
// Rust has no class inheritance, so this layer is a trait with a blanket
// implementation: anything that is a `NativeMfe` gets every `do_*` hook below.

use std::collections::BTreeSet;
use std::sync::{Arc, Mutex};

use super::data_provider::MeridianCrewServicesDataProvider;
use super::error::MfeError;
use super::manifest_metadata;
use serde_json::{Map, Value};

use super::mfe_base::{iso_now, next_id, BoxFuture, MaybeSendSync, MfeContext, MfeCore, MfeHooks, MfeTelemetryEvent};
use super::mfe_lifecycle::{MfeCapability, MfeLifecycleState};
use super::types::*;

/// What an implementation supplies. Everything else is the blanket
/// `MfeHooks` implementation below.
pub trait NativeMfe: MaybeSendSync {
    /// The injected data seam (ADR-096).
    fn provider(&self) -> &Arc<dyn MeridianCrewServicesDataProvider>;

    /// Capability ids currently mounted, mirroring `mountedComponent`.
    fn mounted(&self) -> &Mutex<BTreeSet<String>>;

    /// Mount a capability. The native analogue of `mountComponent`.
    fn mount(&self, capability_id: &str) -> Result<(), MfeError>;

    /// Tear down a mounted capability. The native analogue of `unmount`.
    fn unmount(&self, capability_id: &str) {
        self.mounted()
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner())
            .remove(capability_id);
    }
}

/// The static tables must agree with the manifest this crate was generated
/// from. They cannot disagree without someone having edited a generated file,
/// so this is a loud failure rather than a recovery path.
fn validate_capability_table(core: &MfeCore) -> Result<(), MfeError> {
    if manifest_metadata::NAME.is_empty() || core.identity().name.is_empty() {
        return Err(MfeError::InvalidState {
            from: core.state(),
            attempted: MfeCapability::Load,
            allowed: vec![MfeLifecycleState::Uninitialized],
        });
    }
    Ok(())
}

/// Every capability this crate declares, as the manifest spells it.
fn capability_table() -> Vec<CapabilityMetadata> {
    manifest_metadata::CAPABILITIES
        .iter()
        .map(|c| CapabilityMetadata {
            name: c.name.to_string(),
            kind: c.kind.to_string(),
            description: c.description.to_string(),
        })
        .collect()
}

fn check(name: &str, pass: bool, message: impl Into<String>) -> HealthCheck {
    HealthCheck {
        name: name.to_string(),
        status: if pass { CheckStatus::Pass } else { CheckStatus::Fail },
        message: Some(message.into()),
    }
}

/// `context.inputs` for `updateControlPlaneState`, validated exactly as
/// `validateStateUpdateInputs` validates it in `base-remote-mfe.ts`.
fn state_update_inputs(context: &MfeContext) -> Result<(String, Value, Option<String>), MfeError> {
    let key = context.inputs.get("stateKey").and_then(Value::as_str).map(str::trim).filter(|k| !k.is_empty());
    let Some(key) = key else {
        return Err(MfeError::Validation {
            field: "context.inputs.stateKey".to_string(),
            message: "updateControlPlaneState requires context.inputs.stateKey to be a non-empty string".to_string(),
        });
    };
    let data = match context.inputs.get("stateData") {
        None => Value::Object(Map::new()),
        Some(Value::Object(obj)) => Value::Object(obj.clone()),
        Some(_) => {
            return Err(MfeError::Validation {
                field: "context.inputs.stateData".to_string(),
                message: "updateControlPlaneState requires context.inputs.stateData to be an object when provided".to_string(),
            })
        }
    };
    let correlation = match context.inputs.get("correlationId") {
        None => None,
        Some(Value::String(c)) if !c.trim().is_empty() => Some(c.trim().to_string()),
        Some(_) => {
            return Err(MfeError::Validation {
                field: "context.inputs.correlationId".to_string(),
                message: "updateControlPlaneState requires context.inputs.correlationId to be a non-empty string when provided".to_string(),
            })
        }
    };
    Ok((key.to_string(), data, correlation))
}

/// The daemon's `sendMessage` mutation — the same document
/// `BaseRemoteMFE.doUpdateControlPlaneState` sends.
pub const SEND_MESSAGE_MUTATION: &str = "mutation sendMessage($m: String!) { sendMessage(message: $m) }";

/// How long the daemon has to acknowledge, as in TypeScript.
pub const SEND_MESSAGE_TIMEOUT_MS: u64 = 4_000;

impl<T: NativeMfe> MfeHooks for T {
    /// Initialization — connect, warm caches, validate config.
    fn do_load<'a>(&'a self, core: &'a MfeCore, _context: &'a MfeContext) -> BoxFuture<'a, Result<LoadResult, MfeError>> {
        Box::pin(async move {
            // `Instant::now()` panics on wasm32-unknown-unknown (ADR-100), so the
            // duration is only measured where there is a clock.
            #[cfg(not(target_arch = "wasm32"))]
            let started = Some(std::time::Instant::now());
            #[cfg(target_arch = "wasm32")]
            let started: Option<std::time::Instant> = None;
            validate_capability_table(core)?;
            Ok(LoadResult {
                status: LoadStatus::Loaded,
                available_components: manifest_metadata::DOMAIN_CAPABILITIES.iter().map(|c| c.to_string()).collect(),
                capabilities: capability_table(),
                timestamp: iso_now(),
                duration: started.map(|s| s.elapsed().as_millis() as u64),
            })
        })
    }

    fn do_render<'a>(&'a self, core: &'a MfeCore, context: &'a MfeContext) -> BoxFuture<'a, Result<RenderResult, MfeError>> {
        Box::pin(async move {
            let Some(capability_id) = context.capability_id.clone() else {
                return Err(MfeError::InvalidState {
                    from: core.state(),
                    attempted: MfeCapability::Render,
                    allowed: vec![MfeLifecycleState::Ready],
                });
            };
            self.mount(&capability_id)?;
            self.mounted()
                .lock()
                .unwrap_or_else(|poisoned| poisoned.into_inner())
                .insert(capability_id.clone());
            Ok(RenderResult { status: RenderStatus::Rendered, capability_id, timestamp: iso_now() })
        })
    }

    /// Data reload in place. The provider owns the fetch; there is nothing
    /// delivery-mechanism-specific to do here — the same as
    /// `BaseRemoteMFE.doRefresh`.
    fn do_refresh<'a>(&'a self, _core: &'a MfeCore, _context: &'a MfeContext) -> BoxFuture<'a, Result<(), MfeError>> {
        Box::pin(async { Ok(()) })
    }

    /// Allow, as `BaseRemoteMFE.doAuthorizeAccess` does. Access policy belongs
    /// to the product; an MFE that needs its own check registers a manifest
    /// hook on `AuthorizeAccess`, which runs in the pipeline before this.
    fn do_authorize_access<'a>(&'a self, _core: &'a MfeCore, _context: &'a MfeContext) -> BoxFuture<'a, Result<bool, MfeError>> {
        Box::pin(async { Ok(true) })
    }

    /// Liveness with the checks this lane can actually make: the state, the
    /// capability table, and — when there is a BFF — whether a transport was
    /// injected to reach it. The web lane checks its container and components;
    /// a linked crate has neither.
    fn do_health<'a>(&'a self, core: &'a MfeCore, _context: &'a MfeContext) -> BoxFuture<'a, Result<HealthResult, MfeError>> {
        Box::pin(async move {
            let state = core.state();
            let mut checks = vec![
                check("state", state != MfeLifecycleState::Error, format!("lifecycle state is {}", state.as_str())),
                check(
                    "capability-table",
                    validate_capability_table(core).is_ok(),
                    format!("{} domain capabilities declared", manifest_metadata::DOMAIN_CAPABILITIES.len()),
                ),
            ];
            if core.identity().bff_endpoint.is_some() {
                let has = core.deps().transport.is_some();
                checks.push(check(
                    "transport",
                    has,
                    if has { "transport configured".to_string() } else { "no transport — inject MfeDependencies.transport to reach the BFF".to_string() },
                ));
            }
            let status = if state == MfeLifecycleState::Error {
                HealthStatus::Unhealthy
            } else if checks.iter().any(|c| c.status == CheckStatus::Fail) {
                HealthStatus::Degraded
            } else {
                HealthStatus::Healthy
            };
            Ok(HealthResult { status, checks, timestamp: iso_now() })
        })
    }

    /// Self-description, answered from the generated table with no I/O.
    fn do_describe<'a>(&'a self, core: &'a MfeCore, _context: &'a MfeContext) -> BoxFuture<'a, Result<DescribeResult, MfeError>> {
        Box::pin(async move {
            Ok(DescribeResult {
                name: core.identity().name.clone(),
                version: core.identity().version.clone(),
                kind: manifest_metadata::MANIFEST_TYPE.to_string(),
                capabilities: manifest_metadata::CAPABILITIES.iter().map(|c| c.name.to_string()).collect(),
                manifest: manifest_metadata::manifest(),
            })
        })
    }

    /// The manifest as JSON, as `BaseRemoteMFE.doSchema` returns it.
    fn do_schema<'a>(&'a self, _core: &'a MfeCore, _context: &'a MfeContext) -> BoxFuture<'a, Result<SchemaResult, MfeError>> {
        Box::pin(async { Ok(SchemaResult { schema: manifest_metadata::MANIFEST_JSON.to_string(), format: SchemaFormat::Json }) })
    }

    /// Telemetry: forward `context.inputs.event` to `deps.telemetry`
    /// (ADR-101). Answers `emitted: false`, not an error, when there is no
    /// telemetry or no event — as `BaseRemoteMFE.doEmit` does.
    fn do_emit<'a>(&'a self, core: &'a MfeCore, context: &'a MfeContext) -> BoxFuture<'a, Result<EmitResult, MfeError>> {
        Box::pin(async move {
            let (Some(telemetry), Some(Value::Object(raw))) = (&core.deps().telemetry, context.inputs.get("event")) else {
                return Ok(EmitResult { emitted: false, event_id: None });
            };
            if !telemetry.is_active() {
                return Ok(EmitResult { emitted: false, event_id: None });
            }
            let text = |key: &str, default: &str| raw.get(key).and_then(Value::as_str).unwrap_or(default).to_string();
            let event = MfeTelemetryEvent {
                name: text("name", "event"),
                capability: text("capability", "emit"),
                phase: text("phase", "main"),
                user: raw.get("user").and_then(Value::as_str).map(str::to_string),
                duration: raw.get("duration").and_then(Value::as_u64),
                status: text("status", "success"),
                metadata: raw.get("metadata").and_then(Value::as_object).cloned().unwrap_or_default(),
                timestamp: raw.get("timestamp").and_then(Value::as_str).map(str::to_string).or_else(iso_now),
            };
            telemetry.emit(event);
            Ok(EmitResult { emitted: true, event_id: Some(next_id("evt-")) })
        })
    }

    /// Push domain state to the daemon for registry re-evaluation (ADR-101),
    /// step for step as `BaseRemoteMFE.doUpdateControlPlaneState`:
    ///
    /// 1. validate `stateKey` / `stateData` / `correlationId`
    /// 2. no connected daemon → `acknowledged: false`, not an error
    /// 3. a `STATE_UPDATE` action envelope (ADR-057), as `buildMessage` builds it
    /// 4. the daemon's `sendMessage` mutation; a timeout reads `sendMessage timed out`
    /// 5. telemetry, 6. the result
    fn do_update_control_plane_state<'a>(
        &'a self,
        core: &'a MfeCore,
        context: &'a MfeContext,
    ) -> BoxFuture<'a, Result<ControlPlaneStateResult, MfeError>> {
        Box::pin(async move {
            let (state_key, state_data, correlation) = state_update_inputs(context)?;
            let correlation_id = correlation.unwrap_or_else(|| context.request_id.clone());

            let client = match &core.deps().control_plane {
                Some(client) if client.connected() => client.clone(),
                _ => {
                    return Ok(ControlPlaneStateResult {
                        acknowledged: false,
                        correlation_id,
                        error: Some("Daemon WebSocket not connected".to_string()),
                        resolution: None,
                    })
                }
            };

            let envelope = serde_json::json!({
                "direction": "ACTION",
                "kind": "ACTION",
                "payload": {
                    "id": next_id("act-"),
                    "componentId": context.capability_id.clone().unwrap_or_else(|| core.identity().name.clone()),
                    "actionType": "STATE_UPDATE",
                    "stateKey": state_key,
                    "data": state_data,
                    "timestamp": iso_now(),
                },
                "metadata": { "correlationId": correlation_id, "acknowledged": false, "error": null },
            });
            let variables = serde_json::json!({ "m": envelope.to_string() });

            let (acknowledged, error) = match client.mutation(SEND_MESSAGE_MUTATION, variables, SEND_MESSAGE_TIMEOUT_MS).await {
                Ok(true) => (true, None),
                Ok(false) => (false, Some("sendMessage mutation failed".to_string())),
                Err(e) => {
                    let message = e.to_string();
                    (false, Some(if message.contains("timed out") { "sendMessage timed out".to_string() } else { message }))
                }
            };

            let mut metadata = Map::new();
            metadata.insert("mfe".to_string(), Value::from(core.identity().name.clone()));
            metadata.insert("stateKey".to_string(), Value::from(state_key));
            metadata.insert("correlationId".to_string(), Value::from(correlation_id.clone()));
            metadata.insert("acknowledged".to_string(), Value::from(acknowledged));
            core.emit_telemetry(
                "control-plane-state-update",
                "updateControlPlaneState",
                "main",
                if acknowledged { "success" } else { "error" },
                metadata,
            );

            Ok(ControlPlaneStateResult { acknowledged, correlation_id, error, resolution: None })
        })
    }
}
