// Generated by seans-mfe-tool. Do not edit — regenerated on every `remote:generate`.
//
// Capability result types and this MFE's identity (ADR-099).
//
// The result types mirror the runtime barrel's exported shapes (`LoadResult`,
// `RenderResult`, …). The per-capability Inputs/Outputs structs mirror the
// generated `src/platform/base-mfe/types.ts` in the web lane: empty today, and
// the place a capability's real payload is declared.

use serde::{Deserialize, Serialize};

use super::manifest_metadata;

/// Identity, rendered from the manifest at generation time.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MfeIdentity {
    pub name: String,
    pub version: String,
    pub crate_name: String,
    /// The BFF origin this MFE's data provider talks to, from the manifest.
    pub bff_endpoint: Option<String>,
}

impl MfeIdentity {
    /// The identity this crate was generated from.
    pub fn current() -> Self {
        MfeIdentity {
            name: manifest_metadata::NAME.to_string(),
            version: manifest_metadata::VERSION.to_string(),
            crate_name: manifest_metadata::CRATE_NAME.to_string(),
            bff_endpoint: manifest_metadata::BFF_ENDPOINT.map(str::to_string),
        }
    }
}

/// One capability as the manifest declares it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CapabilityMetadata {
    pub name: String,
    #[serde(rename = "type")]
    pub kind: String,
    pub description: String,
}

// The ten results below serialize to `packages/runtime/src/capability-results.ts`
// (ADR-101): camelCase fields, lowercase enum values, ISO-8601 timestamps.
// `rust-result-contract.test.ts` compares the two files field by field.
//
// Timestamps are `Option<String>` because `wasm32-unknown-unknown` has no
// clock std can reach (ADR-100): `None` there, never a made-up time.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum LoadStatus {
    Loaded,
    Error,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LoadResult {
    pub status: LoadStatus,
    pub available_components: Vec<String>,
    pub capabilities: Vec<CapabilityMetadata>,
    pub timestamp: Option<String>,
    pub duration: Option<u64>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum RenderStatus {
    Rendered,
    Error,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RenderResult {
    pub status: RenderStatus,
    pub capability_id: String,
    pub timestamp: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum HealthStatus {
    Healthy,
    Degraded,
    Unhealthy,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum CheckStatus {
    Pass,
    Fail,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HealthCheck {
    pub name: String,
    pub status: CheckStatus,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub message: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HealthResult {
    pub status: HealthStatus,
    pub checks: Vec<HealthCheck>,
    pub timestamp: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DescribeResult {
    pub name: String,
    pub version: String,
    /// The manifest's `type` (`remote`, …). `type` is a Rust keyword.
    #[serde(rename = "type")]
    pub kind: String,
    pub capabilities: Vec<String>,
    /// The manifest this crate was generated from, as JSON.
    pub manifest: serde_json::Value,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SchemaFormat {
    Graphql,
    Json,
    Openapi,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SchemaResult {
    pub schema: String,
    pub format: SchemaFormat,
}

/// One GraphQL error, as the BFF returned it.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct QueryError {
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub path: Option<Vec<String>>,
}

impl QueryError {
    pub fn new(message: impl Into<String>) -> Self {
        QueryError { message: message.into(), path: None }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct QueryResult {
    pub data: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub errors: Vec<QueryError>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EmitResult {
    pub emitted: bool,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub event_id: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ControlPlaneStateResult {
    pub acknowledged: bool,
    pub correlation_id: String,
    pub error: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub resolution: Option<serde_json::Value>,
}

// ---- CrewRoster

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CrewRosterInputs {}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CrewRosterOutputs {}

// ---- PayStatus

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PayStatusInputs {}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PayStatusOutputs {}
