// Generated by seans-mfe-tool. Do not edit — regenerated on every `remote:generate`.
//
// Capability result types and this MFE's identity (ADR-099).
//
// The result types mirror the runtime barrel's exported shapes (`LoadResult`,
// `RenderResult`, …). The per-capability Inputs/Outputs structs mirror the
// generated `src/platform/base-mfe/types.ts` in the web lane: empty today, and
// the place a capability's real payload is declared.

use serde::{Deserialize, Serialize};

use super::manifest_metadata;

/// Identity, rendered from the manifest at generation time.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MfeIdentity {
    pub name: String,
    pub version: String,
    pub crate_name: String,
    /// The BFF origin this MFE's data provider talks to, from the manifest.
    pub bff_endpoint: Option<String>,
}

impl MfeIdentity {
    /// The identity this crate was generated from.
    pub fn current() -> Self {
        MfeIdentity {
            name: manifest_metadata::NAME.to_string(),
            version: manifest_metadata::VERSION.to_string(),
            crate_name: manifest_metadata::CRATE_NAME.to_string(),
            bff_endpoint: manifest_metadata::BFF_ENDPOINT.map(str::to_string),
        }
    }
}

/// One capability as reported by `describe`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CapabilityMetadata {
    pub name: String,
    #[serde(rename = "type")]
    pub kind: String,
    pub description: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LoadResult {
    pub success: bool,
    pub available_capabilities: Vec<String>,
    pub duration_ms: u64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RenderResult {
    pub success: bool,
    pub capability_id: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DescribeResult {
    pub name: String,
    pub version: String,
    pub capabilities: Vec<CapabilityMetadata>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HealthResult {
    pub healthy: bool,
    pub state: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SchemaResult {
    pub sdl: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct QueryResult {
    pub data: Option<serde_json::Value>,
    pub errors: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EmitResult {
    pub accepted: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ControlPlaneStateResult {
    pub accepted: bool,
    pub state_key: String,
}

// ---- CrewRoster

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CrewRosterInputs {}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CrewRosterOutputs {}

// ---- PayStatus

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PayStatusInputs {}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PayStatusOutputs {}
