
/**
 * testmonorepovalidationMFEBFF
 * @description BFF layer generated from DSL manifest
 * @generated By seans-mfe-tool CLI
 */
import { createMeshHTTPHandler } from '@graphql-mesh/http';
import { getMesh } from '@graphql-mesh/runtime';
import meshConfig from './.meshrc.yaml';

export async function startBFFServer(port: number = 4000) {
  const mesh = await getMesh({ config: meshConfig });
  const handler = createMeshHTTPHandler(mesh);
  // TODO: Integrate with Express or Koa if needed
  // WARNING: Stub generated by CLI
}
