/**
 * ADR-061 conformance — codegen is a pure unit, and the framework variant is
 * injected rather than resolved inside it.
 *
 * ADR-061 extracted `packages/codegen` as a zero-coupling `manifest →
 * GeneratedFile[]` generator. The structural half held on inspection: codegen's
 * only workspace dependencies are `@falese/smt-dsl` and `@falese/smt-contracts`,
 * it ships its templates, it never imports the framework loader, `src/dsl` is
 * gone so the `dsl → codegen → dsl` cycle cannot re-form, and the runtime
 * imports manifest types with `import type` only.
 *
 * The gap is in §3. Its exact words:
 *
 *   "third-party frameworks (ADR-036) are supported only through injection,
 *    which the CLI always does."
 *
 * The CLI does not always do it. `mfe:validate` and `check-mfe-drift` both call
 * `generateAllFiles` with no `frameworkVariant`, so both fall through to
 * `deriveBuiltinVariant` — which by construction can only answer `react-rspack`
 * or `angular-webpack`.
 *
 * For the 21 example MFEs, all on built-in frameworks, that is harmless: the two
 * paths are byte-identical (check 4 proves it rather than trusting the ADR).
 * For an MFE on a third-party framework it is not harmless, and the worse of the
 * two is `check-mfe-drift`. It is the only gate that compares generated bytes,
 * and its non-`--check` mode **writes** what it generates. Pointed at a
 * third-party-framework MFE it would have reported every generator-owned file as
 * drifted and then overwritten them with React output — a repair tool
 * corrupting the thing it repairs.
 *
 * Latent, not live: no third-party-framework MFE exists in this repo yet, which
 * is exactly why nothing noticed. ADR-036's whole promise is that adding one is
 * "publish a package", with no platform edit — so the first team to take that
 * promise up is the one who would have found this.
 *
 * Checks 1–4 confirm the structural half and are regression guards. Check 5 is
 * the one that was red.
 *
 * Each proven able to fail: import the framework loader into codegen (1), add a
 * dependency to codegen's package.json (2), make the runtime import a DSL value
 * (3), diverge the derived variant from the injected one (4), drop injection at
 * a call site (5).
 */
import * as fs from 'fs';
import * as path from 'path';
import { parseManifestFile } from '@falese/smt-dsl';
import { generateAllFiles, deriveBuiltinVariant } from '@falese/smt-codegen';
import { resolveFrameworkVariant } from '../../src/framework/loader';

const REPO_ROOT = path.resolve(__dirname, '..', '..');
const CODEGEN_SRC = path.join(REPO_ROOT, 'packages', 'codegen', 'src');

const read = (rel: string): string => fs.readFileSync(path.join(REPO_ROOT, rel), 'utf8');

/** Every non-test `.ts` under a directory, repo-relative. */
function sources(dir: string): string[] {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return entry.name === '__tests__' ? [] : sources(full);
    if (!entry.name.endsWith('.ts') || entry.name.endsWith('.test.ts')) return [];
    return [path.relative(REPO_ROOT, full)];
  });
}

describe('ADR-061: dsl and codegen as first-class packages', () => {
  it('keeps the framework loader out of codegen', () => {
    // ADR-061 §3, and the reason the whole extraction was worth doing: the
    // loader dynamically requires @falese/smt-framework-<name>, so importing it
    // would make a "zero-dep generator" depend on every framework plugin at
    // runtime. Naming those packages in a lookup table is fine — strings are
    // not edges.
    const offenders = sources(CODEGEN_SRC).filter((file) => {
      const text = fs.readFileSync(path.join(REPO_ROOT, file), 'utf8');
      return /^\s*import[^\n]*(framework\/loader|loadFrameworkPlugin)/m.test(text)
        || /require\(['"][^'"]*framework\/loader/.test(text);
    });
    expect(offenders).toEqual([]);

    // The inverted dependency the ADR also names: a package must not reach back
    // into the CLI tree.
    const inverted = sources(CODEGEN_SRC).filter((file) =>
      /from\s+['"](\.\.\/)+src\//.test(fs.readFileSync(path.join(REPO_ROOT, file), 'utf8'))
    );
    expect(inverted).toEqual([]);
  });

  it('holds codegen to the dependency set the decision fixed', () => {
    // "Its only workspace dependencies are @falese/smt-dsl and
    // @falese/smt-contracts, plus ejs and fs-extra/js-yaml. It ships its EJS
    // templates." A framework package appearing here is the coupling ADR-061
    // exists to prevent, and it would arrive as a dependency long before it
    // arrived as an import.
    const pkg = JSON.parse(read(path.join('packages', 'codegen', 'package.json'))) as {
      dependencies?: Record<string, string>;
      files?: string[];
    };
    expect(Object.keys(pkg.dependencies ?? {}).sort()).toEqual([
      '@falese/smt-contracts',
      '@falese/smt-dsl',
      'ejs',
      'fs-extra',
      'js-yaml',
    ]);
    expect(pkg.files).toContain('templates');

    // §4: the cycle is broken by src/dsl no longer existing at all.
    expect(fs.existsSync(path.join(REPO_ROOT, 'src', 'dsl'))).toBe(false);
  });

  it('keeps the runtime free of DSL values', () => {
    // "BaseMFE imports DSL types as `import type` only — erased at runtime — so
    // the ADR-056 boundary test stays green." A value import would put Zod and
    // js-yaml into every generated MFE's bundle through the runtime.
    const text = read(path.join('packages', 'runtime', 'src', 'base-mfe.ts'));
    for (const line of text.split('\n')) {
      if (!line.includes('@falese/smt-dsl')) continue;
      expect(line).toMatch(/import type|import\(/);
    }

    const pkg = JSON.parse(read(path.join('packages', 'runtime', 'package.json'))) as {
      dependencies?: Record<string, string>;
    };
    expect(pkg.dependencies?.['@falese/smt-dsl']).toBeUndefined();
  });

  it.each([
    ['react', path.join('examples', 'abc-kids', 'home')],
    ['angular', path.join('examples', 'meridian-station', 'meridian-life-support')],
  ])('%s: the derived fallback matches an injected variant byte for byte', async (_fw, rel) => {
    // ADR-061's own acceptance condition — "Both paths produce byte-identical
    // output for the built-in frameworks" — is what makes any non-injecting
    // caller safe.
    //
    // The injected side comes from `resolveFrameworkVariant`, the CLI's real
    // resolver, which loads the framework plugin. Passing
    // `deriveBuiltinVariant`'s own output instead would compare the fallback
    // against itself: an earlier draft did exactly that and stayed green while
    // the fallback was deliberately corrupted to answer `react-rspack` for
    // Angular. The claim is that the pure fallback agrees with the *plugin*,
    // so the plugin has to be the other side of the comparison.
    const dir = path.join(REPO_ROOT, rel);
    const parsed = await parseManifestFile(path.join(dir, 'mfe-manifest.yaml'));
    const manifest = ((parsed as { manifest?: unknown }).manifest ?? parsed) as never;

    expect(deriveBuiltinVariant(manifest)).toEqual(resolveFrameworkVariant(manifest));

    const derived = await generateAllFiles(manifest, dir);
    const injected = await generateAllFiles(manifest, dir, {
      frameworkVariant: resolveFrameworkVariant(manifest),
    });

    const shape = (r: { files: { path: string; content: string }[] }): string[] =>
      r.files.map((f) => `${f.path}\n${f.content}`);
    expect(shape(derived)).toEqual(shape(injected));
  }, 120_000);

  it('injects the resolved variant at every generateAllFiles call site', () => {
    // The claim: "supported only through injection, which the CLI always does."
    // A caller that omits the variant silently gets react-rspack for an MFE on
    // any third-party framework — and check-mfe-drift's non---check mode writes
    // what it generates, so it would overwrite that MFE with React output.
    //
    // Scoped to callers that see a real, arbitrary manifest. Fixture-driven
    // scripts are excluded by name below, with a reason each.
    const EXEMPT = new Map([
      [
        path.join('scripts', 'check-template-typecheck.ts'),
        'generates the two built-in template lanes from synthetic manifests; there is no third-party variant to resolve',
      ],
      [
        path.join('scripts', 'codegen-characterization.ts'),
        'a fixed abc-kids corpus, deliberately pinned to the built-in variant so the byte comparison stays stable',
      ],
    ]);

    const callers = [...sources(path.join(REPO_ROOT, 'src')), ...sources(path.join(REPO_ROOT, 'scripts'))]
      .filter((file) => !EXEMPT.has(file))
      .filter((file) => /\bgenerateAllFiles\s*\(/.test(read(file)));
    expect(callers.length).toBeGreaterThan(0);

    // Checks for the resolution call, not for the word `frameworkVariant`. A
    // substring test passed a break-test that renamed the option to
    // `frameworkVariantX` — the string was still present, and a mention in a
    // comment would have satisfied it just as well. §3 names the function: "the
    // CLI owns framework resolution — resolveFrameworkVariant() … and passes
    // the trio".
    const missing = callers.filter((file) => !/\bresolveFrameworkVariant\s*\(/.test(read(file)));
    expect(missing).toEqual([]);
  });
});
