// Generated by seans-mfe-tool. Do not edit — regenerated on every `remote:generate`.
//
// The wasm-bindgen exports the remote entry calls (ADR-100).
//
// One MFE instance per page, as in the web lane, driven through the SAME
// platform contract the native crate renders: `mount` runs `load` when the
// instance is not ready, then `render` for the capability — state guard,
// transitions and manifest hooks included — and only then asks the
// capability's developer-owned `render` to draw into the slot.

use std::rc::Rc;
use std::sync::Arc;

use wasm_bindgen::prelude::*;
use web_sys::Element;

use meridian_crew_services::{
    BoxFuture, MfeContext, MfeDependencies, MfeError, MfeLifecycleState, NativeMfe, MeridianCrewServicesDataProvider,
    MeridianCrewServicesMfe,
};
use meridian_crew_services::{CrewRosterOutputs, PayStatusOutputs};

/// The provider the browser build starts with: every capability answers with
/// its empty `Outputs`.
///
/// The native crate's transport trait requires `Send` futures, and browser
/// `fetch` futures are not `Send`, so a fetch-backed provider is not generated
/// yet (ADR-100 §Boundaries). A capability that needs data fetches it in its
/// own `render` today.
struct BrowserProvider;

impl MeridianCrewServicesDataProvider for BrowserProvider {
    fn crew_roster(&self) -> BoxFuture<'_, Result<CrewRosterOutputs, MfeError>> {
        Box::pin(async { Ok(CrewRosterOutputs::default()) })
    }
    fn pay_status(&self) -> BoxFuture<'_, Result<PayStatusOutputs, MfeError>> {
        Box::pin(async { Ok(PayStatusOutputs::default()) })
    }
}

thread_local! {
    static MFE: Rc<MeridianCrewServicesMfe> =
        Rc::new(MeridianCrewServicesMfe::new(Arc::new(BrowserProvider), MfeDependencies::default()));
}

fn instance() -> Rc<MeridianCrewServicesMfe> {
    MFE.with(Rc::clone)
}

fn to_js(error: MfeError) -> JsValue {
    JsValue::from_str(&error.to_string())
}

/// The domain capabilities this build can mount.
#[wasm_bindgen]
pub fn capabilities() -> Vec<String> {
    meridian_crew_services::platform::manifest_metadata::DOMAIN_CAPABILITIES
        .iter()
        .map(|c| c.to_string())
        .collect()
}

/// Mount `capability` into `element` — what the remote entry's imperative
/// handle calls (ADR-056). `props_json` is the placement's props.
#[wasm_bindgen]
pub async fn mount(element: Element, capability: String, props_json: String) -> Result<(), JsValue> {
    let mfe = instance();
    if matches!(mfe.state(), MfeLifecycleState::Uninitialized | MfeLifecycleState::Error) {
        mfe.load(MfeContext::new()).await.map_err(to_js)?;
    }
    mfe.render(MfeContext::new().with_capability_id(capability.clone()))
        .await
        .map_err(to_js)?;

    let props: serde_json::Value = serde_json::from_str(&props_json).unwrap_or(serde_json::Value::Null);
    draw(&capability, &element, &props)
}

/// Tear down what `mount` drew, and record the unmount.
#[wasm_bindgen]
pub fn unmount(element: Element, capability: String) {
    while let Some(child) = element.first_child() {
        let _ = element.remove_child(&child);
    }
    instance().hooks().unmount(&capability);
}

/// Dispatch to the capability's developer-owned renderer.
fn draw(capability: &str, element: &Element, props: &serde_json::Value) -> Result<(), JsValue> {
    match capability {
        "CrewRoster" => crate::features::crew_roster::render(element, props),
        "PayStatus" => crate::features::pay_status::render(element, props),
        other => Err(JsValue::from_str(&format!("unknown capability \"{}\"", other))),
    }
}
