// Generated by seans-mfe-tool. Do not edit — regenerated on every `remote:generate`.
//
// manifest-metadata-gen — the executable the SPM build-tool plugin runs.
//
// Reads mfe-manifest.json (the CLI's projection of mfe-manifest.yaml) and
// writes ManifestMetadata.swift. This is the Swift half of "the manifest is
// read by two build systems and neither holds a copy of the truth" (ADR-095).

import Foundation

struct Capability: Decodable {
    let name: String
    let type: String
    let description: String
}

struct ManifestProjection: Decodable {
    let name: String
    let version: String
    let bundleId: String
    let bffEndpoint: String?
    let capabilities: [Capability]
}

let args = CommandLine.arguments
guard args.count == 3 else {
    FileHandle.standardError.write("usage: manifest-metadata-gen <manifest.json> <out.swift>\n".data(using: .utf8)!)
    exit(2)
}

let input = URL(fileURLWithPath: args[1])
let output = URL(fileURLWithPath: args[2])

let manifest: ManifestProjection
do {
    manifest = try JSONDecoder().decode(ManifestProjection.self, from: Data(contentsOf: input))
} catch {
    FileHandle.standardError.write("failed to read \(input.path): \(error)\n".data(using: .utf8)!)
    exit(1)
}

func swiftString(_ s: String) -> String {
    "\"" + s.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"") + "\""
}

let domain = manifest.capabilities.filter { $0.type == "domain" }

var out = """
// Generated at build time by ManifestCodegen. Do not edit and do not commit.
import Foundation

public enum ManifestMetadata {
    public static let name = \(swiftString(manifest.name))
    public static let version = \(swiftString(manifest.version))
    public static let bundleId = \(swiftString(manifest.bundleId))
    public static let bffEndpoint: String? = \(manifest.bffEndpoint.map(swiftString) ?? "nil")

    public static let domainCapabilities: [String] = [
\(domain.map { "        \(swiftString($0.name))," }.joined(separator: "\n"))
    ]

    public static let capabilities: [CapabilityMetadata] = [
\(manifest.capabilities.map { "        CapabilityMetadata(name: \(swiftString($0.name)), type: \(swiftString($0.type)), description: \(swiftString($0.description)))," }.joined(separator: "\n"))
    ]
}

"""

do {
    try out.write(to: output, atomically: true, encoding: .utf8)
} catch {
    FileHandle.standardError.write("failed to write \(output.path): \(error)\n".data(using: .utf8)!)
    exit(1)
}
