// Generated by seans-mfe-tool. Do not edit — regenerated on every `remote:generate`.
//
// GraphQL client for this MFE's BFF (ADR-012, ADR-095).
//
// The Swift mirror of the web lane's generator-owned `src/platform/bff/bff.ts`:
// a generic `query` over the BFF's GraphQL endpoint, with HTTP failures and
// GraphQL errors mapped to typed errors. Like that file, it does NOT generate
// per-capability queries — the BFF's schema is composed by Mesh from the
// manifest's `data.sources` at build time, so codegen cannot know it. The
// documents live beside the capabilities that use them.
//
// The endpoint is baked from the manifest and overridable by environment, the
// same precedence the web connector uses: the MFE and its BFF are one
// deployable unit served from the same origin, so a relative path would resolve
// against the host app rather than the BFF.
//
// Transport is NOT this file's: both this and `MFEBase.doQuery` POST through
// `GraphQLPost.send`. What differs is error policy — see the note there.

import Foundation
#if canImport(FoundationNetworking)
// URLSession lives in FoundationNetworking on Linux. Without this the package
// stops compiling there — and Linux is where the non-UI surface is verified.
import FoundationNetworking
#endif

/// One error returned in a GraphQL response's `errors` array.
public struct BFFGraphQLError: Decodable, Sendable {
    public let message: String
    public let path: [String]?
}

/// What can go wrong talking to the BFF.
public enum BFFError: Error, CustomStringConvertible {
    /// Transport or non-2xx response. Carries the status when there was one.
    case network(String, status: Int?)
    /// The BFF answered, and the answer carried GraphQL errors.
    case graphQL([BFFGraphQLError])
    /// A 200 with neither `data` nor `errors`.
    case emptyResponse

    public var description: String {
        switch self {
        case let .network(message, status):
            return status.map { "BFF request failed (\($0)): \(message)" } ?? "BFF request failed: \(message)"
        case let .graphQL(errors):
            return errors.map(\.message).joined(separator: "\n")
        case .emptyResponse:
            return "BFF returned neither data nor errors"
        }
    }
}

private struct BFFResponse<T: Decodable>: Decodable {
    let data: T?
    let errors: [BFFGraphQLError]?
}

/// The POST body. Generic over the variables so a document can take any
/// `Encodable` payload — GraphQL variables are arbitrary JSON, not strings.
private struct BFFRequest<V: Encodable>: Encodable {
    let query: String
    let variables: V?
}

/// Stands in for `V` when a document takes no variables.
private struct NoVariables: Encodable {}

/// Queries this MFE's BFF.
public struct BFFClient: Sendable {
    /// Baked from the manifest; `BFF_URL` overrides it at runtime.
    public static let defaultEndpoint: URL = {
        guard let url = URL(string: "http://localhost:5005/graphql") else {
            fatalError("mfe-manifest.yaml bff endpoint is not a URL: http://localhost:5005/graphql")
        }
        return url
    }()

    private let endpoint: URL
    private let transport: MFETransport

    public init(endpoint: URL? = nil, transport: @escaping MFETransport = GraphQLPost.urlSession) {
        self.endpoint =
            endpoint
            ?? ProcessInfo.processInfo.environment["BFF_URL"].flatMap(URL.init(string:))
            ?? Self.defaultEndpoint
        self.transport = transport
    }

    /// POST a GraphQL document that takes no variables and decode `data` into `T`.
    public func query<T: Decodable>(
        _ document: String,
        headers: [String: String] = [:],
        as _: T.Type = T.self
    ) async throws -> T {
        try await send(BFFRequest<NoVariables>(query: document, variables: nil), headers: headers)
    }

    /// POST a GraphQL document with variables and decode `data` into `T`.
    public func query<T: Decodable, V: Encodable>(
        _ document: String,
        variables: V,
        headers: [String: String] = [:],
        as _: T.Type = T.self
    ) async throws -> T {
        try await send(BFFRequest(query: document, variables: variables), headers: headers)
    }

    private func send<T: Decodable, V: Encodable>(
        _ payload: BFFRequest<V>,
        headers: [String: String]
    ) async throws -> T {
        let body = try await perform(payload, headers: headers)
        let decoded = try JSONDecoder().decode(BFFResponse<T>.self, from: body)

        // Errors first: a partial response carries both, and a caller asking
        // for typed data should not silently receive half of it.
        if let errors = decoded.errors, !errors.isEmpty {
            throw BFFError.graphQL(errors)
        }
        guard let data = decoded.data else {
            throw BFFError.emptyResponse
        }
        return data
    }

    /// POST and hand back the response body.
    ///
    /// Delegates to `GraphQLPost.send` — the one HTTP path in this package,
    /// shared with `MFEBase.doQuery`. This file used to build its own
    /// URLRequest, set the same headers and check the same status range; the
    /// web lane has that duplication because `BaseMFE` ships in a published
    /// package and cannot import generated code, which is not true here.
    ///
    /// Only the ERROR POLICY stays this file's own: `BFFError` rather than the
    /// transport error, because callers of `query<T>` catch `BFFError`.
    private func perform<V: Encodable>(
        _ payload: BFFRequest<V>,
        headers: [String: String]
    ) async throws -> Data {
        do {
            return try await GraphQLPost.send(
                to: endpoint,
                body: try JSONEncoder().encode(payload),
                headers: headers,
                transport: transport
            )
        } catch let MFETransportError.network(message, status) {
            throw BFFError.network(message, status: status)
        }
    }
}
