// Generated by seans-mfe-tool. Do not edit — regenerated on every `remote:generate`.
//
// GraphQL client for this MFE's BFF (ADR-012, ADR-095).
//
// The Swift mirror of the web lane's generator-owned `src/platform/bff/bff.ts`:
// a generic `query` over the BFF's GraphQL endpoint, with HTTP failures and
// GraphQL errors mapped to typed errors. Like that file, it does NOT generate
// per-capability queries — the BFF's schema is composed by Mesh from the
// manifest's `data.sources` at build time, so codegen cannot know it. The
// documents live beside the capabilities that use them.
//
// The endpoint is baked from the manifest and overridable by environment, the
// same precedence the web connector uses: the MFE and its BFF are one
// deployable unit served from the same origin, so a relative path would resolve
// against the host app rather than the BFF.

import Foundation
#if canImport(FoundationNetworking)
// URLSession lives in FoundationNetworking on Linux. Without this the package
// stops compiling there — and Linux is where the non-UI surface is verified.
import FoundationNetworking
#endif

/// One error returned in a GraphQL response's `errors` array.
public struct BFFGraphQLError: Decodable, Sendable {
    public let message: String
    public let path: [String]?
}

/// What can go wrong talking to the BFF.
public enum BFFError: Error, CustomStringConvertible {
    /// Transport or non-2xx response. Carries the status when there was one.
    case network(String, status: Int?)
    /// The BFF answered, and the answer carried GraphQL errors.
    case graphQL([BFFGraphQLError])
    /// A 200 with neither `data` nor `errors`.
    case emptyResponse

    public var description: String {
        switch self {
        case let .network(message, status):
            return status.map { "BFF request failed (\($0)): \(message)" } ?? "BFF request failed: \(message)"
        case let .graphQL(errors):
            return errors.map(\.message).joined(separator: "\n")
        case .emptyResponse:
            return "BFF returned neither data nor errors"
        }
    }
}

/// Just the `errors` array, for the raw path where `data` has no static type.
private struct ErrorsOnly: Decodable {
    let errors: [BFFGraphQLError]?
}

private struct BFFResponse<T: Decodable>: Decodable {
    let data: T?
    let errors: [BFFGraphQLError]?
}

/// The POST body. Generic over the variables so a document can take any
/// `Encodable` payload — GraphQL variables are arbitrary JSON, not strings.
private struct BFFRequest<V: Encodable>: Encodable {
    let query: String
    let variables: V?
}

/// Stands in for `V` when a document takes no variables.
private struct NoVariables: Encodable {}

/// Queries this MFE's BFF.
public struct BFFClient: Sendable {
    /// Baked from the manifest; `BFF_URL` overrides it at runtime.
    public static let defaultEndpoint = URL(string: "http://localhost:5005/graphql")!

    private let endpoint: URL
    private let session: URLSession

    public init(endpoint: URL? = nil, session: URLSession = .shared) {
        self.endpoint =
            endpoint
            ?? ProcessInfo.processInfo.environment["BFF_URL"].flatMap(URL.init(string:))
            ?? Self.defaultEndpoint
        self.session = session
    }

    /// POST a GraphQL document that takes no variables and decode `data` into `T`.
    public func query<T: Decodable>(
        _ document: String,
        headers: [String: String] = [:],
        as _: T.Type = T.self
    ) async throws -> T {
        try await send(BFFRequest<NoVariables>(query: document, variables: nil), headers: headers)
    }

    /// POST a GraphQL document with variables and decode `data` into `T`.
    public func query<T: Decodable, V: Encodable>(
        _ document: String,
        variables: V,
        headers: [String: String] = [:],
        as _: T.Type = T.self
    ) async throws -> T {
        try await send(BFFRequest(query: document, variables: variables), headers: headers)
    }

    /// Run a document the CALLER named and return the `data` field as raw JSON.
    ///
    /// The `query` platform capability's path: a host hands this MFE a document
    /// at runtime, so there is no type to decode into. `query(_:as:)` is the
    /// other direction — a document this package owns, decoded into a declared
    /// type.
    public func queryRaw(
        _ document: String,
        variables: [String: String]? = nil,
        headers: [String: String] = [:]
    ) async throws -> Data {
        let body = try await perform(BFFRequest(query: document, variables: variables), headers: headers)

        // Errors first, for the same reason the decoding path does it.
        let envelope = try JSONDecoder().decode(ErrorsOnly.self, from: body)
        if let errors = envelope.errors, !errors.isEmpty {
            throw BFFError.graphQL(errors)
        }

        let root = try JSONSerialization.jsonObject(with: body, options: [.fragmentsAllowed])
        guard let object = root as? [String: Any], let data = object["data"], !(data is NSNull) else {
            throw BFFError.emptyResponse
        }
        return try JSONSerialization.data(withJSONObject: data, options: [.fragmentsAllowed])
    }

    private func send<T: Decodable, V: Encodable>(
        _ payload: BFFRequest<V>,
        headers: [String: String]
    ) async throws -> T {
        let body = try await perform(payload, headers: headers)
        let decoded = try JSONDecoder().decode(BFFResponse<T>.self, from: body)

        // Errors first: a partial response carries both, and a caller asking
        // for typed data should not silently receive half of it.
        if let errors = decoded.errors, !errors.isEmpty {
            throw BFFError.graphQL(errors)
        }
        guard let data = decoded.data else {
            throw BFFError.emptyResponse
        }
        return data
    }

    /// POST and hand back the response body. Shared by both query paths so the
    /// transport rules are stated once.
    private func perform<V: Encodable>(
        _ payload: BFFRequest<V>,
        headers: [String: String]
    ) async throws -> Data {
        var request = URLRequest(url: endpoint)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        for (field, value) in headers {
            request.setValue(value, forHTTPHeaderField: field)
        }
        request.httpBody = try JSONEncoder().encode(payload)

        let body: Data
        let response: URLResponse
        do {
            (body, response) = try await session.data(for: request)
        } catch {
            throw BFFError.network(error.localizedDescription, status: nil)
        }

        if let http = response as? HTTPURLResponse, !(200..<300).contains(http.statusCode) {
            throw BFFError.network(
                HTTPURLResponse.localizedString(forStatusCode: http.statusCode),
                status: http.statusCode
            )
        }

        return body
    }
}
