// Generated by seans-mfe-tool. Do not edit — regenerated on every `remote:generate`.
//
// The data provider this MFE's BFF backs (ADR-095).
//
// Generator-owned: the wiring from a capability to a BFF query is mechanical,
// so the platform writes it. What it cannot write is the query itself — the
// BFF's schema is composed by Mesh from `data.sources` at build time — so each
// document lives in a developer-owned `Features/<Cap>Query.swift`, the same
// split the web lane has between generated `bff.ts` and the query a feature
// component writes.

import Foundation

/// Talks to the BFF at `BFFClient.defaultEndpoint`.
public struct BFFMeridianCrewServicesDataProvider: MeridianCrewServicesDataProvider {
    private let client: BFFClient

    public init(client: BFFClient = BFFClient()) {
        self.client = client
    }

    public func crewRoster() async throws -> CrewRosterOutputs {
        try await client.query(CrewRosterQuery.document)
    }

    public func payStatus() async throws -> PayStatusOutputs {
        try await client.query(PayStatusQuery.document)
    }

}
