// Generated by seans-mfe-tool. Do not edit — regenerated on every `remote:generate`.
//
// The manifest's domain capabilities, as a static table (ADR-096).
//
// Generator-owned, and re-stamped on every generate. Each view lives in its own
// developer-owned `Features/<Capability>View.swift`: adding a capability to the
// manifest adds an entry here AND seeds that file, which does not exist yet and
// is therefore written, so the package keeps compiling (ADR-095 §7).
//
// `mfe:validate` reports the remaining case — a view someone deleted — as
// `native-capability-view`, because the reference below is inside
// `#if canImport(SwiftUI)` and compiles out on Linux.

import Foundation
#if canImport(SwiftUI)
import SwiftUI
#endif

public enum CapabilityViewRegistry {
    /// Domain capability ids declared by the manifest, in manifest order.
    public static let declared: [String] = [
        "CrewRoster",
        "PayStatus",
    ]

#if canImport(SwiftUI)
    /// `provider` is handed to the view so it fetches through the same seam the
    /// MFE was constructed with (ADR-096) — a host's stub or the BFF-backed
    /// provider, never a second one the view made for itself.
    @MainActor
    public static func view(for capabilityId: String, provider: any MeridianCrewServicesDataProvider) -> AnyView? {
        switch capabilityId {
        case "CrewRoster": return AnyView(CrewRosterView(provider: provider))
        case "PayStatus": return AnyView(PayStatusView(provider: provider))
        default: return nil
        }
    }
#endif
}
