// Generated by seans-mfe-tool. Do not edit — regenerated on every `remote:generate`.
//
// MeridianCrewServicesMFE — the concrete class (ADR-096).
//
// This sits beside `RemoteMFE` (React/rspack) and `AngularRemoteMFE`
// (Angular/webpack) as a third concrete subclass of the platform base class.
// It is NOT a subclass of either of those, and not of `BaseRemoteMFE` — it
// descends from `NativeMFEBase`, the sibling that carries native acquisition.
// ADR-034 set this shape when it made `AngularRemoteMFE` a sibling of
// `RemoteMFE` rather than a subclass.
//
// Hierarchy:
//
//   MFEBase                 ← rendering of BaseMFE (contract + orchestration)
//     └─ NativeMFEBase      ← sibling of BaseRemoteMFE (Bundle.load acquisition)
//          └─ MeridianCrewServicesMFE   ← this file
//
// It overrides only `mount` — the view selection — exactly the surface a
// generated `RemoteMFE` subclass fills in the web lane. The `query` capability
// needs no override: `MFEBase.doQuery` is a concrete default (ADR-053/070),
// exactly as `BaseMFE.doQuery` is in TypeScript.

import Foundation
#if canImport(SwiftUI)
import SwiftUI
#endif

public final class MeridianCrewServicesMFE: NativeMFEBase {

    /// Stub handlers for every hook the manifest names.
    ///
    /// The web lane generates a stub METHOD per hook on `mfe.ts`, so a manifest
    /// declaring `handler: onLoadBegin` runs the moment it is generated. Swift
    /// cannot resolve a handler to a method by name (ADR-098 §3), so the
    /// equivalent is this map. Without it a generated package would throw on
    /// `load()` for a manifest the web lane runs happily.
    ///
    /// Anything a host passes in `deps.customHandlers` wins over these.
    public static let generatedHandlers: [String: MFEHandler] = [
        // Load · before · onLoadBegin — replace with your implementation.
        "onLoadBegin": { context in
            print("[MeridianCrewServicesMFE][before][onLoadBegin] requestId=\(context.requestId) capability=\(context.capability ?? "-")")
        },
        // Load · after · onLoadComplete — replace with your implementation.
        "onLoadComplete": { context in
            print("[MeridianCrewServicesMFE][after][onLoadComplete] requestId=\(context.requestId) capability=\(context.capability ?? "-")")
        },
        // Load · error · onLoadError — replace with your implementation.
        "onLoadError": { context in
            print("[MeridianCrewServicesMFE][error][onLoadError] requestId=\(context.requestId) capability=\(context.capability ?? "-")")
        },
        // Render · before · onRenderBegin — replace with your implementation.
        "onRenderBegin": { context in
            print("[MeridianCrewServicesMFE][before][onRenderBegin] requestId=\(context.requestId) capability=\(context.capability ?? "-")")
        },
        // Render · after · onRenderComplete — replace with your implementation.
        "onRenderComplete": { context in
            print("[MeridianCrewServicesMFE][after][onRenderComplete] requestId=\(context.requestId) capability=\(context.capability ?? "-")")
        },
        // Render · error · onRenderError — replace with your implementation.
        "onRenderError": { context in
            print("[MeridianCrewServicesMFE][error][onRenderError] requestId=\(context.requestId) capability=\(context.capability ?? "-")")
        },
    ]

    public init(
        provider: MeridianCrewServicesDataProvider = BFFMeridianCrewServicesDataProvider(),
        identity: MFEIdentity = .current,
        deps: MFEDependencies = MFEDependencies()
    ) {
        var resolved = deps
        // Host entries win; the generated stubs fill whatever is left.
        resolved.customHandlers = Self.generatedHandlers.merging(deps.customHandlers) { _, host in host }
        super.init(provider: provider, identity: identity, deps: resolved)
    }

    /// Select and mount a capability's view.
    ///
    /// `CapabilityViewRegistry` is generator-owned and lists every domain
    /// capability this target implements. Each view lives in its own
    /// developer-owned `Features/<Capability>View.swift`, seeded once by
    /// regeneration and never rewritten after that.
    public override func mount(_ capabilityId: String) throws {
        guard CapabilityViewRegistry.declared.contains(capabilityId) else {
            throw MFEStateError(from: state, attempted: .render, allowed: [.ready])
        }
    }


#if canImport(SwiftUI)
    /// The view for a capability, for a host composing this MFE into a screen.
    @MainActor
    public func view(for capabilityId: String) -> AnyView? {
        CapabilityViewRegistry.view(for: capabilityId)
    }
#endif
}
