// Generated by seans-mfe-tool. Do not edit — regenerated on every `remote:generate`.
//
// MFEBase — the Swift rendering of `BaseMFE` (ADR-096).
//
// `packages/runtime/src/base-mfe.ts` owns all orchestration: state guards,
// transitions, lifecycle phases and the error boundary. Subclasses implement
// the `do*()` hooks and never the public capability methods.
//
// TypeScript can only *document* that rule. Swift enforces it: every
// capability below is `public final`, so a subclass cannot override it and
// skip a state guard. `open func do…` is the hook. This rendering is therefore
// strictly stronger than the original, which is the note ADR-096 records.
//
// Class inheritance, not a protocol with a default-implementation extension:
// protocol extensions dispatch statically, so a conforming type declaring its
// own `load()` would silently shadow the extension and bypass every guard with
// no diagnostic. That is precisely what `final` exists to prevent.

import Foundation
#if canImport(FoundationNetworking)
// URLSession lives in FoundationNetworking on Linux.
import FoundationNetworking
#endif

/// Arbitrary JSON, for capability inputs.
///
/// `Context.inputs` is `Record<string, unknown>` in TypeScript. A Swift
/// `[String: String]` could not carry a GraphQL variable that is a number, a
/// bool or an object, which is most of them.
public enum JSONValue: Codable, Sendable, Equatable {
    case string(String)
    case number(Double)
    case bool(Bool)
    case object([String: JSONValue])
    case array([JSONValue])
    case null

    /// The value as a string, when it is one. `nil` for every other case.
    public var stringValue: String? {
        if case let .string(s) = self { return s }
        return nil
    }

    public init(from decoder: Decoder) throws {
        let c = try decoder.singleValueContainer()
        if c.decodeNil() { self = .null }
        else if let v = try? c.decode(Bool.self) { self = .bool(v) }
        else if let v = try? c.decode(Double.self) { self = .number(v) }
        else if let v = try? c.decode(String.self) { self = .string(v) }
        else if let v = try? c.decode([JSONValue].self) { self = .array(v) }
        else if let v = try? c.decode([String: JSONValue].self) { self = .object(v) }
        else {
            throw DecodingError.dataCorruptedError(in: c, debugDescription: "Unrecognised JSON value")
        }
    }

    public func encode(to encoder: Encoder) throws {
        var c = encoder.singleValueContainer()
        switch self {
        case .null: try c.encodeNil()
        case let .bool(v): try c.encode(v)
        case let .number(v): try c.encode(v)
        case let .string(v): try c.encode(v)
        case let .array(v): try c.encode(v)
        case let .object(v): try c.encode(v)
        }
    }
}

extension JSONValue: ExpressibleByStringLiteral {
    public init(stringLiteral value: String) { self = .string(value) }
}

/// How a GraphQL POST actually reaches the network.
///
/// A closure rather than a protocol so a test can inject one without any
/// conformance gymnastics: `URLSession` is not declared `Sendable` on every
/// platform, so a `Sendable` protocol it had to conform to would compile on
/// Darwin and fail on Linux.
public typealias MFETransport = @Sendable (URLRequest) async throws -> (Data, URLResponse)

/// Transport or non-2xx failure. Carries the status when there was one.
public enum MFETransportError: Error, CustomStringConvertible {
    case network(String, status: Int?)

    public var description: String {
        switch self {
        case let .network(message, status):
            return status.map { "BFF request failed (\($0)): \(message)" } ?? "BFF request failed: \(message)"
        }
    }
}

/// **The** HTTP path to a GraphQL endpoint in this package.
///
/// `doQuery` and `BFFClient` both go through here. They used to each build a
/// URLRequest, set the same headers and check the same status range, which is
/// duplication no gate could see: `check:mfe-drift` compares generated bytes to
/// the template and both stayed "correct" while free to diverge, and no test
/// exercised either path.
///
/// The web lane has that duplication for a reason this lane does not share:
/// `BaseMFE` ships in a published package and cannot import the `bff.ts`
/// generated into an MFE later. Here both files are generated into the same
/// module in the same commit.
///
/// What is NOT shared is error policy, and that difference is deliberate:
/// `doQuery` returns a `{data, errors}` envelope because that is what the
/// `query` capability answers with, and `BFFClient.query<T>` throws because a
/// caller decoding into a type should not silently receive half a response.
/// TypeScript splits them the same way.
public enum GraphQLPost {
    /// The default transport. `URLSession.shared`, in one place.
    public static let urlSession: MFETransport = { request in
        try await URLSession.shared.data(for: request)
    }

    /// POST `body` and hand back the response data, or throw.
    public static func send(
        to endpoint: URL,
        body: Data,
        headers: [String: String] = [:],
        transport: MFETransport = GraphQLPost.urlSession
    ) async throws -> Data {
        var request = URLRequest(url: endpoint)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        for (field, value) in headers {
            request.setValue(value, forHTTPHeaderField: field)
        }
        request.httpBody = body

        let data: Data
        let response: URLResponse
        do {
            (data, response) = try await transport(request)
        } catch {
            throw MFETransportError.network(error.localizedDescription, status: nil)
        }

        if let http = response as? HTTPURLResponse, !(200..<300).contains(http.statusCode) {
            throw MFETransportError.network(
                HTTPURLResponse.localizedString(forStatusCode: http.statusCode),
                status: http.statusCode
            )
        }
        return data
    }
}

/// A capability the native lane does not implement.
///
/// Returned-as-success is the failure mode this replaces: a stub answering
/// `accepted: true` claims work it did not do. Throwing names the capability
/// and says what is missing.
public struct MFENotImplementedError: Error, CustomStringConvertible {
    public let capability: MFECapability
    public let detail: String

    public var description: String {
        "\(capability.rawValue) is not implemented in the native lane: \(detail)"
    }
}

/// A lifecycle hook handler. Mirrors `(context: Context) => Promise<void>`.
public typealias MFEHandler = @Sendable (MFEContext) async throws -> Void

/// One telemetry event. Emitted on every hook failure (ADR-002 REQ-043).
public struct MFETelemetryEvent: Sendable {
    public let name: String
    public let capability: String
    public let phase: String
    public let status: String
    public let hook: String
    public let handler: String
    public let message: String
    public let severity: String
}

public protocol MFETelemetry: Sendable {
    func emit(_ event: MFETelemetryEvent)
}

public protocol MFEErrorHandler: Sendable {
    func handle(_ error: Error, context: MFEContext)
}

/// What a host injects. The native subset of `BaseMFEDependencies` (ADR-098 §4).
///
/// TypeScript declares eight; four of them have no native consumer and are
/// deliberately not declared here (ADR-092 §5): `wsClient` (no control-plane
/// transport), `bffUrl` (resolution is `inputs["bffUrl"]` → `BFF_URL` →
/// `identity.bffEndpoint`), `manifestParser` (the manifest is rendered into
/// `ManifestMetadata` at swift build time, not parsed at runtime) and
/// `stateValidator` (the transition table is a frozen static).
public struct MFEDependencies: Sendable {
    /// `platform.x` handlers. There is no native handler library behind this,
    /// so an unlisted `platform.*` throws (ADR-098 §Boundaries).
    public var platformHandlers: [String: MFEHandler]
    /// Custom handlers by manifest name. In Swift this IS the resolution
    /// mechanism, not an override of one — there is no way to look a method up
    /// by name on a plain class (ADR-098 §3).
    public var customHandlers: [String: MFEHandler]
    public var telemetry: MFETelemetry?
    public var errorHandler: MFEErrorHandler?
    /// How `doQuery` reaches the network. TypeScript has no analogue because
    /// its tests stub the global `fetch`; Swift has no global to stub, so
    /// without this seam the `query` capability cannot be tested at all.
    public var transport: MFETransport?

    public init(platformHandlers: [String: MFEHandler] = [:],
                customHandlers: [String: MFEHandler] = [:],
                telemetry: MFETelemetry? = nil,
                errorHandler: MFEErrorHandler? = nil,
                transport: MFETransport? = nil) {
        self.platformHandlers = platformHandlers
        self.customHandlers = customHandlers
        self.telemetry = telemetry
        self.errorHandler = errorHandler
        self.transport = transport
    }
}

/// A handler named by the manifest that nothing supplied.
public struct MFEHandlerNotFoundError: Error, CustomStringConvertible {
    public let handler: String
    public let hint: String
    public var description: String { "Handler not found: \(handler). \(hint)" }
}

/// One lifecycle phase, as the manifest names them.
public enum MFELifecyclePhase: String, Sendable, CaseIterable {
    case before, main, after, error
}

/// One manifest-declared hook, as rendered into `ManifestMetadata` by the SPM
/// build-tool plugin from `mfe-manifest.json` (ADR-040, ADR-098 §5).
public struct MFEHookSpec: Sendable {
    public let capability: String
    public let phase: MFELifecyclePhase
    public let hook: String
    /// One or more handlers, run in order (REQ-045).
    public let handlers: [String]
    /// A failure is reported and swallowed rather than propagated (REQ-042).
    public let contained: Bool

    public init(capability: String, phase: MFELifecyclePhase, hook: String, handlers: [String], contained: Bool) {
        self.capability = capability
        self.phase = phase
        self.hook = hook
        self.handlers = handlers
        self.contained = contained
    }
}

/// Carries the context through the middleware chain by reference, the way a
/// TypeScript object travels through `runPipeline`.
public final class MFEContextBox: @unchecked Sendable {
    public var context: MFEContext
    public init(_ context: MFEContext) { self.context = context }
}

/// Holds a capability's result out of the middleware chain, which returns Void.
final class ResultBox<T>: @unchecked Sendable {
    var value: T?
}

/// Invocation context. Mirrors the runtime's `Context`.
///
/// `@unchecked` because of one member: `error` is an existential `any Error`,
/// which carries no Sendable guarantee, and TypeScript's `Context.error` is the
/// member being mirrored. Everything else here is a value type.
public struct MFEContext: @unchecked Sendable {
    public var requestId: String
    public var capabilityId: String?
    public var inputs: [String: JSONValue]
    /// Bearer token, forwarded to the BFF by the default `doQuery`.
    public var jwt: String?
    /// Extra HTTP headers, forwarded to the BFF by the default `doQuery`.
    public var headers: [String: String]
    /// Set by the hook engine before each phase, as TypeScript's does.
    public var phase: MFELifecyclePhase?
    /// The capability currently executing.
    public var capability: String?
    /// Populated for the `error` phase only.
    public var error: Error?

    public init(requestId: String = UUID().uuidString,
                capabilityId: String? = nil,
                inputs: [String: JSONValue] = [:],
                jwt: String? = nil,
                headers: [String: String] = [:]) {
        self.jwt = jwt
        self.headers = headers
        self.requestId = requestId
        self.capabilityId = capabilityId
        self.inputs = inputs
    }
}

open class MFEBase {
    /// Current lifecycle state. Writable only through `transition(to:)`.
    public private(set) var state: MFELifecycleState = .uninitialized

    /// Transition history, for the same diagnostic reason `BaseMFE` keeps one.
    public private(set) var stateHistory: [(from: MFELifecycleState, to: MFELifecycleState, at: Date)] = []

    public let identity: MFEIdentity

    /// Injected handler maps, telemetry and error reporting (ADR-098 §4).
    public let deps: MFEDependencies

    /// ADR-001's re-entrancy guard: a manifest may map a hook to a method that
    /// invokes the capability the hook is attached to, and that cycle is
    /// invisible to its author. Keyed by capability+phase, checked where every
    /// phase passes through, so no manifest can opt out of it.
    private var lifecycleStack: [String] = []

    public init(identity: MFEIdentity = .current, deps: MFEDependencies = MFEDependencies()) {
        self.identity = identity
        self.deps = deps
    }

    // MARK: - Orchestration (the base class's, not a subclass's)

    public final func assertState(_ capability: MFECapability, _ context: MFEContext? = nil) throws {
        let allowed = capability.preStates
        // An empty preStates list means "any state, including destroyed" —
        // only `emit` is that permissive, and telemetry must survive teardown.
        guard allowed.isEmpty || allowed.contains(state) else {
            let error = MFEStateError(from: state, attempted: capability, allowed: allowed)
            // TypeScript's assertState notifies deps.errorHandler before
            // throwing; the native lane used to report nothing at all.
            deps.errorHandler?.handle(error, context: context ?? MFEContext(capabilityId: capability.rawValue))
            throw error
        }
    }

    public final func transition(to newState: MFELifecycleState, for capability: MFECapability = .load) throws {
        guard MFELifecycleTransitions.isValid(from: state, to: newState) else {
            // `for:` so an invalid transition during render/refresh/… is not
            // reported as an attempted `load`. Defaulted rather than required
            // because `transition(to:)` is public API a subclass may already
            // call.
            let error = MFEStateError(from: state, attempted: capability, allowed: MFELifecycleTransitions.table[state] ?? [])
            deps.errorHandler?.handle(error, context: MFEContext())
            throw error
        }
        stateHistory.append((from: state, to: newState, at: Date()))
        state = newState
    }

    // MARK: - The capability pipeline (ADR-098 §1)

    /// One step. Mirrors `packages/runtime/src/capability-pipeline.ts`.
    ///
    /// The context travels in a reference box rather than `inout`: a middleware
    /// list is escaping, and an escaping function type cannot carry an `inout`
    /// parameter across `await` the way TypeScript's shared object does.
    public typealias Middleware = (MFEContextBox, () async throws -> Void) async throws -> Void

    private func runStep(_ steps: [Middleware], _ index: Int, _ box: MFEContextBox) async throws {
        guard index < steps.count else { return }
        try await steps[index](box) { try await self.runStep(steps, index + 1, box) }
    }

    /// Run a middleware chain, each step calling the next.
    private func runPipeline(_ steps: [Middleware], _ box: MFEContextBox) async throws {
        try await runStep(steps, 0, box)
    }

    /// Middleware: assert the MFE is in one of the capability's pre-states.
    private func stateGuard(_ capability: MFECapability) -> Middleware {
        { box, next in
            try self.assertState(capability, box.context)
            try await next()
        }
    }

    /// Middleware: transition the state machine. No-op when there is no state.
    private func stateTransition(_ target: MFELifecycleState?, for capability: MFECapability) -> Middleware {
        { _, next in
            if let target { try self.transition(to: target, for: capability) }
            try await next()
        }
    }

    /// Middleware: run one phase's manifest hooks for a capability.
    private func lifecyclePhase(_ capability: MFECapability, _ phase: MFELifecyclePhase) -> Middleware {
        { box, next in
            try await self.executeLifecycle(capability.rawValue, phase, box)
            try await next()
        }
    }

    /// Middleware: on downstream failure run the error phase and the error
    /// state, then rethrow.
    private func errorBoundary(_ capability: MFECapability) -> Middleware {
        { box, next in
            do {
                try await next()
            } catch {
                let errorBox = MFEContextBox(box.context)
                errorBox.context.error = error
                try? await self.executeLifecycle(capability.rawValue, .error, errorBox)
                if let errorState = capability.errorState, self.state != errorState {
                    try? self.transition(to: errorState, for: capability)
                }
                throw error
            }
        }
    }

    /// The capability pipeline, composed in the order
    /// `BaseMFE.executeCapability` composes it.
    ///
    /// The error boundary sits AFTER the guard and the enter-transition on
    /// purpose: an invalid-state or invalid-transition error propagates without
    /// running the capability's error phase or error state.
    private func execute<T>(_ capability: MFECapability, _ context: MFEContext, _ body: @escaping () async throws -> T) async throws -> T {
        let result = ResultBox<T>()
        let box = MFEContextBox(context)
        box.context.capability = capability.rawValue

        let pipeline: [Middleware] = [
            stateGuard(capability),
            stateTransition(capability.enterState, for: capability),
            errorBoundary(capability),
            lifecyclePhase(capability, .before),
            lifecyclePhase(capability, .main),
            { _, next in
                result.value = try await body()
                try await next()
            },
            lifecyclePhase(capability, .after),
            stateTransition(capability.exitState, for: capability),
        ]

        try await runPipeline(pipeline, box)
        guard let value = result.value else {
            throw MFENotImplementedError(capability: capability, detail: "pipeline completed without producing a result")
        }
        return value
    }

    // MARK: - The hook engine (ADR-002, rendered — ADR-098 §2)

    /// Run every hook the manifest declares for one capability phase.
    ///
    /// Skips rather than throws on re-entrancy (ADR-001): the re-entrant call
    /// is the bug, but the outer call is usually work a user is waiting on, and
    /// failing that too turns one authoring mistake into a broken capability.
    private func executeLifecycle(_ capability: String, _ phase: MFELifecyclePhase, _ box: MFEContextBox) async throws {
        let key = "\(capability):\(phase.rawValue)"
        if lifecycleStack.contains(key) { return }

        let hooks = findCapabilityHooks(capability, phase)
        guard !hooks.isEmpty else { return }

        lifecycleStack.append(key)
        defer { lifecycleStack.removeLast() }

        box.context.phase = phase
        box.context.capability = capability

        for hook in hooks {
            try await executeHook(hook, box.context, phase)
        }
    }

    /// The manifest's hooks for one capability+phase.
    ///
    /// A static table lookup rather than a walk over a parsed manifest: the SPM
    /// build-tool plugin renders `ManifestMetadata.hooks` from
    /// `mfe-manifest.json` at swift build time (ADR-095), which is also why
    /// there is no native analogue of `deps.manifestParser`.
    private func findCapabilityHooks(_ capability: String, _ phase: MFELifecyclePhase) -> [MFEHookSpec] {
        // CASE-INSENSITIVE, because the two sides spell the capability
        // differently and always have: `MFECapability.load.rawValue` is "load"
        // (the platform contract's spelling) while the manifest writes "Load"
        // and the projection preserves it. `BaseMFE.findCapabilityConfig`
        // lowercases both sides for exactly this reason; an exact compare here
        // matched nothing, so every manifest hook was inert.
        let wanted = capability.lowercased()
        return ManifestMetadata.hooks.filter {
            $0.capability.lowercased() == wanted && $0.phase == phase
        }
    }

    /// One hook's handlers, in order (REQ-045).
    ///
    /// `contained` reports and swallows (REQ-042). A main-phase failure
    /// propagates; before/after/error continue to the next handler (REQ-042,
    /// REQ-045). Every failure reports (REQ-043).
    private func executeHook(_ hook: MFEHookSpec, _ context: MFEContext, _ phase: MFELifecyclePhase) async throws {
        for handler in hook.handlers {
            do {
                if hook.contained {
                    do {
                        try await invokeHandler(handler, context)
                    } catch {
                        emitHookFailure(hook.hook, handler, error, context, "warn")
                    }
                } else {
                    try await invokeHandler(handler, context)
                }
            } catch {
                emitHookFailure(hook.hook, handler, error, context, phase == .main ? "error" : "warn")
                if phase == .main { throw error }
            }
        }
    }

    /// Resolve and run one handler. THE substitution seam, and the only one.
    ///
    /// ADR-079 deleted `deps.lifecycleExecutor` because a seam wrapped around
    /// the phase loop skipped containment, propagation and telemetry silently.
    /// Consulting the maps here means a substituted handler still runs under
    /// every guarantee above.
    ///
    /// Resolution differs from TypeScript by necessity (ADR-098 §3): there is
    /// no way to look a method up by name on a plain Swift class, so the
    /// handler map IS the mechanism rather than an override of one.
    open func invokeHandler(_ name: String, _ context: MFEContext) async throws {
        if name.hasPrefix("platform.") {
            let platformName = String(name.dropFirst("platform.".count))
            guard let handler = deps.platformHandlers[platformName] else {
                throw MFEHandlerNotFoundError(
                    handler: name,
                    hint: "There is no native platform handler library. Supply it as deps.platformHandlers[\"\(platformName)\"]."
                )
            }
            try await handler(context)
            return
        }

        if let handler = deps.customHandlers[name] {
            try await handler(context)
            return
        }
        // By last segment, as TypeScript does: 'custom.fail' -> 'fail'.
        let lastSegment = name.split(separator: ".").last.map(String.init) ?? name
        if let handler = deps.customHandlers[lastSegment] {
            try await handler(context)
            return
        }
        throw MFEHandlerNotFoundError(
            handler: name,
            hint: "Register it as deps.customHandlers[\"\(lastSegment)\"]. Swift cannot resolve a handler to a method by name, so a manifest hook needs the map entry."
        )
    }

    /// Report a hook failure (REQ-043). Nothing ships an `MFETelemetry`, so
    /// this is silent until a host supplies one.
    private func emitHookFailure(_ hook: String, _ handler: String, _ error: Error, _ context: MFEContext, _ severity: String) {
        deps.telemetry?.emit(MFETelemetryEvent(
            name: "lifecycle-error",
            capability: context.capability ?? "lifecycle",
            phase: context.phase?.rawValue ?? "unknown",
            status: "error",
            hook: hook,
            handler: handler,
            message: String(describing: error),
            severity: severity
        ))
    }

    // MARK: - The ten capabilities — final; subclasses override the do* hooks

    /// Self-registration — returns the MFE manifest and capabilities.
    public final func describe(_ context: MFEContext) async throws -> DescribeResult {
        try await execute(.describe, context) { try await self.doDescribe(context) }
    }

    /// Initialization — connect, warm caches, validate config.
    public final func load(_ context: MFEContext) async throws -> LoadResult {
        try await execute(.load, context) { try await self.doLoad(context) }
    }

    /// The MFE produces its own experience for a resolved capability.
    public final func render(_ context: MFEContext) async throws -> RenderResult {
        try await execute(.render, context) { try await self.doRender(context) }
    }

    /// Data reload in place when state changes but this MFE stays selected.
    public final func refresh(_ context: MFEContext) async throws -> Void {
        try await execute(.refresh, context) { try await self.doRefresh(context) }
    }

    /// Telemetry publication. Does not trigger registry re-evaluation.
    public final func emit(_ context: MFEContext) async throws -> EmitResult {
        try await execute(.emit, context) { try await self.doEmit(context) }
    }

    /// Execute a GraphQL query against this MFE without rendering.
    public final func query(_ context: MFEContext) async throws -> QueryResult {
        try await execute(.query, context) { try await self.doQuery(context) }
    }

    /// GraphQL SDL introspection for registry schema federation.
    public final func schema(_ context: MFEContext) async throws -> SchemaResult {
        try await execute(.schema, context) { try await self.doSchema(context) }
    }

    /// JWT validation — the gate check the daemon runs before render().
    public final func authorizeAccess(_ context: MFEContext) async throws -> Bool {
        try await execute(.authorizeAccess, context) { try await self.doAuthorizeAccess(context) }
    }

    /// Liveness and dependency checks for registry polling.
    public final func health(_ context: MFEContext) async throws -> HealthResult {
        try await execute(.health, context) { try await self.doHealth(context) }
    }

    /// MFE-initiated push of domain state for registry re-evaluation.
    public final func updateControlPlaneState(_ context: MFEContext) async throws -> ControlPlaneStateResult {
        try await execute(.updateControlPlaneState, context) { try await self.doUpdateControlPlaneState(context) }
    }

    // MARK: - Subclass hooks (`protected abstract do*()` in TypeScript)

    open func doDescribe(_ context: MFEContext) async throws -> DescribeResult {
        fatalError("doDescribe must be overridden")
    }

    open func doLoad(_ context: MFEContext) async throws -> LoadResult {
        fatalError("doLoad must be overridden")
    }

    open func doRender(_ context: MFEContext) async throws -> RenderResult {
        fatalError("doRender must be overridden")
    }

    open func doRefresh(_ context: MFEContext) async throws -> Void {
        fatalError("doRefresh must be overridden")
    }

    open func doEmit(_ context: MFEContext) async throws -> EmitResult {
        fatalError("doEmit must be overridden")
    }

    open func doSchema(_ context: MFEContext) async throws -> SchemaResult {
        fatalError("doSchema must be overridden")
    }

    open func doAuthorizeAccess(_ context: MFEContext) async throws -> Bool {
        fatalError("doAuthorizeAccess must be overridden")
    }

    open func doHealth(_ context: MFEContext) async throws -> HealthResult {
        fatalError("doHealth must be overridden")
    }

    open func doUpdateControlPlaneState(_ context: MFEContext) async throws -> ControlPlaneStateResult {
        fatalError("doUpdateControlPlaneState must be overridden")
    }

    // MARK: - query — a CONCRETE default, at the layer TypeScript puts it

    /// Run a GraphQL document against this MFE's BFF.
    ///
    /// `BaseMFE.doQuery` is the one hook that is NOT abstract: it is a working
    /// default on the base class (ADR-053, ADR-070), so this is rendered here
    /// rather than on a subclass. An MFE with no BFF and no override answers
    /// `data: nil` instead of dialing a non-existent endpoint, which is what
    /// makes the capability uniform across every MFE (ADR-070).
    ///
    /// Endpoint resolution, in the order ADR-053 fixes:
    ///   1. `context.inputs["bffUrl"]`
    ///   2. the `BFF_URL` environment variable
    ///   3. `identity.bffEndpoint` — the manifest's, baked at generation
    ///
    /// The TypeScript order has three more entries (a `deps.bffUrl` injection,
    /// and composing `manifest.endpoint` with `data.serve.endpoint`). There is
    /// no dependency container in this lane, and the composition already
    /// happened at generation time — `identity.bffEndpoint` IS
    /// `endpoint + serve.endpoint`. Same resolution, fewer steps to get there.
    open func doQuery(_ context: MFEContext) async throws -> QueryResult {
        let override =
            context.inputs["bffUrl"]?.stringValue
            ?? ProcessInfo.processInfo.environment["BFF_URL"]

        // ADR-070's uniform no-data contract.
        guard let target = override ?? identity.bffEndpoint, let url = URL(string: target) else {
            return QueryResult(data: nil, errors: [])
        }
        guard let document = context.inputs["document"]?.stringValue else {
            return QueryResult(data: nil, errors: ["context.inputs[\"document\"] is required for the query capability"])
        }

        var headers = context.headers
        if let jwt = context.jwt {
            headers["Authorization"] = "Bearer \(jwt)"
        }

        var payload: [String: JSONValue] = ["query": .string(document)]
        if let variables = context.inputs["variables"] {
            payload["variables"] = variables
        }

        let body: Data
        do {
            body = try await GraphQLPost.send(
                to: url,
                body: try JSONEncoder().encode(payload),
                headers: headers,
                transport: deps.transport ?? GraphQLPost.urlSession
            )
        } catch {
            // The envelope policy: `query` answers with errors, it does not
            // throw. `BFFClient.query<T>` throws for the same failure, which is
            // the deliberate half of the difference between the two.
            return QueryResult(data: nil, errors: [String(describing: error)])
        }

        let decoded = try JSONDecoder().decode([String: JSONValue].self, from: body)
        var errors: [String] = []
        if case let .array(list)? = decoded["errors"] {
            errors = list.compactMap { entry in
                if case let .object(fields) = entry { return fields["message"]?.stringValue }
                return nil
            }
        }
        // Partial responses carry both, and the capability returns both.
        guard let data = decoded["data"], data != .null else {
            return QueryResult(data: nil, errors: errors)
        }
        return QueryResult(data: try JSONEncoder().encode(data), errors: errors)
    }
}
