// Generated by seans-mfe-tool. Do not edit — regenerated on every `remote:generate`.
//
// MFEBase — the Swift rendering of `BaseMFE` (ADR-096).
//
// `packages/runtime/src/base-mfe.ts` owns all orchestration: state guards,
// transitions, lifecycle phases and the error boundary. Subclasses implement
// the `do*()` hooks and never the public capability methods.
//
// TypeScript can only *document* that rule. Swift enforces it: every
// capability below is `public final`, so a subclass cannot override it and
// skip a state guard. `open func do…` is the hook. This rendering is therefore
// strictly stronger than the original, which is the note ADR-096 records.
//
// Class inheritance, not a protocol with a default-implementation extension:
// protocol extensions dispatch statically, so a conforming type declaring its
// own `load()` would silently shadow the extension and bypass every guard with
// no diagnostic. That is precisely what `final` exists to prevent.

import Foundation

/// Invocation context. Mirrors the runtime's `Context`.
public struct MFEContext: Sendable {
    public var requestId: String
    public var capabilityId: String?
    public var inputs: [String: String]

    public init(requestId: String = UUID().uuidString,
                capabilityId: String? = nil,
                inputs: [String: String] = [:]) {
        self.requestId = requestId
        self.capabilityId = capabilityId
        self.inputs = inputs
    }
}

open class MFEBase {
    /// Current lifecycle state. Writable only through `transition(to:)`.
    public private(set) var state: MFELifecycleState = .uninitialized

    /// Transition history, for the same diagnostic reason `BaseMFE` keeps one.
    public private(set) var stateHistory: [(from: MFELifecycleState, to: MFELifecycleState, at: Date)] = []

    public let identity: MFEIdentity

    public init(identity: MFEIdentity = .current) {
        self.identity = identity
    }

    // MARK: - Orchestration (the base class's, not a subclass's)

    public final func assertState(_ capability: MFECapability) throws {
        let allowed = capability.preStates
        // An empty preStates list means "any state, including destroyed" —
        // only `emit` is that permissive, and telemetry must survive teardown.
        guard allowed.isEmpty || allowed.contains(state) else {
            throw MFEStateError(from: state, attempted: capability, allowed: allowed)
        }
    }

    public final func transition(to newState: MFELifecycleState) throws {
        guard MFELifecycleTransitions.isValid(from: state, to: newState) else {
            throw MFEStateError(from: state, attempted: .load, allowed: MFELifecycleTransitions.table[state] ?? [])
        }
        stateHistory.append((from: state, to: newState, at: Date()))
        state = newState
    }

    /// The shared capability pipeline: guard → enter → run → exit, with the
    /// error state applied on throw. Mirrors `executeCapability` + the
    /// stateGuard / stateTransition / errorBoundary middleware.
    private func execute<T>(_ capability: MFECapability, _ body: () async throws -> T) async throws -> T {
        try assertState(capability)
        if let enter = capability.enterState { try transition(to: enter) }
        do {
            let result = try await body()
            if let exit = capability.exitState { try transition(to: exit) }
            return result
        } catch {
            if let errorState = capability.errorState, state != errorState {
                try? transition(to: errorState)
            }
            throw error
        }
    }

    // MARK: - The ten capabilities — final; subclasses override the do* hooks

    /// Self-registration — returns the MFE manifest and capabilities.
    public final func describe(_ context: MFEContext) async throws -> DescribeResult {
        try await execute(.describe) { try await self.doDescribe(context) }
    }

    /// Initialization — connect, warm caches, validate config.
    public final func load(_ context: MFEContext) async throws -> LoadResult {
        try await execute(.load) { try await self.doLoad(context) }
    }

    /// The MFE produces its own experience for a resolved capability.
    public final func render(_ context: MFEContext) async throws -> RenderResult {
        try await execute(.render) { try await self.doRender(context) }
    }

    /// Data reload in place when state changes but this MFE stays selected.
    public final func refresh(_ context: MFEContext) async throws -> Void {
        try await execute(.refresh) { try await self.doRefresh(context) }
    }

    /// Telemetry publication. Does not trigger registry re-evaluation.
    public final func emit(_ context: MFEContext) async throws -> EmitResult {
        try await execute(.emit) { try await self.doEmit(context) }
    }

    /// Execute a GraphQL query against this MFE without rendering.
    public final func query(_ context: MFEContext) async throws -> QueryResult {
        try await execute(.query) { try await self.doQuery(context) }
    }

    /// GraphQL SDL introspection for registry schema federation.
    public final func schema(_ context: MFEContext) async throws -> SchemaResult {
        try await execute(.schema) { try await self.doSchema(context) }
    }

    /// JWT validation — the gate check the daemon runs before render().
    public final func authorizeAccess(_ context: MFEContext) async throws -> Bool {
        try await execute(.authorizeAccess) { try await self.doAuthorizeAccess(context) }
    }

    /// Liveness and dependency checks for registry polling.
    public final func health(_ context: MFEContext) async throws -> HealthResult {
        try await execute(.health) { try await self.doHealth(context) }
    }

    /// MFE-initiated push of domain state for registry re-evaluation.
    public final func updateControlPlaneState(_ context: MFEContext) async throws -> ControlPlaneStateResult {
        try await execute(.updateControlPlaneState) { try await self.doUpdateControlPlaneState(context) }
    }

    // MARK: - Subclass hooks (`protected abstract do*()` in TypeScript)

    open func doDescribe(_ context: MFEContext) async throws -> DescribeResult {
        fatalError("doDescribe must be overridden")
    }

    open func doLoad(_ context: MFEContext) async throws -> LoadResult {
        fatalError("doLoad must be overridden")
    }

    open func doRender(_ context: MFEContext) async throws -> RenderResult {
        fatalError("doRender must be overridden")
    }

    open func doRefresh(_ context: MFEContext) async throws -> Void {
        fatalError("doRefresh must be overridden")
    }

    open func doEmit(_ context: MFEContext) async throws -> EmitResult {
        fatalError("doEmit must be overridden")
    }

    open func doQuery(_ context: MFEContext) async throws -> QueryResult {
        fatalError("doQuery must be overridden")
    }

    open func doSchema(_ context: MFEContext) async throws -> SchemaResult {
        fatalError("doSchema must be overridden")
    }

    open func doAuthorizeAccess(_ context: MFEContext) async throws -> Bool {
        fatalError("doAuthorizeAccess must be overridden")
    }

    open func doHealth(_ context: MFEContext) async throws -> HealthResult {
        fatalError("doHealth must be overridden")
    }

    open func doUpdateControlPlaneState(_ context: MFEContext) async throws -> ControlPlaneStateResult {
        fatalError("doUpdateControlPlaneState must be overridden")
    }

}
