// Generated by seans-mfe-tool. Do not edit — regenerated on every `remote:generate`.
//
// The platform contract, rendered into Swift (ADR-096).
//
// Every value below comes from `packages/contracts/src/platform-contract.ts`,
// the canonical framework-neutral contract (ADR-041, ADR-042, ADR-080). It is
// rendered, never hand-written: a hand-kept Swift copy would drift the first
// time a state or capability was added, and nothing would catch it.
//
// `native-contract-pin.test.ts` fails if this file and the TypeScript contract
// ever disagree.

import Foundation

/// The six lifecycle states. Mirrors `MFE_LIFECYCLE_STATES`.
public enum MFELifecycleState: String, CaseIterable, Sendable {
    case uninitialized = "uninitialized"
    case loading = "loading"
    case ready = "ready"
    case rendering = "rendering"
    case error = "error"
    case destroyed = "destroyed"
}

/// The legal edges of the machine, mirroring `MFE_LIFECYCLE_TRANSITIONS`.
///
/// A transition not listed here is a programming error and throws at the
/// boundary rather than corrupting state silently (ADR-042).
public enum MFELifecycleTransitions {
    public static let table: [MFELifecycleState: [MFELifecycleState]] = [
        .uninitialized: [.loading],
        .loading: [.ready, .error],
        .ready: [.loading, .rendering, .destroyed],
        .rendering: [.ready, .error],
        .error: [.loading, .destroyed],
        .destroyed: [],
    ]

    public static func isValid(from: MFELifecycleState, to: MFELifecycleState) -> Bool {
        (table[from] ?? []).contains(to)
    }
}

/// The ten platform capabilities. Mirrors `PLATFORM_CAPABILITIES`.
public enum MFECapability: String, CaseIterable, Sendable {
    case describe = "describe"
    case load = "load"
    case render = "render"
    case refresh = "refresh"
    case emit = "emit"
    case query = "query"
    case schema = "schema"
    case authorizeAccess = "authorizeAccess"
    case health = "health"
    case updateControlPlaneState = "updateControlPlaneState"

    /// States the capability may be invoked from. Empty means any state,
    /// including `destroyed` — only `emit` is that permissive.
    public var preStates: [MFELifecycleState] {
        switch self {
        case .describe: return [.uninitialized, .loading, .ready, .rendering, .error]
        case .load: return [.uninitialized, .ready, .error]
        case .render: return [.ready]
        case .refresh: return [.ready]
        case .emit: return []
        case .query: return [.ready]
        case .schema: return [.ready]
        case .authorizeAccess: return [.ready]
        case .health: return [.uninitialized, .loading, .ready, .rendering, .error]
        case .updateControlPlaneState: return [.ready, .rendering]
        }
    }

    /// State entered before execution, e.g. `load` → `loading`.
    public var enterState: MFELifecycleState? {
        switch self {
        case .describe: return nil
        case .load: return .loading
        case .render: return .rendering
        case .refresh: return nil
        case .emit: return nil
        case .query: return nil
        case .schema: return nil
        case .authorizeAccess: return nil
        case .health: return nil
        case .updateControlPlaneState: return nil
        }
    }

    /// State entered on success.
    public var exitState: MFELifecycleState? {
        switch self {
        case .describe: return nil
        case .load: return .ready
        case .render: return .ready
        case .refresh: return nil
        case .emit: return nil
        case .query: return nil
        case .schema: return nil
        case .authorizeAccess: return nil
        case .health: return nil
        case .updateControlPlaneState: return nil
        }
    }

    /// State entered on failure.
    public var errorState: MFELifecycleState? {
        switch self {
        case .describe: return nil
        case .load: return .error
        case .render: return .error
        case .refresh: return nil
        case .emit: return nil
        case .query: return nil
        case .schema: return nil
        case .authorizeAccess: return nil
        case .health: return nil
        case .updateControlPlaneState: return nil
        }
    }
}

/// Raised when a capability is invoked from a state the contract forbids.
public struct MFEStateError: Error, CustomStringConvertible {
    public let from: MFELifecycleState
    public let attempted: MFECapability
    public let allowed: [MFELifecycleState]

    public var description: String {
        let states = allowed.map(\.rawValue).joined(separator: ", ")
        return "Invalid state for \(attempted.rawValue): in \(from.rawValue), requires one of [\(states)]"
    }
}

/// Raised when a capability id is not one this target implements. Not a state
/// violation — the state may be fine; the id is not in the manifest.
public struct MFEUnknownCapabilityError: Error, CustomStringConvertible {
    public let capabilityId: String
    public let declared: [String]

    public var description: String {
        "Unknown capability \"\(capabilityId)\": this target declares [\(declared.joined(separator: ", "))]"
    }
}
