// Generated by seans-mfe-tool. Do not edit — regenerated on every `remote:generate`.
//
// NativeMFEBase — the native acquisition lifecycle (ADR-096).
//
// This is a SIBLING of `packages/runtime/src/base-remote-mfe.ts`, not a
// rendering of it. `BaseRemoteMFE` reads as framework-neutral but it is
// delivery-mechanism-bound: `fetchContainer(remoteEntry)`, a Module
// Federation container, an MF shared scope, a DOM node to mount into. None of
// that exists in an SPM package, and attaching the native lane under it would
// force a remote-entry fiction.
//
// Correspondence with BaseRemoteMFE:
//
//   fetchContainer(remoteEntry)  →  resolveBundle() / Bundle.load()
//   mountComponent(id, el)       →  mount(_:)        [subclass hook]
//   unmount(containerId)         →  unmount(_:)      [subclass hook]
//   getSharedDependencies()      →  NO ANALOGUE
//
// That last one is the honest asymmetry. A Module Federation shared scope
// deduplicates singletons across separately-fetched bundles at runtime. SPM
// resolves versions at build time and the linker emits one copy, so there is
// nothing to negotiate. We declare no member rather than stub one: the
// platform CONTRACT crosses to native intact; the FEDERATION machinery does
// not, because it was never part of the contract.

import Foundation

open class NativeMFEBase: MFEBase {
    /// The loaded module image. Set by `doLoad`, mirroring
    /// `BaseRemoteMFE.container`.
    public private(set) var bundle: Bundle?

    /// Capability ids currently mounted, mirroring `mountedComponent`.
    public private(set) var mounted: Set<String> = []

    private let provider: MeridianCrewServicesDataProvider

    public init(provider: MeridianCrewServicesDataProvider,
                identity: MFEIdentity = .current,
                deps: MFEDependencies = MFEDependencies()) {
        self.provider = provider
        super.init(identity: identity, deps: deps)
    }

    // MARK: - Subclass hooks (the two that DO cross from BaseRemoteMFE)

    /// Mount a capability's view. The native analogue of `mountComponent`.
    open func mount(_ capabilityId: String) throws {
        fatalError("mount must be overridden")
    }

    /// Tear down a mounted capability. The native analogue of `unmount`.
    open func unmount(_ capabilityId: String) {
        mounted.remove(capabilityId)
    }

    // MARK: - Acquisition

    /// Resolve the module's bundle and load its image.
    ///
    /// This is what `load` actually does on a native target. Swift modules are
    /// acquired by the linker at build time — statically by SPM, or by dyld at
    /// launch for a bundled framework — and iOS forbids `dlopen`ing downloaded
    /// code, so there is no remote entry to fetch. `Bundle.load()` is
    /// Foundation's real module-loading operation and it is not a no-op: it
    /// maps the bundle's image.
    open func resolveBundle() throws -> Bundle {
        let b = Bundle(for: type(of: self))
        if !b.isLoaded {
            // `load()` returns Bool. Discarding it explicitly: a failed load
            // surfaces as `isLoaded` staying false, which the caller's
            // capability-table validation then catches — and the bare call
            // warns under Swift 6.
            _ = b.load()
        }
        return b
    }

    // MARK: - do* hooks implemented at the delivery layer

    /// Initialization — connect, warm caches, validate config.
    ///
    /// Exactly the contract's own wording for `load`. On the web lane the
    /// `remoteEntry.js` fetch already happens BEFORE `doLoad()` is reachable,
    /// because the shell must fetch the bundle to obtain the class at all. So
    /// acquisition was never one of the ten capabilities in either lane; the
    /// lanes differ only in WHEN it happens.
    open override func doLoad(_ context: MFEContext) async throws -> LoadResult {
        let started = Date()
        let resolved = try resolveBundle()
        self.bundle = resolved
        try validateCapabilityTable()
        return LoadResult(
            success: true,
            availableCapabilities: ManifestMetadata.domainCapabilities,
            durationMs: Int(Date().timeIntervalSince(started) * 1000)
        )
    }

    /// The static capability table must agree with the manifest this module
    /// was generated from. It cannot disagree without someone having edited a
    /// generated file, so this is a loud failure rather than a recovery path.
    private func validateCapabilityTable() throws {
        guard !ManifestMetadata.name.isEmpty else {
            throw MFEStateError(from: state, attempted: .load, allowed: [.uninitialized])
        }
    }

    open override func doRender(_ context: MFEContext) async throws -> RenderResult {
        guard let capabilityId = context.capabilityId else {
            throw MFEStateError(from: state, attempted: .render, allowed: [.ready])
        }
        try mount(capabilityId)
        mounted.insert(capabilityId)
        return RenderResult(success: true, capabilityId: capabilityId)
    }

    open override func doRefresh(_ context: MFEContext) async throws {
        // Data reload in place. The provider owns the fetch; there is nothing
        // delivery-mechanism-specific to do here.
    }

    open override func doAuthorizeAccess(_ context: MFEContext) async throws -> Bool {
        true
    }

    open override func doHealth(_ context: MFEContext) async throws -> HealthResult {
        HealthResult(healthy: state != .error, state: state.rawValue)
    }

    /// Self-registration. Answered from the statically generated table with no
    /// I/O — the native counterpart of reading the manifest off the container.
    open override func doDescribe(_ context: MFEContext) async throws -> DescribeResult {
        DescribeResult(
            name: identity.name,
            version: identity.version,
            capabilities: ManifestMetadata.capabilities
        )
    }

    open override func doSchema(_ context: MFEContext) async throws -> SchemaResult {
        SchemaResult(sdl: nil)
    }

    /// Telemetry emission. NOT implemented in the native lane.
    ///
    /// `BaseMFE` emits through an injected `deps.telemetry`; there is no
    /// dependency container here, so there is nowhere for an event to go.
    /// Answering `accepted: true` would claim a delivery that never happened.
    open override func doEmit(_ context: MFEContext) async throws -> EmitResult {
        throw MFENotImplementedError(
            capability: .emit,
            detail: "no telemetry transport — BaseMFE emits through deps.telemetry, which this lane has no analogue for"
        )
    }

    /// Control-plane push. NOT implemented in the native lane.
    ///
    /// `BaseMFE.attachControlPlane(wsClient:)` takes a daemon WebSocket client
    /// and there is no native counterpart, so this had nothing to push and
    /// returned `accepted: true` regardless — a capability reporting success
    /// for work it did not do.
    open override func doUpdateControlPlaneState(_ context: MFEContext) async throws -> ControlPlaneStateResult {
        throw MFENotImplementedError(
            capability: .updateControlPlaneState,
            detail: "no control-plane transport — BaseMFE.attachControlPlane(wsClient:) has no native analogue"
        )
    }
}
