// Generated by scripts/derive-seeds.mjs from seed/station.json — do not hand-edit.
const ModelSeed = [
  {
    "CertificationId": 5531,
    "CrewId": 42,
    "CertificationCode": "DOCKING_CONTROL",
    "ExpiresOnUtc": "2027-01-31T00:00:00Z",
    "Status": "VALID"
  },
  {
    "CertificationId": 5532,
    "CrewId": 42,
    "CertificationCode": "EVA",
    "ExpiresOnUtc": "2026-08-10T00:00:00Z",
    "Status": "EXPIRING"
  },
  {
    "CertificationId": 5533,
    "CrewId": 43,
    "CertificationCode": "HAZMAT",
    "ExpiresOnUtc": "2027-03-15T00:00:00Z",
    "Status": "VALID"
  },
  {
    "CertificationId": 5534,
    "CrewId": 43,
    "CertificationCode": "EVA",
    "ExpiresOnUtc": "2026-12-05T00:00:00Z",
    "Status": "VALID"
  },
  {
    "CertificationId": 5535,
    "CrewId": 44,
    "CertificationCode": "MEDICAL",
    "ExpiresOnUtc": "2027-06-20T00:00:00Z",
    "Status": "VALID"
  },
  {
    "CertificationId": 5536,
    "CrewId": 45,
    "CertificationCode": "DOCKING_CONTROL",
    "ExpiresOnUtc": "2026-07-30T00:00:00Z",
    "Status": "EXPIRING"
  },
  {
    "CertificationId": 5537,
    "CrewId": 45,
    "CertificationCode": "EVA",
    "ExpiresOnUtc": "2026-06-01T00:00:00Z",
    "Status": "EXPIRED"
  },
  {
    "CertificationId": 5538,
    "CrewId": 46,
    "CertificationCode": "FOOD_SAFETY",
    "ExpiresOnUtc": "2027-02-14T00:00:00Z",
    "Status": "VALID"
  },
  {
    "CertificationId": 5539,
    "CrewId": 46,
    "CertificationCode": "MEDICAL",
    "ExpiresOnUtc": "2026-08-01T00:00:00Z",
    "Status": "EXPIRING"
  },
  {
    "CertificationId": 5540,
    "CrewId": 47,
    "CertificationCode": "HAZMAT",
    "ExpiresOnUtc": "2026-05-30T00:00:00Z",
    "Status": "EXPIRED"
  },
  {
    "CertificationId": 5541,
    "CrewId": 48,
    "CertificationCode": "MEDICAL",
    "ExpiresOnUtc": "2027-09-09T00:00:00Z",
    "Status": "VALID"
  },
  {
    "CertificationId": 5542,
    "CrewId": 49,
    "CertificationCode": "DOCKING_CONTROL",
    "ExpiresOnUtc": "2027-04-22T00:00:00Z",
    "Status": "VALID"
  }
];

module.exports = ModelSeed;
