// Generated by scripts/derive-seeds.mjs from seed/station.json — do not hand-edit.
const ModelSeed = [
  {
    "CrewId": 42,
    "CrewMemberName": "Imani Okafor",
    "Section": "OPERATIONS",
    "DutyStatus": "ON_DUTY",
    "BerthAssignment": "HAB-2-114"
  },
  {
    "CrewId": 43,
    "CrewMemberName": "Wei Zhang",
    "Section": "ENGINEERING",
    "DutyStatus": "ON_DUTY",
    "BerthAssignment": "HAB-2-115"
  },
  {
    "CrewId": 44,
    "CrewMemberName": "Sofia Marek",
    "Section": "MEDICAL",
    "DutyStatus": "OFF_DUTY",
    "BerthAssignment": "HAB-3-021"
  },
  {
    "CrewId": 45,
    "CrewMemberName": "Dmitri Volkov",
    "Section": "OPERATIONS",
    "DutyStatus": "ON_DUTY",
    "BerthAssignment": "HAB-2-116"
  },
  {
    "CrewId": 46,
    "CrewMemberName": "Amara Diallo",
    "Section": "HOSPITALITY",
    "DutyStatus": "ON_DUTY",
    "BerthAssignment": "HAB-4-007"
  },
  {
    "CrewId": 47,
    "CrewMemberName": "Jonas Berg",
    "Section": "ENGINEERING",
    "DutyStatus": "LEAVE",
    "BerthAssignment": "HAB-3-030"
  },
  {
    "CrewId": 48,
    "CrewMemberName": "Priya Nair",
    "Section": "MEDICAL",
    "DutyStatus": "ON_DUTY",
    "BerthAssignment": "HAB-3-022"
  },
  {
    "CrewId": 49,
    "CrewMemberName": "Tomás Rivera",
    "Section": "OPERATIONS",
    "DutyStatus": "OFF_DUTY",
    "BerthAssignment": "HAB-2-117"
  }
];

module.exports = ModelSeed;
