// Generated by scripts/derive-seeds.mjs from seed/station.json — do not hand-edit.
const ModelSeed = [
  {
    "ModuleId": 1,
    "ModuleName": "Docking Ring A",
    "DeckZone": "RING-A",
    "ModuleType": "DOCKING"
  },
  {
    "ModuleId": 2,
    "ModuleName": "Habitat Block 2",
    "DeckZone": "HAB-2",
    "ModuleType": "HABITAT"
  },
  {
    "ModuleId": 3,
    "ModuleName": "Life Support Ring B",
    "DeckZone": "RING-B",
    "ModuleType": "LIFE_SUPPORT"
  },
  {
    "ModuleId": 4,
    "ModuleName": "Concourse A",
    "DeckZone": "CONCOURSE-A",
    "ModuleType": "CONCOURSE"
  },
  {
    "ModuleId": 5,
    "ModuleName": "Power Core",
    "DeckZone": "CORE",
    "ModuleType": "POWER"
  },
  {
    "ModuleId": 6,
    "ModuleName": "Habitat Block 3",
    "DeckZone": "HAB-3",
    "ModuleType": "HABITAT"
  }
];

module.exports = ModelSeed;
