// Generated by scripts/derive-seeds.mjs from seed/station.json — do not hand-edit.
const ModelSeed = [
  {
    "PassengerId": 30011,
    "PassengerName": "Rosa Delgado",
    "DockingNo": 4025,
    "CabinClass": "BUSINESS",
    "ClearanceStatus": "CLEARED"
  },
  {
    "PassengerId": 30012,
    "PassengerName": "Ken Watanabe",
    "DockingNo": 4025,
    "CabinClass": "ECONOMY",
    "ClearanceStatus": "CLEARED"
  },
  {
    "PassengerId": 30013,
    "PassengerName": "Fatima Al-Sayed",
    "DockingNo": 4025,
    "CabinClass": "STATEROOM",
    "ClearanceStatus": "CLEARED"
  },
  {
    "PassengerId": 30014,
    "PassengerName": "Marcus Boone",
    "DockingNo": 4025,
    "CabinClass": "ECONOMY",
    "ClearanceStatus": "FLAGGED"
  },
  {
    "PassengerId": 30015,
    "PassengerName": "Lena Novak",
    "DockingNo": 4025,
    "CabinClass": "ECONOMY",
    "ClearanceStatus": "CLEARED"
  },
  {
    "PassengerId": 30016,
    "PassengerName": "Yusuf Kamara",
    "DockingNo": 4025,
    "CabinClass": "BUSINESS",
    "ClearanceStatus": "CLEARED"
  },
  {
    "PassengerId": 30017,
    "PassengerName": "Ada Lindqvist",
    "DockingNo": 4025,
    "CabinClass": "ECONOMY",
    "ClearanceStatus": "PENDING"
  },
  {
    "PassengerId": 30018,
    "PassengerName": "Owen Hale",
    "DockingNo": 4030,
    "CabinClass": "ECONOMY",
    "ClearanceStatus": "PENDING"
  },
  {
    "PassengerId": 30019,
    "PassengerName": "Mei Fong",
    "DockingNo": 4030,
    "CabinClass": "BUSINESS",
    "ClearanceStatus": "PENDING"
  },
  {
    "PassengerId": 30020,
    "PassengerName": "Silas Ward",
    "DockingNo": 4025,
    "CabinClass": "ECONOMY",
    "ClearanceStatus": "CLEARED"
  }
];

module.exports = ModelSeed;
