// Generated by scripts/derive-seeds.mjs from seed/station.json — do not hand-edit.
const ModelSeed = [
  {
    "StallId": 218,
    "VendorId": 105,
    "ConcourseZone": "CONCOURSE-A",
    "StallNo": "A-18",
    "LeaseCredits": 5400.5
  },
  {
    "StallId": 219,
    "VendorId": 106,
    "ConcourseZone": "CONCOURSE-A",
    "StallNo": "A-22",
    "LeaseCredits": 7200
  },
  {
    "StallId": 305,
    "VendorId": 107,
    "ConcourseZone": "CONCOURSE-B",
    "StallNo": "B-04",
    "LeaseCredits": 3950.75
  },
  {
    "StallId": 306,
    "VendorId": 108,
    "ConcourseZone": "CONCOURSE-B",
    "StallNo": "B-11",
    "LeaseCredits": 6100
  },
  {
    "StallId": 220,
    "VendorId": 109,
    "ConcourseZone": "CONCOURSE-A",
    "StallNo": "A-03",
    "LeaseCredits": 4800.25
  },
  {
    "StallId": 307,
    "VendorId": 110,
    "ConcourseZone": "CONCOURSE-B",
    "StallNo": "B-19",
    "LeaseCredits": 2900
  }
];

module.exports = ModelSeed;
