// Generated by scripts/derive-seeds.mjs from seed/station.json — do not hand-edit.
const ModelSeed = [
  {
    "ReadingId": 91001,
    "ModuleId": 3,
    "MetricKind": "O2_PARTIAL_PRESSURE",
    "MetricValue": 21.2,
    "RecordedAtUtc": "2026-07-18T05:40:00Z",
    "AlertLevel": "NOMINAL"
  },
  {
    "ReadingId": 91002,
    "ModuleId": 3,
    "MetricKind": "CO2_PPM",
    "MetricValue": 640,
    "RecordedAtUtc": "2026-07-18T05:40:00Z",
    "AlertLevel": "WATCH"
  },
  {
    "ReadingId": 91003,
    "ModuleId": 3,
    "MetricKind": "TEMP_C",
    "MetricValue": 21.5,
    "RecordedAtUtc": "2026-07-18T05:40:00Z",
    "AlertLevel": "NOMINAL"
  },
  {
    "ReadingId": 91004,
    "ModuleId": 3,
    "MetricKind": "PRESSURE_KPA",
    "MetricValue": 101.1,
    "RecordedAtUtc": "2026-07-18T05:40:00Z",
    "AlertLevel": "NOMINAL"
  },
  {
    "ReadingId": 91005,
    "ModuleId": 2,
    "MetricKind": "O2_PARTIAL_PRESSURE",
    "MetricValue": 20.9,
    "RecordedAtUtc": "2026-07-18T05:41:00Z",
    "AlertLevel": "NOMINAL"
  },
  {
    "ReadingId": 91006,
    "ModuleId": 2,
    "MetricKind": "CO2_PPM",
    "MetricValue": 480,
    "RecordedAtUtc": "2026-07-18T05:41:00Z",
    "AlertLevel": "NOMINAL"
  },
  {
    "ReadingId": 91007,
    "ModuleId": 2,
    "MetricKind": "TEMP_C",
    "MetricValue": 22.1,
    "RecordedAtUtc": "2026-07-18T05:41:00Z",
    "AlertLevel": "NOMINAL"
  },
  {
    "ReadingId": 91008,
    "ModuleId": 6,
    "MetricKind": "CO2_PPM",
    "MetricValue": 1180,
    "RecordedAtUtc": "2026-07-18T05:42:00Z",
    "AlertLevel": "CRITICAL"
  },
  {
    "ReadingId": 91009,
    "ModuleId": 6,
    "MetricKind": "O2_PARTIAL_PRESSURE",
    "MetricValue": 20.1,
    "RecordedAtUtc": "2026-07-18T05:42:00Z",
    "AlertLevel": "WATCH"
  },
  {
    "ReadingId": 91010,
    "ModuleId": 6,
    "MetricKind": "TEMP_C",
    "MetricValue": 23.9,
    "RecordedAtUtc": "2026-07-18T05:42:00Z",
    "AlertLevel": "WATCH"
  },
  {
    "ReadingId": 91011,
    "ModuleId": 1,
    "MetricKind": "PRESSURE_KPA",
    "MetricValue": 100.8,
    "RecordedAtUtc": "2026-07-18T05:43:00Z",
    "AlertLevel": "NOMINAL"
  },
  {
    "ReadingId": 91012,
    "ModuleId": 1,
    "MetricKind": "TEMP_C",
    "MetricValue": 19.4,
    "RecordedAtUtc": "2026-07-18T05:43:00Z",
    "AlertLevel": "NOMINAL"
  },
  {
    "ReadingId": 91013,
    "ModuleId": 4,
    "MetricKind": "TEMP_C",
    "MetricValue": 22.8,
    "RecordedAtUtc": "2026-07-18T05:44:00Z",
    "AlertLevel": "NOMINAL"
  },
  {
    "ReadingId": 91014,
    "ModuleId": 4,
    "MetricKind": "CO2_PPM",
    "MetricValue": 720,
    "RecordedAtUtc": "2026-07-18T05:44:00Z",
    "AlertLevel": "WATCH"
  },
  {
    "ReadingId": 91015,
    "ModuleId": 5,
    "MetricKind": "POWER_KW",
    "MetricValue": 8420,
    "RecordedAtUtc": "2026-07-18T05:45:00Z",
    "AlertLevel": "NOMINAL"
  },
  {
    "ReadingId": 91016,
    "ModuleId": 5,
    "MetricKind": "TEMP_C",
    "MetricValue": 31.2,
    "RecordedAtUtc": "2026-07-18T05:45:00Z",
    "AlertLevel": "WATCH"
  }
];

module.exports = ModelSeed;
