// Generated by scripts/derive-seeds.mjs from seed/station.json — do not hand-edit.
const ModelSeed = [
  {
    "VendorId": 105,
    "VendorName": "Red Dust Noodle Bar",
    "ConcourseZone": "CONCOURSE-A",
    "CuisineOrCategory": "Noodles",
    "LicenseStatus": "ACTIVE"
  },
  {
    "VendorId": 106,
    "VendorName": "Orbit Outfitters",
    "ConcourseZone": "CONCOURSE-A",
    "CuisineOrCategory": "Outfitters",
    "LicenseStatus": "ACTIVE"
  },
  {
    "VendorId": 107,
    "VendorName": "Lagrange Coffee",
    "ConcourseZone": "CONCOURSE-B",
    "CuisineOrCategory": "Coffee",
    "LicenseStatus": "PROBATION"
  },
  {
    "VendorId": 108,
    "VendorName": "The Vacuum Lounge",
    "ConcourseZone": "CONCOURSE-B",
    "CuisineOrCategory": "Bar",
    "LicenseStatus": "ACTIVE"
  },
  {
    "VendorId": 109,
    "VendorName": "Ring B Pharmacy",
    "ConcourseZone": "CONCOURSE-A",
    "CuisineOrCategory": "Pharmacy",
    "LicenseStatus": "ACTIVE"
  },
  {
    "VendorId": 110,
    "VendorName": "Starlight Sundries",
    "ConcourseZone": "CONCOURSE-B",
    "CuisineOrCategory": "Convenience",
    "LicenseStatus": "SUSPENDED"
  }
];

module.exports = ModelSeed;
