
/**
 * abckidsflappyMFE bootstrap
 *
 * Instantiates abckidsflappyMFE and calls load() so the full doLoad lifecycle
 * runs and its console logs are visible in the browser DevTools.
 *
 * This fires once when the Module Federation remote bundle is first imported
 * by the shell (i.e. when remote.tsx is evaluated).
 *
 * @generated By seans-mfe-tool CLI — regenerated on every codegen run.
 *            Do not edit by hand; changes will be overwritten.
 */
import { abckidsflappyMFE } from './mfe';

const manifest = {
  "name": "abc-kids-flappy",
  "version": "1.0.0",
  "type": "remote",
  "language": "typescript",
  "framework": "react",
  "bundler": "rspack",
  "description": "Flappy Bird — tap to flap, avoid pipes, keep score!",
  "owner": "abc-kids-team",
  "tags": [
    "kids",
    "game",
    "flappy-bird",
    "arcade"
  ],
  "category": "games",
  "endpoint": "http://localhost:3001",
  "remoteEntry": "http://localhost:3001/remoteEntry.js",
  "discovery": "http://localhost:3001/.well-known/mfe-manifest.yaml",
  "capabilities": [
    {
      "PlayGame": {
        "type": "domain",
        "description": "Play the Flappy Bird game on an HTML5 Canvas"
      }
    },
    {
      "ShowCover": {
        "type": "domain",
        "description": "Show the Flappy Bird game cover card with title and art"
      }
    },
    {
      "GetGameInfo": {
        "type": "domain",
        "description": "Return game metadata including title, age range, and description"
      }
    },
    {
      "Load": {
        "type": "platform",
        "lifecycle": {
          "before": [
            {
              "detectExecutionContext": {
                "handler": "detectExecutionContext",
                "source": "../../handlers/detectExecutionContext",
                "description": "Detect shell vs standalone via URL origin (ADR-072)"
              }
            },
            {
              "onLoadBegin": {
                "handler": "onLoadBegin",
                "description": "Log load lifecycle entry"
              }
            }
          ],
          "after": [
            {
              "onLoadComplete": {
                "handler": "onLoadComplete",
                "description": "Log load success and available components"
              }
            }
          ],
          "error": [
            {
              "onLoadError": {
                "handler": "onLoadError",
                "description": "Log load failure",
                "contained": true
              }
            }
          ]
        }
      }
    },
    {
      "Render": {
        "type": "platform",
        "lifecycle": {
          "before": [
            {
              "onRenderBegin": {
                "handler": "onRenderBegin",
                "description": "Log render lifecycle entry"
              }
            }
          ],
          "after": [
            {
              "onRenderComplete": {
                "handler": "onRenderComplete",
                "description": "Log render success"
              }
            }
          ],
          "error": [
            {
              "onRenderError": {
                "handler": "onRenderError",
                "description": "Log render failure",
                "contained": true
              }
            }
          ]
        }
      }
    }
  ],
  "dependencies": {
    "runtime": {
      "react": "^18.2.0",
      "react-dom": "^18.2.0"
    },
    "design-system": {
      "@mui/material": "^5.14.0",
      "@emotion/react": "^11.11.1",
      "@emotion/styled": "^11.11.0"
    }
  }
};

export const mfe = new abckidsflappyMFE(manifest);

export const mfeReady: Promise<void> = mfe
  .load({
    inputs: {
      remoteEntry: manifest.remoteEntry,
    },
  })
  .then((result) => {
    console.log(
      '[abckidsflappyMFE] bootstrap load() complete \u2014 status:',
      result.status,
      '\u2014 components:',
      result.availableComponents
    );
  })
  .catch((err) => {
    console.error('[abckidsflappyMFE] bootstrap load() failed:', err);
  });
