

import { AngularRemoteMFE } from '@seans-mfe-tool/runtime/angular';
import type { Context, LoadResult, RenderResult, QueryResult} from '@seans-mfe-tool/runtime';

import type { TelemetryDashboardOutputs, ModuleStatusOutputs, AlertsFeedOutputs } from './types';


import { query as bffQuery } from '../bff/bff';

/**
 * meridianlifesupportMFE
 * @description Meridian Station life support — telemetry dashboard, module status, alerts
 * @generated By seans-mfe-tool CLI from DSL manifest
 *
 * @extends AngularRemoteMFE — ALL 10 platform capabilities are INHERITED:
 *   load(), render(), refresh(), authorizeAccess(), health(), describe(),
 *   schema(), query(), emit(), updateControlPlaneState().
 *
 * Render mounts the named standalone component via bootstrapApplication()
 * from @angular/platform-browser; props are applied as @Input() fields on
 * the bootstrapped instance.
 *
 * DOMAIN CAPABILITIES (this MFE's business logic — implement below):
 *
 *   TelemetryDashboard() — Full telemetry board — every module&#39;s environmental readings from StationOS
 *
 *   ModuleStatus() — Compact per-module status card for the console status rail
 *
 *   AlertsFeed() — Readings at WATCH or CRITICAL alert level, newest first
 *
 */
export class meridianlifesupportMFE extends AngularRemoteMFE {
  constructor(manifest: any) {
    super(manifest);
  }

  // ---------------------------------------------------------------------------
  // Platform Capability Overrides (optional — call super() to preserve base behaviour)
  // ---------------------------------------------------------------------------

  protected override async doLoad(context: Context): Promise<LoadResult> {
    console.log('[meridianlifesupportMFE][doLoad] loading remoteEntry=%s', context.inputs?.remoteEntry ?? '<from manifest>');
    const result = await super.doLoad(context);
    if (result.status === 'loaded') {
      console.log('[meridianlifesupportMFE][doLoad] ready — components=%o duration=%dms', result.availableComponents, result.duration);
    } else {
      console.error('[meridianlifesupportMFE][doLoad] failed — status=%s error=%s', result.status, (result.error as Error | undefined)?.message);
    }
    return result;
  }

  protected override async doRender(context: Context): Promise<RenderResult> {
    console.log('[meridianlifesupportMFE][doRender] rendering component=%s containerId=%s', context.inputs?.component ?? '<auto>', context.inputs?.containerId ?? '<auto>');
    const result = await super.doRender(context);
    console.log('[meridianlifesupportMFE][doRender] result=%s duration=%dms', result.status, result.duration);
    return result;
  }

  /**
   * doQuery — routes mfe.query() calls to the BFF connector.
   *
   * Reads context.inputs.document + variables and dispatches via the generated
   * bff.ts connector. The BFF URL is resolved automatically from
   * manifest.endpoint + data.serve.endpoint (e.g. http://localhost:5003/graphql).
   * Pass context.inputs.bffUrl to override when the shell is on a different origin.
   *
   * Re-generated on every `remote:generate` run — do not edit by hand.
   */
  protected override async doQuery(context: Context): Promise<QueryResult> {
    const { document, variables } = (context.inputs ?? {}) as {
      document: string;
      variables?: Record<string, unknown>;
    };
    try {
      const data = await bffQuery(document, variables, {
        ...(context.jwt ? { Authorization: `Bearer ${context.jwt}` } : {}),
        ...(context.requestId ? { 'X-Request-ID': context.requestId } : {}),
      });
      return { data };
    } catch (err) {
      return { data: null, errors: [{ message: (err as Error).message }] };
    }
  }

  // ---------------------------------------------------------------------------
  // Domain Capabilities — implement your business logic below
  // ---------------------------------------------------------------------------

  /**
   * loadDomainComponent
   * @description Resolves a domain capability name to its Angular standalone component.
   * Called by AngularRemoteMFE.doRender() — do not call directly.
   */
  protected override async loadDomainComponent(name: string): Promise<any> {
    switch (name) {

      case 'TelemetryDashboard':
        return import('../../features/TelemetryDashboard/TelemetryDashboard.component').then(
          (m: any) => m['TelemetryDashboardComponent'] ?? m.default
        );

      case 'ModuleStatus':
        return import('../../features/ModuleStatus/ModuleStatus.component').then(
          (m: any) => m['ModuleStatusComponent'] ?? m.default
        );

      case 'AlertsFeed':
        return import('../../features/AlertsFeed/AlertsFeed.component').then(
          (m: any) => m['AlertsFeedComponent'] ?? m.default
        );

      default:
        throw new Error(`[meridianlifesupportMFE] loadDomainComponent: unknown component "${name}"`);
    }
  }

  /**
   * TelemetryDashboard
   * @description Full telemetry board — every module&#39;s environmental readings from StationOS
   * @generated Stub — replace with your domain implementation.
   */
  async TelemetryDashboard(context: Context): Promise<TelemetryDashboardOutputs> {
    // TODO: Implement TelemetryDashboard domain logic
    return {} as TelemetryDashboardOutputs;
  }

  /**
   * ModuleStatus
   * @description Compact per-module status card for the console status rail
   * @generated Stub — replace with your domain implementation.
   */
  async ModuleStatus(context: Context): Promise<ModuleStatusOutputs> {
    // TODO: Implement ModuleStatus domain logic
    return {} as ModuleStatusOutputs;
  }

  /**
   * AlertsFeed
   * @description Readings at WATCH or CRITICAL alert level, newest first
   * @generated Stub — replace with your domain implementation.
   */
  async AlertsFeed(context: Context): Promise<AlertsFeedOutputs> {
    // TODO: Implement AlertsFeed domain logic
    return {} as AlertsFeedOutputs;
  }

  // ---------------------------------------------------------------------------
  // Lifecycle Hooks — called by the platform during capability execution
  // ---------------------------------------------------------------------------

  /**
   * onLoadBegin
   * @description Log load lifecycle entry
   * @lifecycle before phase
   */
  protected async onLoadBegin(context: Context): Promise<void> {
    console.log('[meridianlifesupportMFE][before][onLoadBegin]', {
      requestId: context.requestId,
      capability: context.capability,
      phase: context.phase,
    });
  }

  /**
   * onLoadComplete
   * @description Log load success and available components
   * @lifecycle after phase
   */
  protected async onLoadComplete(context: Context): Promise<void> {
    console.log('[meridianlifesupportMFE][after][onLoadComplete]', {
      requestId: context.requestId,
      capability: context.capability,
      phase: context.phase,
    });
  }

  /**
   * onLoadError
   * @description Log load failure
   * @lifecycle error phase
   */
  protected async onLoadError(context: Context): Promise<void> {
    console.log('[meridianlifesupportMFE][error][onLoadError]', {
      requestId: context.requestId,
      capability: context.capability,
      phase: context.phase,
    });
  }

  /**
   * onRenderBegin
   * @description Log render lifecycle entry
   * @lifecycle before phase
   */
  protected async onRenderBegin(context: Context): Promise<void> {
    console.log('[meridianlifesupportMFE][before][onRenderBegin]', {
      requestId: context.requestId,
      capability: context.capability,
      phase: context.phase,
    });
  }

  /**
   * onRenderComplete
   * @description Log render success
   * @lifecycle after phase
   */
  protected async onRenderComplete(context: Context): Promise<void> {
    console.log('[meridianlifesupportMFE][after][onRenderComplete]', {
      requestId: context.requestId,
      capability: context.capability,
      phase: context.phase,
    });
  }

  /**
   * onRenderError
   * @description Log render failure
   * @lifecycle error phase
   */
  protected async onRenderError(context: Context): Promise<void> {
    console.log('[meridianlifesupportMFE][error][onRenderError]', {
      requestId: context.requestId,
      capability: context.capability,
      phase: context.phase,
    });
  }

}
