FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY . .

EXPOSE <%= registryPort %>

ENV NODE_ENV=production

CMD ["node", "--loader", "ts-node/esm", "mfe-registry.ts"]
