
/**
 * meridianconsoleMFE bootstrap
 *
 * Instantiates meridianconsoleMFE and calls load() so the full doLoad lifecycle
 * runs and its console logs are visible in the browser DevTools.
 *
 * This fires once when the Module Federation remote bundle is first imported
 * by the shell (i.e. when remote.tsx is evaluated).
 *
 * @generated By seans-mfe-tool CLI — regenerated on every codegen run.
 *            Do not edit by hand; changes will be overwritten.
 */
import { meridianconsoleMFE } from './mfe';

const manifest = {
  "name": "meridian-console",
  "version": "1.0.0",
  "type": "remote",
  "language": "typescript",
  "framework": "react",
  "bundler": "rspack",
  "description": "Meridian Station console — the station operator's home screen and slot provider",
  "owner": "meridian-station",
  "tags": [
    "meridian",
    "console",
    "launcher",
    "slot-provider"
  ],
  "category": "console",
  "endpoint": "http://localhost:5001",
  "remoteEntry": "http://localhost:5001/remoteEntry.js",
  "discovery": "http://localhost:5001/.well-known/mfe-manifest.yaml",
  "capabilities": [
    {
      "StationConsole": {
        "type": "domain",
        "description": "Render the station console — domain menu, status rail, and the berth strip; selecting a domain drives the control plane"
      }
    },
    {
      "Load": {
        "type": "platform",
        "lifecycle": {
          "before": [
            {
              "onLoadBegin": {
                "handler": "onLoadBegin",
                "description": "Log load lifecycle entry"
              }
            }
          ],
          "after": [
            {
              "onLoadComplete": {
                "handler": "onLoadComplete",
                "description": "Log load success and available components"
              }
            }
          ],
          "error": [
            {
              "onLoadError": {
                "handler": "onLoadError",
                "description": "Log load failure",
                "contained": true
              }
            }
          ]
        }
      }
    },
    {
      "Render": {
        "type": "platform",
        "lifecycle": {
          "before": [
            {
              "onRenderBegin": {
                "handler": "onRenderBegin",
                "description": "Log render lifecycle entry"
              }
            }
          ],
          "after": [
            {
              "onRenderComplete": {
                "handler": "onRenderComplete",
                "description": "Log render success"
              }
            }
          ],
          "error": [
            {
              "onRenderError": {
                "handler": "onRenderError",
                "description": "Log render failure",
                "contained": true
              }
            }
          ]
        }
      }
    }
  ],
  "dependencies": {
    "runtime": {
      "react": "^18.0.0",
      "react-dom": "^18.0.0"
    },
    "design-system": {
      "@mui/material": "^5.14.0"
    }
  },
  "providesSlots": [
    {
      "id": "main",
      "description": "Primary work area — the active domain MFE composes here"
    },
    {
      "id": "status",
      "description": "Secondary status rail — compact status cards compose here"
    },
    {
      "id": "berth.{id}",
      "description": "One tile per docking berth on the berth strip, keyed by berth id"
    }
  ]
};

export const mfe = new meridianconsoleMFE(manifest);

export const mfeReady: Promise<void> = mfe
  .load({
    inputs: {
      remoteEntry: manifest.remoteEntry,
    },
  })
  .then((result) => {
    console.log(
      '[meridianconsoleMFE] bootstrap load() complete \u2014 status:',
      result.status,
      '\u2014 components:',
      result.availableComponents
    );
  })
  .catch((err) => {
    console.error('[meridianconsoleMFE] bootstrap load() failed:', err);
  });
