
/**
 * meridiandockingcontrolMFE bootstrap
 *
 * Instantiates meridiandockingcontrolMFE and calls load() so the full doLoad lifecycle
 * runs and its console logs are visible in the browser DevTools.
 *
 * This fires once when the Module Federation remote bundle is first imported
 * by the shell (i.e. when remote.tsx is evaluated).
 *
 * @generated By seans-mfe-tool CLI — regenerated on every codegen run.
 *            Do not edit by hand; changes will be overwritten.
 */
import { meridiandockingcontrolMFE } from './mfe';

const manifest = {
  "name": "meridian-docking-control",
  "version": "1.0.0",
  "type": "remote",
  "language": "typescript",
  "framework": "angular",
  "bundler": "webpack",
  "description": "Meridian Station docking & traffic control — berth board, berth tiles, traffic log",
  "owner": "meridian-station",
  "tags": [
    "meridian",
    "docking",
    "ops",
    "angular"
  ],
  "category": "operations",
  "endpoint": "http://localhost:5002",
  "remoteEntry": "http://localhost:5002/remoteEntry.js",
  "discovery": "http://localhost:5002/.well-known/mfe-manifest.yaml",
  "capabilities": [
    {
      "DockingBoard": {
        "type": "domain",
        "description": "Full berth board — occupancy from Harbormaster joined with outstanding tariff status from StellarLedger"
      }
    },
    {
      "BerthTile": {
        "type": "domain",
        "description": "Compact single-berth tile for the console's keyed berth strip (props.berthId selects the berth)"
      }
    },
    {
      "TrafficLog": {
        "type": "domain",
        "description": "Recent and scheduled dockings — the station traffic picture"
      }
    },
    {
      "Load": {
        "type": "platform",
        "lifecycle": {
          "before": [
            {
              "onLoadBegin": {
                "handler": "onLoadBegin",
                "description": "Log load lifecycle entry"
              }
            }
          ],
          "after": [
            {
              "onLoadComplete": {
                "handler": "onLoadComplete",
                "description": "Log load success and available components"
              }
            }
          ],
          "error": [
            {
              "onLoadError": {
                "handler": "onLoadError",
                "description": "Log load failure",
                "contained": true
              }
            }
          ]
        }
      }
    },
    {
      "Render": {
        "type": "platform",
        "lifecycle": {
          "before": [
            {
              "onRenderBegin": {
                "handler": "onRenderBegin",
                "description": "Log render lifecycle entry"
              }
            }
          ],
          "after": [
            {
              "onRenderComplete": {
                "handler": "onRenderComplete",
                "description": "Log render success"
              }
            }
          ],
          "error": [
            {
              "onRenderError": {
                "handler": "onRenderError",
                "description": "Log render failure",
                "contained": true
              }
            }
          ]
        }
      }
    }
  ],
  "dependencies": {
    "runtime": {
      "@angular/core": "^19.2.16",
      "@angular/common": "^19.2.16",
      "@angular/platform-browser": "^19.2.16",
      "rxjs": "^7.8.0",
      "zone.js": "~0.14.0"
    }
  },
  "data": {
    "sources": [
      {
        "name": "Harbormaster",
        "handler": {
          "openapi": {
            "source": "./specs/harbormaster.yaml"
          }
        }
      },
      {
        "name": "StellarLedger",
        "handler": {
          "openapi": {
            "source": "./specs/stellar-ledger.yaml"
          }
        },
        "transforms": [
          {
            "hoistField": [
              {
                "typeName": "Query",
                "pathConfig": [
                  "listCharges",
                  "result"
                ],
                "newFieldName": "charges"
              },
              {
                "typeName": "Query",
                "pathConfig": [
                  "listValuations",
                  "result"
                ],
                "newFieldName": "valuations"
              },
              {
                "typeName": "Query",
                "pathConfig": [
                  "listAccounts",
                  "result"
                ],
                "newFieldName": "accounts"
              }
            ]
          }
        ]
      }
    ],
    "serve": {
      "endpoint": "/graphql",
      "playground": true
    },
    "mockSwitch": {
      "enabled": true
    }
  }
};

export const mfe = new meridiandockingcontrolMFE(manifest);

export const mfeReady: Promise<void> = mfe
  .load({
    requestId: `bootstrap-${Date.now()}`,
    timestamp: new Date(),
    inputs: {
      remoteEntry: manifest.remoteEntry,
    },
  })
  .then((result) => {
    console.log(
      '[meridiandockingcontrolMFE] bootstrap load() complete \u2014 status:',
      result.status,
      '\u2014 components:',
      result.availableComponents
    );
  })
  .catch((err) => {
    console.error('[meridiandockingcontrolMFE] bootstrap load() failed:', err);
  });
