

import { AngularRemoteMFE } from '@seans-mfe-tool/runtime/angular';
import type { Context, LoadResult, RenderResult, QueryResult} from '@seans-mfe-tool/runtime';

import type { DockingBoardOutputs, BerthTileOutputs, TrafficLogOutputs } from './types';


import { query as bffQuery } from '../bff/bff';

/**
 * meridiandockingcontrolMFE
 * @description Meridian Station docking &amp; traffic control — berth board, berth tiles, traffic log
 * @generated By seans-mfe-tool CLI from DSL manifest
 *
 * @extends AngularRemoteMFE — ALL 10 platform capabilities are INHERITED:
 *   load(), render(), refresh(), authorizeAccess(), health(), describe(),
 *   schema(), query(), emit(), updateControlPlaneState().
 *
 * Render mounts the named standalone component via bootstrapApplication()
 * from @angular/platform-browser; props are applied as @Input() fields on
 * the bootstrapped instance.
 *
 * DOMAIN CAPABILITIES (this MFE's business logic — implement below):
 *
 *   DockingBoard() — Full berth board — occupancy from Harbormaster joined with outstanding tariff status from StellarLedger
 *
 *   BerthTile() — Compact single-berth tile for the console&#39;s keyed berth strip (props.berthId selects the berth)
 *
 *   TrafficLog() — Recent and scheduled dockings — the station traffic picture
 *
 */
export class meridiandockingcontrolMFE extends AngularRemoteMFE {
  constructor(manifest: any) {
    super(manifest);
  }

  // ---------------------------------------------------------------------------
  // Platform Capability Overrides (optional — call super() to preserve base behaviour)
  // ---------------------------------------------------------------------------

  protected override async doLoad(context: Context): Promise<LoadResult> {
    console.log('[meridiandockingcontrolMFE][doLoad] loading remoteEntry=%s', context.inputs?.remoteEntry ?? '<from manifest>');
    const result = await super.doLoad(context);
    if (result.status === 'loaded') {
      console.log('[meridiandockingcontrolMFE][doLoad] ready — components=%o duration=%dms', result.availableComponents, result.duration);
    } else {
      console.error('[meridiandockingcontrolMFE][doLoad] failed — status=%s error=%s', result.status, (result.error as Error | undefined)?.message);
    }
    return result;
  }

  protected override async doRender(context: Context): Promise<RenderResult> {
    console.log('[meridiandockingcontrolMFE][doRender] rendering component=%s containerId=%s', context.inputs?.component ?? '<auto>', context.inputs?.containerId ?? '<auto>');
    const result = await super.doRender(context);
    console.log('[meridiandockingcontrolMFE][doRender] result=%s duration=%dms', result.status, result.duration);
    return result;
  }

  /**
   * doQuery — routes mfe.query() calls to the BFF connector.
   *
   * Reads context.inputs.document + variables and dispatches via the generated
   * bff.ts connector. The BFF URL is resolved automatically from
   * manifest.endpoint + data.serve.endpoint (e.g. http://localhost:5002/graphql).
   * Pass context.inputs.bffUrl to override when the shell is on a different origin.
   *
   * Re-generated on every `remote:generate` run — do not edit by hand.
   */
  protected override async doQuery(context: Context): Promise<QueryResult> {
    const { document, variables } = (context.inputs ?? {}) as {
      document: string;
      variables?: Record<string, unknown>;
    };
    try {
      const data = await bffQuery(document, variables, {
        ...(context.jwt ? { Authorization: `Bearer ${context.jwt}` } : {}),
        ...(context.requestId ? { 'X-Request-ID': context.requestId } : {}),
      });
      return { data };
    } catch (err) {
      return { data: null, errors: [{ message: (err as Error).message }] };
    }
  }

  // ---------------------------------------------------------------------------
  // Domain Capabilities — implement your business logic below
  // ---------------------------------------------------------------------------

  /**
   * loadDomainComponent
   * @description Resolves a domain capability name to its Angular standalone component.
   * Called by AngularRemoteMFE.doRender() — do not call directly.
   */
  protected override async loadDomainComponent(name: string): Promise<any> {
    switch (name) {

      case 'DockingBoard':
        return import('../../features/DockingBoard/DockingBoard.component').then(
          (m: any) => m['DockingBoardComponent'] ?? m.default
        );

      case 'BerthTile':
        return import('../../features/BerthTile/BerthTile.component').then(
          (m: any) => m['BerthTileComponent'] ?? m.default
        );

      case 'TrafficLog':
        return import('../../features/TrafficLog/TrafficLog.component').then(
          (m: any) => m['TrafficLogComponent'] ?? m.default
        );

      default:
        throw new Error(`[meridiandockingcontrolMFE] loadDomainComponent: unknown component "${name}"`);
    }
  }

  /**
   * DockingBoard
   * @description Full berth board — occupancy from Harbormaster joined with outstanding tariff status from StellarLedger
   * @generated Stub — replace with your domain implementation.
   */
  async DockingBoard(context: Context): Promise<DockingBoardOutputs> {
    // TODO: Implement DockingBoard domain logic
    return {} as DockingBoardOutputs;
  }

  /**
   * BerthTile
   * @description Compact single-berth tile for the console&#39;s keyed berth strip (props.berthId selects the berth)
   * @generated Stub — replace with your domain implementation.
   */
  async BerthTile(context: Context): Promise<BerthTileOutputs> {
    // TODO: Implement BerthTile domain logic
    return {} as BerthTileOutputs;
  }

  /**
   * TrafficLog
   * @description Recent and scheduled dockings — the station traffic picture
   * @generated Stub — replace with your domain implementation.
   */
  async TrafficLog(context: Context): Promise<TrafficLogOutputs> {
    // TODO: Implement TrafficLog domain logic
    return {} as TrafficLogOutputs;
  }

  // ---------------------------------------------------------------------------
  // Lifecycle Hooks — called by the platform during capability execution
  // ---------------------------------------------------------------------------

  /**
   * onLoadBegin
   * @description Log load lifecycle entry
   * @lifecycle before phase
   */
  protected async onLoadBegin(context: Context): Promise<void> {
    console.log('[meridiandockingcontrolMFE][before][onLoadBegin]', {
      requestId: context.requestId,
      capability: context.capability,
      phase: context.phase,
    });
  }

  /**
   * onLoadComplete
   * @description Log load success and available components
   * @lifecycle after phase
   */
  protected async onLoadComplete(context: Context): Promise<void> {
    console.log('[meridiandockingcontrolMFE][after][onLoadComplete]', {
      requestId: context.requestId,
      capability: context.capability,
      phase: context.phase,
    });
  }

  /**
   * onLoadError
   * @description Log load failure
   * @lifecycle error phase
   */
  protected async onLoadError(context: Context): Promise<void> {
    console.log('[meridiandockingcontrolMFE][error][onLoadError]', {
      requestId: context.requestId,
      capability: context.capability,
      phase: context.phase,
    });
  }

  /**
   * onRenderBegin
   * @description Log render lifecycle entry
   * @lifecycle before phase
   */
  protected async onRenderBegin(context: Context): Promise<void> {
    console.log('[meridiandockingcontrolMFE][before][onRenderBegin]', {
      requestId: context.requestId,
      capability: context.capability,
      phase: context.phase,
    });
  }

  /**
   * onRenderComplete
   * @description Log render success
   * @lifecycle after phase
   */
  protected async onRenderComplete(context: Context): Promise<void> {
    console.log('[meridiandockingcontrolMFE][after][onRenderComplete]', {
      requestId: context.requestId,
      capability: context.capability,
      phase: context.phase,
    });
  }

  /**
   * onRenderError
   * @description Log render failure
   * @lifecycle error phase
   */
  protected async onRenderError(context: Context): Promise<void> {
    console.log('[meridiandockingcontrolMFE][error][onRenderError]', {
      requestId: context.requestId,
      capability: context.capability,
      phase: context.phase,
    });
  }

}
