/**
 * Demo-mode mock switch (ADR-052)
 * @generated By seans-mfe-tool — regenerated on every codegen run; do not edit by hand.
 *
 * Wraps every Query.* resolver (via Mesh resolversComposition). For each request it
 * decides mock vs live and, when mocking, returns the fixture from ./mocks.json keyed
 * by the GraphQL field name. When no fixture exists or the switch is off, the live
 * upstream resolver runs (next()).
 *
 * Switch precedence (per request):
 *   header `x-bff-mode: mock` -> mock
 *   header `x-bff-mode: live` -> live
 *   no header                 -> DEMO_MODE env var (`true` = mock)
 *
 * Edit the fixtures in ./mocks.json (developer-owned). This file is generated.
 */
const fixtures = require('./mocks.json');

function useMock(context) {
  const mode = context && context.headers && context.headers['x-bff-mode'];
  if (mode === 'mock') return true;
  if (mode === 'live') return false;
  return process.env.DEMO_MODE === 'true';
}

const mockSwitch = (next) => (root, args, context, info) => {
  const fixture = fixtures[info.fieldName];
  if (useMock(context) && fixture !== undefined) {
    return fixture;
  }
  return next(root, args, context, info);
};

module.exports = { mockSwitch };
