
/**
 * meridianconcourseMFE bootstrap
 *
 * Instantiates meridianconcourseMFE and calls load() so the full doLoad lifecycle
 * runs and its console logs are visible in the browser DevTools.
 *
 * This fires once when the Module Federation remote bundle is first imported
 * by the shell (i.e. when remote.tsx is evaluated).
 *
 * @generated By seans-mfe-tool CLI — regenerated on every codegen run.
 *            Do not edit by hand; changes will be overwritten.
 */
import { meridianconcourseMFE } from './mfe';

const manifest = {
  "name": "meridian-concourse",
  "version": "1.0.0",
  "type": "remote",
  "language": "typescript",
  "framework": "react",
  "bundler": "rspack",
  "description": "Meridian Station concourse — vendor directory, stalls, settlements, inbound supplies",
  "owner": "meridian-station",
  "tags": [
    "meridian",
    "concourse",
    "marketplace",
    "react"
  ],
  "category": "services",
  "endpoint": "http://localhost:5006",
  "remoteEntry": "http://localhost:5006/remoteEntry.js",
  "discovery": "http://localhost:5006/.well-known/mfe-manifest.yaml",
  "capabilities": [
    {
      "MarketDirectory": {
        "type": "domain",
        "description": "The three-source screen — StationOS vendors and stalls, StellarLedger settlement standing, Harbormaster inbound supply dockings"
      }
    },
    {
      "Load": {
        "type": "platform",
        "lifecycle": {
          "before": [
            {
              "onLoadBegin": {
                "handler": "onLoadBegin",
                "description": "Log load lifecycle entry"
              }
            }
          ],
          "after": [
            {
              "onLoadComplete": {
                "handler": "onLoadComplete",
                "description": "Log load success and available components"
              }
            }
          ],
          "error": [
            {
              "onLoadError": {
                "handler": "onLoadError",
                "description": "Log load failure",
                "contained": true
              }
            }
          ]
        }
      }
    },
    {
      "Render": {
        "type": "platform",
        "lifecycle": {
          "before": [
            {
              "onRenderBegin": {
                "handler": "onRenderBegin",
                "description": "Log render lifecycle entry"
              }
            }
          ],
          "after": [
            {
              "onRenderComplete": {
                "handler": "onRenderComplete",
                "description": "Log render success"
              }
            }
          ],
          "error": [
            {
              "onRenderError": {
                "handler": "onRenderError",
                "description": "Log render failure",
                "contained": true
              }
            }
          ]
        }
      }
    }
  ],
  "dependencies": {
    "runtime": {
      "react": "^18.0.0",
      "react-dom": "^18.0.0"
    },
    "design-system": {
      "@mui/material": "^5.14.0"
    }
  },
  "data": {
    "sources": [
      {
        "name": "StationOS",
        "handler": {
          "openapi": {
            "source": "./specs/station-os.yaml"
          }
        },
        "transforms": [
          {
            "hoistField": [
              {
                "typeName": "Query",
                "pathConfig": [
                  "GetVendors",
                  "Data"
                ],
                "newFieldName": "vendors"
              },
              {
                "typeName": "Query",
                "pathConfig": [
                  "GetStalls",
                  "Data"
                ],
                "newFieldName": "stalls"
              }
            ]
          }
        ]
      },
      {
        "name": "StellarLedger",
        "handler": {
          "openapi": {
            "source": "./specs/stellar-ledger.yaml"
          }
        },
        "transforms": [
          {
            "hoistField": [
              {
                "typeName": "Query",
                "pathConfig": [
                  "listSettlements",
                  "result"
                ],
                "newFieldName": "settlements"
              }
            ]
          }
        ]
      },
      {
        "name": "Harbormaster",
        "handler": {
          "openapi": {
            "source": "./specs/harbormaster.yaml"
          }
        }
      }
    ],
    "serve": {
      "endpoint": "/graphql",
      "playground": true
    },
    "mockSwitch": {
      "enabled": true
    }
  }
};

export const mfe = new meridianconcourseMFE(manifest);

export const mfeReady: Promise<void> = mfe
  .load({
    // Context requires request identity — a partial literal fails typecheck
    // in every generated project (DX punch list #17).
    requestId: `bootstrap-load-${Date.now()}`,
    timestamp: new Date(),
    inputs: {
      remoteEntry: manifest.remoteEntry,
    },
  })
  .then((result) => {
    console.log(
      '[meridianconcourseMFE] bootstrap load() complete \u2014 status:',
      result.status,
      '\u2014 components:',
      result.availableComponents
    );
  })
  .catch((err) => {
    console.error('[meridianconcourseMFE] bootstrap load() failed:', err);
  });
