
/**
 * abckidshomeMFE bootstrap
 *
 * Instantiates abckidshomeMFE and calls load() so the full doLoad lifecycle
 * runs and its console logs are visible in the browser DevTools.
 *
 * This fires once when the Module Federation remote bundle is first imported
 * by the shell (i.e. when remote.tsx is evaluated).
 *
 * @generated By seans-mfe-tool CLI — regenerated on every codegen run.
 *            Do not edit by hand; changes will be overwritten.
 */
import { abckidshomeMFE } from './mfe';

const manifest = {
  "name": "abc-kids-home",
  "version": "1.0.0",
  "type": "remote",
  "language": "typescript",
  "framework": "react",
  "bundler": "rspack",
  "description": "ABC Kids — the home launcher; pick a game to play!",
  "owner": "abc-kids-team",
  "tags": [
    "kids",
    "launcher",
    "home",
    "shell"
  ],
  "category": "launcher",
  "endpoint": "http://localhost:3015",
  "remoteEntry": "http://localhost:3015/remoteEntry.js",
  "discovery": "http://localhost:3015/.well-known/mfe-manifest.yaml",
  "capabilities": [
    {
      "GameMenu": {
        "type": "domain",
        "description": "Render the ABC Kids home — a tile per registered game; selecting one drives the control plane"
      }
    },
    {
      "Load": {
        "type": "platform",
        "lifecycle": {
          "before": [
            {
              "onLoadBegin": {
                "handler": "onLoadBegin",
                "description": "Log load lifecycle entry"
              }
            }
          ],
          "after": [
            {
              "onLoadComplete": {
                "handler": "onLoadComplete",
                "description": "Log load success and available components"
              }
            }
          ],
          "error": [
            {
              "onLoadError": {
                "handler": "onLoadError",
                "description": "Log load failure",
                "contained": true
              }
            }
          ]
        }
      }
    },
    {
      "Render": {
        "type": "platform",
        "lifecycle": {
          "before": [
            {
              "onRenderBegin": {
                "handler": "onRenderBegin",
                "description": "Log render lifecycle entry"
              }
            }
          ],
          "after": [
            {
              "onRenderComplete": {
                "handler": "onRenderComplete",
                "description": "Log render success"
              }
            }
          ],
          "error": [
            {
              "onRenderError": {
                "handler": "onRenderError",
                "description": "Log render failure",
                "contained": true
              }
            }
          ]
        }
      }
    }
  ],
  "dependencies": {
    "runtime": {
      "react": "^18.2.0",
      "react-dom": "^18.2.0"
    },
    "design-system": {
      "@mui/material": "^5.14.0",
      "@emotion/react": "^11.11.1",
      "@emotion/styled": "^11.11.0"
    }
  },
  "providesSlots": [
    {
      "id": "main",
      "description": "Primary game region"
    },
    {
      "id": "info",
      "description": "Contextual game information region"
    }
  ]
};

export const mfe = new abckidshomeMFE(manifest);

export const mfeReady: Promise<void> = mfe
  .load({
    // Context requires request identity — a partial literal fails typecheck
    // in every generated project (DX punch list #17).
    requestId: `bootstrap-load-${Date.now()}`,
    timestamp: new Date(),
    inputs: {
      remoteEntry: manifest.remoteEntry,
    },
  })
  .then((result) => {
    console.log(
      '[abckidshomeMFE] bootstrap load() complete \u2014 status:',
      result.status,
      '\u2014 components:',
      result.availableComponents
    );
  })
  .catch((err) => {
    console.error('[abckidshomeMFE] bootstrap load() failed:', err);
  });
