/**
 * Remote Entry Point — the home/launcher capability + the ADR-056 presentation
 * handle. Generated by scripts/generate-games.mjs — do not edit by hand.
 */
import { createImperativeHandle } from '@seans-mfe-tool/runtime';
import { mfe, mfeReady } from './platform/base-mfe/bootstrap';
import { GameMenu } from './features/GameMenu/GameMenu.tsx';

export { GameMenu };
export { mfe, mfeReady };

/** Single-capability launcher MFE. The host composes it via
 *  handles.imperative.mount(el, { capability: 'GameMenu', props }). */
export const handles = {
  imperative: createImperativeHandle(mfe, {
    framework: 'react',
    mfeReady,
    defaultCapability: 'GameMenu',
  }),
};

export { default } from './App.tsx';
