// Generated by scripts/derive-seeds.mjs from seed/station.json — do not hand-edit.
const ModelSeed = [
  {
    "berth_id": "b1",
    "berth_class": "medium_freight",
    "occupied_flag": 1,
    "max_mass_kg": 250000,
    "current_docking_id": 4021
  },
  {
    "berth_id": "b2",
    "berth_class": "heavy_bulk",
    "occupied_flag": 1,
    "max_mass_kg": 900000,
    "current_docking_id": 4022
  },
  {
    "berth_id": "b3",
    "berth_class": "light_personnel",
    "occupied_flag": 1,
    "max_mass_kg": 80000,
    "current_docking_id": 4025
  },
  {
    "berth_id": "b4",
    "berth_class": "medium_freight",
    "occupied_flag": 0,
    "max_mass_kg": 250000,
    "current_docking_id": null
  },
  {
    "berth_id": "b5",
    "berth_class": "heavy_bulk",
    "occupied_flag": 1,
    "max_mass_kg": 900000,
    "current_docking_id": 4027
  },
  {
    "berth_id": "b6",
    "berth_class": "light_personnel",
    "occupied_flag": 0,
    "max_mass_kg": 80000,
    "current_docking_id": null
  }
];

module.exports = ModelSeed;
