// Generated by scripts/derive-seeds.mjs from seed/station.json — do not hand-edit.
const ModelSeed = [
  {
    "line_id": 1,
    "docking_id": 4021,
    "sku": "CRYO-CELL-42",
    "description": "Cryogenic fuel cells, crated",
    "qty": 12,
    "declared_mass_kg": 1840.5,
    "hazard_class": "CRYO"
  },
  {
    "line_id": 2,
    "docking_id": 4021,
    "sku": "HAB-PANEL-7",
    "description": "Habitat wall panels",
    "qty": 40,
    "declared_mass_kg": 5200,
    "hazard_class": "NONE"
  },
  {
    "line_id": 3,
    "docking_id": 4021,
    "sku": "MED-ISO-9",
    "description": "Medical isotopes, shielded",
    "qty": 2,
    "declared_mass_kg": 18.2,
    "hazard_class": "RADIOLOGICAL"
  },
  {
    "line_id": 1,
    "docking_id": 4022,
    "sku": "ORE-FE-RAW",
    "description": "Iron ore, unprocessed",
    "qty": 900,
    "declared_mass_kg": 88000,
    "hazard_class": "NONE"
  },
  {
    "line_id": 2,
    "docking_id": 4022,
    "sku": "ACID-H2SO4",
    "description": "Sulfuric acid drums",
    "qty": 24,
    "declared_mass_kg": 3100,
    "hazard_class": "CORROSIVE"
  },
  {
    "line_id": 1,
    "docking_id": 4027,
    "sku": "GRAIN-BULK",
    "description": "Grain, bulk containers",
    "qty": 300,
    "declared_mass_kg": 42000,
    "hazard_class": "NONE"
  },
  {
    "line_id": 2,
    "docking_id": 4027,
    "sku": "BIO-CULT-3",
    "description": "Live bio cultures",
    "qty": 6,
    "declared_mass_kg": 240,
    "hazard_class": "BIO"
  },
  {
    "line_id": 1,
    "docking_id": 4019,
    "sku": "SCRAP-ALLOY",
    "description": "Alloy scrap, baled",
    "qty": 120,
    "declared_mass_kg": 15000,
    "hazard_class": "NONE"
  }
];

module.exports = ModelSeed;
