// Generated by scripts/derive-seeds.mjs from seed/station.json — do not hand-edit.
const ModelSeed = [
  {
    "vessel_registry_no": "VR-88213",
    "vessel_name": "Aurora Freight Nine",
    "operator_name": "Helios Cargo Lines",
    "max_capacity_kg": 300000
  },
  {
    "vessel_registry_no": "VR-77045",
    "vessel_name": "Cinder Hauler",
    "operator_name": "Vulcan Bulk Haulage",
    "max_capacity_kg": 850000
  },
  {
    "vessel_registry_no": "VR-91102",
    "vessel_name": "Starlark",
    "operator_name": "Meridian Transit",
    "max_capacity_kg": 60000
  },
  {
    "vessel_registry_no": "VR-66320",
    "vessel_name": "Pale Horizon",
    "operator_name": "Helios Cargo Lines",
    "max_capacity_kg": 280000
  },
  {
    "vessel_registry_no": "VR-55871",
    "vessel_name": "Kestrel Run",
    "operator_name": "Quickstep Couriers",
    "max_capacity_kg": 90000
  },
  {
    "vessel_registry_no": "VR-49008",
    "vessel_name": "Iron Meridian",
    "operator_name": "Vulcan Bulk Haulage",
    "max_capacity_kg": 880000
  },
  {
    "vessel_registry_no": "VR-83555",
    "vessel_name": "Nightjar",
    "operator_name": "Quickstep Couriers",
    "max_capacity_kg": 85000
  },
  {
    "vessel_registry_no": "VR-72410",
    "vessel_name": "Solace",
    "operator_name": "Meridian Transit",
    "max_capacity_kg": 65000
  }
];

module.exports = ModelSeed;
