// Generated by scripts/derive-seeds.mjs from seed/station.json — do not hand-edit.
const ModelSeed = [
  {
    "chargeId": "CHG-90301",
    "dockingRef": "DCK-004021",
    "accountId": "ACC-7001",
    "chargeType": "DOCKING_FEE",
    "amountCents": 480000,
    "currency": "CR",
    "status": "PENDING"
  },
  {
    "chargeId": "CHG-90302",
    "dockingRef": "DCK-004021",
    "accountId": "ACC-7001",
    "chargeType": "MASS_TARIFF",
    "amountCents": 220000,
    "currency": "CR",
    "status": "PENDING"
  },
  {
    "chargeId": "CHG-90303",
    "dockingRef": "DCK-004021",
    "accountId": "ACC-7001",
    "chargeType": "HAZMAT_SURCHARGE",
    "amountCents": 150000,
    "currency": "CR",
    "status": "DISPUTED"
  },
  {
    "chargeId": "CHG-90304",
    "dockingRef": "DCK-004022",
    "accountId": "ACC-7002",
    "chargeType": "DOCKING_FEE",
    "amountCents": 520000,
    "currency": "CR",
    "status": "PENDING"
  },
  {
    "chargeId": "CHG-90305",
    "dockingRef": "DCK-004022",
    "accountId": "ACC-7002",
    "chargeType": "MASS_TARIFF",
    "amountCents": 610000,
    "currency": "CR",
    "status": "PENDING"
  },
  {
    "chargeId": "CHG-90306",
    "dockingRef": "DCK-004025",
    "accountId": "ACC-7003",
    "chargeType": "DOCKING_FEE",
    "amountCents": 310000,
    "currency": "CR",
    "status": "PAID"
  },
  {
    "chargeId": "CHG-90307",
    "dockingRef": "DCK-004027",
    "accountId": "ACC-7002",
    "chargeType": "DOCKING_FEE",
    "amountCents": 495000,
    "currency": "CR",
    "status": "PENDING"
  },
  {
    "chargeId": "CHG-90308",
    "dockingRef": "DCK-004027",
    "accountId": "ACC-7002",
    "chargeType": "HAZMAT_SURCHARGE",
    "amountCents": 90000,
    "currency": "CR",
    "status": "PENDING"
  },
  {
    "chargeId": "CHG-90309",
    "dockingRef": "DCK-004019",
    "accountId": "ACC-7002",
    "chargeType": "DOCKING_FEE",
    "amountCents": 505000,
    "currency": "CR",
    "status": "PAID"
  },
  {
    "chargeId": "CHG-90310",
    "dockingRef": "DCK-004019",
    "accountId": "ACC-7002",
    "chargeType": "LATE_DEPARTURE",
    "amountCents": 75000,
    "currency": "CR",
    "status": "PAID"
  },
  {
    "chargeId": "CHG-90311",
    "dockingRef": "DCK-004020",
    "accountId": "ACC-7004",
    "chargeType": "DOCKING_FEE",
    "amountCents": 260000,
    "currency": "CR",
    "status": "PAID"
  },
  {
    "chargeId": "CHG-90312",
    "dockingRef": "DCK-004023",
    "accountId": "ACC-7004",
    "chargeType": "DOCKING_FEE",
    "amountCents": 240000,
    "currency": "CR",
    "status": "PAID"
  }
];

module.exports = ModelSeed;
