// Generated by scripts/derive-seeds.mjs from seed/station.json — do not hand-edit.
const ModelSeed = [
  {
    "payrollId": "PAY-80412",
    "crewRef": "CRW-0042",
    "periodEnd": "2026-07-15",
    "grossCents": 720000,
    "status": "PAID"
  },
  {
    "payrollId": "PAY-80413",
    "crewRef": "CRW-0043",
    "periodEnd": "2026-07-15",
    "grossCents": 700000,
    "status": "PAID"
  },
  {
    "payrollId": "PAY-80414",
    "crewRef": "CRW-0044",
    "periodEnd": "2026-07-15",
    "grossCents": 690000,
    "status": "PAID"
  },
  {
    "payrollId": "PAY-80415",
    "crewRef": "CRW-0045",
    "periodEnd": "2026-07-15",
    "grossCents": 720000,
    "status": "HELD"
  },
  {
    "payrollId": "PAY-80416",
    "crewRef": "CRW-0046",
    "periodEnd": "2026-07-15",
    "grossCents": 540000,
    "status": "PAID"
  },
  {
    "payrollId": "PAY-80417",
    "crewRef": "CRW-0047",
    "periodEnd": "2026-07-15",
    "grossCents": 610000,
    "status": "SCHEDULED"
  },
  {
    "payrollId": "PAY-80418",
    "crewRef": "CRW-0048",
    "periodEnd": "2026-07-15",
    "grossCents": 695000,
    "status": "PAID"
  },
  {
    "payrollId": "PAY-80419",
    "crewRef": "CRW-0049",
    "periodEnd": "2026-07-15",
    "grossCents": 705000,
    "status": "PAID"
  }
];

module.exports = ModelSeed;
