// Generated by scripts/derive-seeds.mjs from seed/station.json — do not hand-edit.
const ModelSeed = [
  {
    "valuationId": "VAL-33101",
    "manifestLineRef": "DCK-004021/1",
    "declaredValueCents": 9600000,
    "currency": "CR",
    "insuranceClass": "SPECIALIZED"
  },
  {
    "valuationId": "VAL-33102",
    "manifestLineRef": "DCK-004021/2",
    "declaredValueCents": 2400000,
    "currency": "CR",
    "insuranceClass": "STANDARD"
  },
  {
    "valuationId": "VAL-33103",
    "manifestLineRef": "DCK-004021/3",
    "declaredValueCents": 18750000,
    "currency": "CR",
    "insuranceClass": "SPECIALIZED"
  },
  {
    "valuationId": "VAL-33104",
    "manifestLineRef": "DCK-004022/1",
    "declaredValueCents": 5100000,
    "currency": "CR",
    "insuranceClass": "STANDARD"
  },
  {
    "valuationId": "VAL-33105",
    "manifestLineRef": "DCK-004022/2",
    "declaredValueCents": 890000,
    "currency": "CR",
    "insuranceClass": "SPECIALIZED"
  },
  {
    "valuationId": "VAL-33106",
    "manifestLineRef": "DCK-004027/1",
    "declaredValueCents": 1300000,
    "currency": "CR",
    "insuranceClass": "STANDARD"
  },
  {
    "valuationId": "VAL-33108",
    "manifestLineRef": "DCK-004019/1",
    "declaredValueCents": 210000,
    "currency": "CR",
    "insuranceClass": "STANDARD"
  }
];

module.exports = ModelSeed;
