import path from "path";
import fs from "fs/promises";

interface Requirement {
  id: string;
  type: "functional" | "non-functional" | "technical" | "architectural";
  category: string;
  title: string;
  description: string;
  rationale: string;
  acceptanceCriteria: string[];
  relatedRequirements: string[];
  priority: "critical" | "high" | "medium" | "low";
  status: "draft" | "proposed" | "approved" | "implemented";
}

interface ProjectContext {
  existingRequirements: string[];
  mfeTypes: string[];
  capabilities: string[];
  platformHandlers: string[];
}

export class RequirementDocGenerator {
  private docsPath: string;
  private requirementsPath: string;
  private acceptanceCriteriaPath: string;

  constructor(docsPath: string) {
    this.docsPath = docsPath;
    this.requirementsPath = path.join(docsPath, "requirements");
    this.acceptanceCriteriaPath = path.join(docsPath, "acceptance-criteria");
  }

  /**
   * Generate requirement documents in the project's standard format
   */
  async generateRequirementDocs(
    requirements: Requirement[],
    context: ProjectContext
  ): Promise<void> {
    await this.ensureDirectoriesExist();

    for (const requirement of requirements) {
      await this.generateRequirementFile(requirement);
      await this.generateAcceptanceCriteriaFile(requirement);
    }

    await this.generateRequirementsSummary(requirements);
  }

  /**
   * Ensure output directories exist
   */
  private async ensureDirectoriesExist(): Promise<void> {
    await fs.mkdir(this.requirementsPath, { recursive: true });
    await fs.mkdir(this.acceptanceCriteriaPath, { recursive: true });
  }

  /**
   * Generate individual requirement document
   */
  private async generateRequirementFile(requirement: Requirement): Promise<void> {
    const filename = `${requirement.id.toLowerCase()}.md`;
    const filepath = path.join(this.requirementsPath, filename);

    const content = this.formatRequirementDocument(requirement);

    await fs.writeFile(filepath, content, "utf-8");
    console.log(`📄 Generated: ${filename}`);
  }

  /**
   * Format requirement as markdown document
   */
  private formatRequirementDocument(req: Requirement): string {
    const priorityEmoji = {
      critical: "🔴",
      high: "🟠",
      medium: "🟡",
      low: "🟢"
    };

    const statusBadge = {
      draft: "⚪ DRAFT",
      proposed: "🔵 PROPOSED",
      approved: "🟢 APPROVED",
      implemented: "✅ IMPLEMENTED"
    };

    return `# ${req.id}: ${req.title}

## Metadata

| Property | Value |
|----------|-------|
| **ID** | ${req.id} |
| **Type** | ${req.type} |
| **Category** | ${req.category.toUpperCase()} |
| **Priority** | ${priorityEmoji[req.priority]} ${req.priority.toUpperCase()} |
| **Status** | ${statusBadge[req.status]} |
| **Created** | ${new Date().toISOString().split('T')[0]} |

## Description

${req.description}

## Rationale

${req.rationale}

## Acceptance Criteria

${this.formatAcceptanceCriteria(req.acceptanceCriteria)}

## Related Requirements

${this.formatRelatedRequirements(req.relatedRequirements)}

## Implementation Notes

*To be filled in during implementation phase*

## Test Coverage

*To be filled in during testing phase*

- [ ] Unit tests
- [ ] Integration tests
- [ ] E2E tests
- [ ] Documentation updated

## Change Log

| Date | Author | Change |
|------|--------|--------|
| ${new Date().toISOString().split('T')[0]} | Requirements Agent | Initial creation |

---

*Generated by MFE Platform Requirements Elicitation Agent*
`;
  }

  /**
   * Format acceptance criteria section
   */
  private formatAcceptanceCriteria(criteria: string[]): string {
    if (criteria.length === 0) {
      return "*No acceptance criteria defined yet*";
    }

    return criteria.map((criterion, index) => {
      // Check if it's in GWT format
      if (criterion.includes("GIVEN") && criterion.includes("WHEN") && criterion.includes("THEN")) {
        return `### AC${index + 1}\n\n\`\`\`gherkin\n${criterion}\n\`\`\`\n`;
      } else {
        return `${index + 1}. ${criterion}`;
      }
    }).join("\n\n");
  }

  /**
   * Format related requirements section
   */
  private formatRelatedRequirements(related: string[]): string {
    if (related.length === 0) {
      return "*No related requirements*";
    }

    return related.map(reqId => {
      const filename = `${reqId.toLowerCase()}.md`;
      return `- [${reqId}](./${filename})`;
    }).join("\n");
  }

  /**
   * Generate acceptance criteria file (GWT format)
   */
  private async generateAcceptanceCriteriaFile(requirement: Requirement): Promise<void> {
    const filename = `${requirement.id.toLowerCase()}.feature`;
    const filepath = path.join(this.acceptanceCriteriaPath, filename);

    const content = this.formatFeatureFile(requirement);

    await fs.writeFile(filepath, content, "utf-8");
    console.log(`🥒 Generated: ${filename}`);
  }

  /**
   * Format as Gherkin feature file
   */
  private formatFeatureFile(req: Requirement): string {
    return `Feature: ${req.title}
  ${req.id}

  Background:
    Given the MFE platform is running
    And all required dependencies are available

${this.formatGherkinScenarios(req.acceptanceCriteria, req.id)}

  @${req.category}
  @priority-${req.priority}
  @status-${req.status}
`;
  }

  /**
   * Format acceptance criteria as Gherkin scenarios
   */
  private formatGherkinScenarios(criteria: string[], reqId: string): string {
    if (criteria.length === 0) {
      return `  Scenario: Basic validation
    Given this requirement is implemented
    When the system is tested
    Then it should meet the requirement definition`;
    }

    return criteria.map((criterion, index) => {
      if (criterion.includes("GIVEN") && criterion.includes("WHEN") && criterion.includes("THEN")) {
        // Already in GWT format - parse and format properly
        const lines = criterion.split("\n").map(l => l.trim());
        return `  Scenario: ${reqId} - AC${index + 1}
    ${lines.join("\n    ")}`;
      } else {
        // Convert free-form criterion to basic scenario
        return `  Scenario: ${reqId} - AC${index + 1}
    Given the preconditions are met
    When ${criterion}
    Then the system behaves as expected`;
      }
    }).join("\n\n");
  }

  /**
   * Generate summary document of all requirements
   */
  private async generateRequirementsSummary(requirements: Requirement[]): Promise<void> {
    const filepath = path.join(this.requirementsPath, "REQUIREMENTS-SUMMARY.md");

    const byCategory = this.groupByCategory(requirements);
    const byPriority = this.groupByPriority(requirements);
    const byStatus = this.groupByStatus(requirements);

    const content = `# Requirements Summary

**Generated:** ${new Date().toISOString()}
**Total Requirements:** ${requirements.length}

## Quick Stats

| Metric | Count |
|--------|-------|
| Total Requirements | ${requirements.length} |
| Critical Priority | ${byPriority.critical?.length || 0} |
| High Priority | ${byPriority.high?.length || 0} |
| Medium Priority | ${byPriority.medium?.length || 0} |
| Low Priority | ${byPriority.low?.length || 0} |
| Draft Status | ${byStatus.draft?.length || 0} |
| Proposed Status | ${byStatus.proposed?.length || 0} |
| Approved Status | ${byStatus.approved?.length || 0} |
| Implemented Status | ${byStatus.implemented?.length || 0} |

## Requirements by Category

${this.formatCategorySection(byCategory)}

## Requirements by Priority

${this.formatPrioritySection(byPriority)}

## Requirements by Status

${this.formatStatusSection(byStatus)}

## Full Requirements List

${this.formatFullList(requirements)}

---

*Generated by MFE Platform Requirements Elicitation Agent*
`;

    await fs.writeFile(filepath, content, "utf-8");
    console.log(`📊 Generated: REQUIREMENTS-SUMMARY.md`);
  }

  /**
   * Group requirements by category
   */
  private groupByCategory(requirements: Requirement[]): Record<string, Requirement[]> {
    return requirements.reduce((acc, req) => {
      const cat = req.category;
      if (!acc[cat]) acc[cat] = [];
      acc[cat].push(req);
      return acc;
    }, {} as Record<string, Requirement[]>);
  }

  /**
   * Group requirements by priority
   */
  private groupByPriority(requirements: Requirement[]): Record<string, Requirement[]> {
    return requirements.reduce((acc, req) => {
      const pri = req.priority;
      if (!acc[pri]) acc[pri] = [];
      acc[pri].push(req);
      return acc;
    }, {} as Record<string, Requirement[]>);
  }

  /**
   * Group requirements by status
   */
  private groupByStatus(requirements: Requirement[]): Record<string, Requirement[]> {
    return requirements.reduce((acc, req) => {
      const status = req.status;
      if (!acc[status]) acc[status] = [];
      acc[status].push(req);
      return acc;
    }, {} as Record<string, Requirement[]>);
  }

  /**
   * Format category section
   */
  private formatCategorySection(grouped: Record<string, Requirement[]>): string {
    return Object.entries(grouped)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([category, reqs]) => {
        const list = reqs.map(r => `  - [${r.id}](./${r.id.toLowerCase()}.md): ${r.title}`).join("\n");
        return `### ${category.toUpperCase()} (${reqs.length})\n\n${list}`;
      })
      .join("\n\n");
  }

  /**
   * Format priority section
   */
  private formatPrioritySection(grouped: Record<string, Requirement[]>): string {
    const order = ["critical", "high", "medium", "low"] as const;
    const emoji: Record<typeof order[number], string> = { critical: "🔴", high: "🟠", medium: "🟡", low: "🟢" };

    return order
      .filter(pri => grouped[pri] && grouped[pri].length > 0)
      .map(pri => {
        const reqs = grouped[pri];
        const list = reqs.map(r => `  - [${r.id}](./${r.id.toLowerCase()}.md): ${r.title}`).join("\n");
        return `### ${emoji[pri]} ${pri.toUpperCase()} (${reqs.length})\n\n${list}`;
      })
      .join("\n\n");
  }

  /**
   * Format status section
   */
  private formatStatusSection(grouped: Record<string, Requirement[]>): string {
    const order = ["draft", "proposed", "approved", "implemented"] as const;
    const emoji: Record<typeof order[number], string> = { draft: "⚪", proposed: "🔵", approved: "🟢", implemented: "✅" };

    return order
      .filter(status => grouped[status] && grouped[status].length > 0)
      .map(status => {
        const reqs = grouped[status];
        const list = reqs.map(r => `  - [${r.id}](./${r.id.toLowerCase()}.md): ${r.title}`).join("\n");
        return `### ${emoji[status]} ${status.toUpperCase()} (${reqs.length})\n\n${list}`;
      })
      .join("\n\n");
  }

  /**
   * Format full list of requirements
   */
  private formatFullList(requirements: Requirement[]): string {
    return requirements
      .sort((a, b) => a.id.localeCompare(b.id))
      .map(req => {
        const priEmoji = { critical: "🔴", high: "🟠", medium: "🟡", low: "🟢" };
        const statusEmoji = { draft: "⚪", proposed: "🔵", approved: "🟢", implemented: "✅" };

        return `- ${priEmoji[req.priority]} ${statusEmoji[req.status]} [${req.id}](./${req.id.toLowerCase()}.md): ${req.title}`;
      })
      .join("\n");
  }
}
