/**
 * The generator's behaviour freeze.
 *
 * `captureSnapshot()` regenerates every manifest in every reference fleet in
 * memory and hashes the result. This test compares that against the committed
 * fixture, so any change to the generator that moves a generated byte fails
 * here rather than being discovered in a fleet rebuild.
 *
 * WHY THIS EXISTS AS A TEST AND NOT JUST A SCRIPT: the harness
 * (`scripts/codegen-characterization.ts`) has been in the repo since #238 and
 * was wired to nothing — it ran only when someone remembered the two-command
 * recipe in its docstring, which across the whole ADR-061 packages migration
 * appears to be never. A safety net nobody pulls is not a safety net.
 *
 * It complements, and does not duplicate, the two existing gates:
 *   - `check:mfe-drift`      compares generated bytes to what is ON DISK,
 *                            for generator-owned files only.
 *   - `check:mfe-consistency` compares manifest ⇄ package.json ⇄ federation.
 *   - this test              compares generated bytes to a FROZEN BASELINE,
 *                            for every file the generator emits, developer-owned
 *                            included — which is the half regeneration never
 *                            rewrites and therefore the half drift cannot see.
 *
 * When a change to the generator is *meant* to change output, regenerate the
 * fixture with `npm run build:codegen-snapshot` and review the diff as part of
 * the change. A diff here is never noise; it is the blast radius.
 */

import * as fs from 'fs';
import {
  captureSnapshot,
  FIXTURE_PATH,
  FLEETS,
  type SnapshotEntry,
} from '../codegen-characterization';

describe('codegen characterization', () => {
  let snapshot: SnapshotEntry[];

  beforeAll(async () => {
    snapshot = await captureSnapshot();
  }, 300_000);

  it('covers every reference fleet', () => {
    const fleets = new Set(snapshot.map((e) => e.manifestDir.split('/')[0]));
    expect([...fleets].sort()).toEqual([...FLEETS].sort());
  });

  it('covers every manifest in the repository', () => {
    // 21 MFEs across the two fleets. A manifest silently dropping out of the
    // walk would otherwise weaken the freeze without failing anything.
    expect(snapshot).toHaveLength(21);
  });

  it('parses and generates every manifest without error', () => {
    const failed = snapshot.filter((e) => e.error);
    expect(failed.map((e) => `${e.manifestDir}: ${e.error}`)).toEqual([]);
  });

  it('exercises both framework lanes in both fleets', () => {
    // The generator's six remaining framework branches all key on the Angular
    // variant, so a baseline with no Angular MFE in a fleet freezes only half
    // the code. abc-kids has one; meridian-station has three.
    for (const fleet of FLEETS) {
      const frameworks = new Set(
        snapshot.filter((e) => e.manifestDir.startsWith(`${fleet}/`)).map((e) => e.framework),
      );
      expect([...frameworks].sort()).toEqual(['angular', 'react']);
    }
  });

  it('matches the committed baseline byte for byte', () => {
    if (!fs.existsSync(FIXTURE_PATH)) {
      throw new Error(
        `No baseline at ${FIXTURE_PATH}. Create it with \`npm run build:codegen-snapshot\`.`,
      );
    }
    const committed = JSON.parse(fs.readFileSync(FIXTURE_PATH, 'utf8')) as SnapshotEntry[];

    // Compare per-MFE rather than whole-array: a single changed template
    // otherwise prints a diff of every file in every MFE, and the useful
    // signal (which files moved) is lost in it.
    expect(snapshot.map((e) => e.manifestDir)).toEqual(committed.map((e) => e.manifestDir));
    for (const [i, entry] of snapshot.entries()) {
      expect({ [entry.manifestDir]: entry }).toEqual({ [entry.manifestDir]: committed[i] });
    }
  });
});
