// Generated by seans-mfe-tool. Do not edit — regenerated on every `remote:generate`.
//
// Contract smoke test. Mirrors the generator-owned `mfe.test.ts` in the web
// lane: it asserts the lifecycle machine this module inherits behaves the way
// the platform contract says, not that any capability does useful work.

import XCTest
@testable import MeridianCrewServices

private struct StubProvider: MeridianCrewServicesDataProvider {
    func crewRoster() async throws -> CrewRosterOutputs { CrewRosterOutputs() }
    func payStatus() async throws -> PayStatusOutputs { PayStatusOutputs() }
}

final class LifecycleTests: XCTestCase {

    func testStartsUninitialized() {
        let mfe = MeridianCrewServicesMFE(provider: StubProvider())
        XCTAssertEqual(mfe.state, .uninitialized)
    }

    func testLoadMovesToReady() async throws {
        let mfe = MeridianCrewServicesMFE(provider: StubProvider())
        _ = try await mfe.load(MFEContext())
        XCTAssertEqual(mfe.state, .ready)
    }

    func testRenderRequiresReady() async {
        let mfe = MeridianCrewServicesMFE(provider: StubProvider())
        // render's preStates is [ready]; from uninitialized this must throw
        // rather than transition.
        do {
            _ = try await mfe.render(MFEContext(capabilityId: "CrewRoster"))
            XCTFail("render should be rejected from uninitialized")
        } catch {
            XCTAssertEqual(mfe.state, .uninitialized)
        }
    }

    func testDescribeReportsManifestCapabilities() async throws {
        let mfe = MeridianCrewServicesMFE(provider: StubProvider())
        let described = try await mfe.describe(MFEContext())
        XCTAssertEqual(described.name, ManifestMetadata.name)
    }

    func testTransitionTableMatchesContract() {
        // The six states and their edges come from the platform contract.
        XCTAssertEqual(MFELifecycleState.allCases.count, 6)
        XCTAssertTrue(MFELifecycleTransitions.isValid(from: .uninitialized, to: .loading))
        XCTAssertFalse(MFELifecycleTransitions.isValid(from: .destroyed, to: .loading))
    }
}
