// Generated by seans-mfe-tool. Do not edit — regenerated on every `remote:generate`.
//
// Contract smoke test. Mirrors the generator-owned `mfe.test.ts` in the web
// lane: it asserts the lifecycle machine this module inherits behaves the way
// the platform contract says, not that any capability does useful work.
//
// Swift Testing (`import Testing`, `@Test`, `#expect`), not XCTest. Runs under
// `swift test` on a Swift 6 toolchain and in Xcode 16+. In Xcode the package's
// test target is not part of the host app's scheme until you add it — see the
// package README.

import Testing
import Foundation
#if canImport(FoundationNetworking)
// URL is Foundation; HTTPURLResponse is FoundationNetworking on Linux, which is
// where the `swift` CI job runs.
import FoundationNetworking
#endif
@testable import MeridianCrewServices

private struct StubProvider: MeridianCrewServicesDataProvider {
    func crewRoster() async throws -> CrewRosterOutputs { CrewRosterOutputs() }
    func payStatus() async throws -> PayStatusOutputs { PayStatusOutputs() }
}

/// Captures what the stub transport was handed.
private actor SeenRequest {
    private(set) var headers: [String: String] = [:]
    func record(_ h: [String: String]) { headers = h }
}

/// Collects handler names across concurrent hook invocations.
private actor FiredHooks {
    private(set) var names: [String] = []
    func record(_ name: String) { names.append(name) }
}

@Suite struct LifecycleTests {

    @Test func startsUninitialized() {
        let mfe = MeridianCrewServicesMFE(provider: StubProvider())
        #expect(mfe.state == .uninitialized)
    }

    @Test func loadMovesToReady() async throws {
        let mfe = MeridianCrewServicesMFE(provider: StubProvider())
        _ = try await mfe.load(MFEContext())
        #expect(mfe.state == .ready)
    }

    @Test func renderRequiresReady() async {
        let mfe = MeridianCrewServicesMFE(provider: StubProvider())
        // render's preStates is [ready]; from uninitialized this must throw
        // rather than transition.
        await #expect(throws: (any Error).self, "render should be rejected from uninitialized") {
            _ = try await mfe.render(MFEContext(capabilityId: "CrewRoster"))
        }
        #expect(mfe.state == .uninitialized)
    }

    @Test func mountRejectsUnknownCapability() {
        let mfe = MeridianCrewServicesMFE(provider: StubProvider())
        // Not a state-machine violation: the state is fine, the id is not.
        #expect(throws: MFEUnknownCapabilityError.self) {
            try mfe.mount("NotACapability")
        }
    }

    @Test func describeReportsManifestCapabilities() async throws {
        let mfe = MeridianCrewServicesMFE(provider: StubProvider())
        let described = try await mfe.describe(MFEContext())
        #expect(described.name == ManifestMetadata.name)
    }

    /// The manifest's hooks actually FIRE.
    ///
    /// This exists because they did not. `MFECapability.load.rawValue` is
    /// "load" and the manifest writes "Load", and the lookup compared the two
    /// exactly — so every hook this manifest declares was inert while 136 text
    /// assertions and a clean `swift build` both passed. A text assertion can
    /// see that the engine was rendered; only running it can see that it runs.
    @Test func manifestHooksFire() async throws {
        let fired = FiredHooks()
        var handlers: [String: MFEHandler] = [:]
        handlers["onLoadBegin"] = { _ in await fired.record("onLoadBegin") }
        handlers["onLoadComplete"] = { _ in await fired.record("onLoadComplete") }
        handlers["onLoadError"] = { _ in await fired.record("onLoadError") }
        handlers["onRenderBegin"] = { _ in await fired.record("onRenderBegin") }
        handlers["onRenderComplete"] = { _ in await fired.record("onRenderComplete") }
        handlers["onRenderError"] = { _ in await fired.record("onRenderError") }

        let mfe = MeridianCrewServicesMFE(
            provider: StubProvider(),
            deps: MFEDependencies(customHandlers: handlers)
        )
        _ = try await mfe.load(MFEContext())

        // Whatever `load`'s before/after hooks are, they ran.
        let ran = await fired.names
        #expect(!ran.isEmpty, "no manifest hook fired during load()")
        #expect(ran.contains("onLoadBegin"), "before hook onLoadBegin did not fire")
        #expect(ran.contains("onLoadComplete"), "after hook onLoadComplete did not fire")
    }

    /// A host's handler wins over the generated stub for the same name.
    @Test func hostHandlerOverridesGeneratedStub() async throws {
        let fired = FiredHooks()
        let name = "onLoadBegin"
        let mfe = MeridianCrewServicesMFE(
            provider: StubProvider(),
            deps: MFEDependencies(customHandlers: [name: { _ in await fired.record(name) }])
        )
        _ = try await mfe.load(MFEContext())
        let ran = await fired.names
        #expect(ran.contains(name), "host handler was shadowed by the generated stub")
    }

    // MARK: - query transport
    //
    // `doQuery` and `BFFClient` share one HTTP path (`GraphQLPost.send`) and
    // keep DIFFERENT error policies on purpose. Nothing else can observe that:
    // `check:mfe-drift` compares generated bytes to the template, so both files
    // stay "correct" while free to diverge. These run the real code over a stub
    // transport, so the split is asserted rather than incidental.

    /// A partial GraphQL response — `data` AND `errors`, a normal outcome.
    private static let partialResponse = Data(#"{"data":{"x":1},"errors":[{"message":"boom"}]}"#.utf8)

    private static func stub(_ body: Data, status: Int = 200) -> MFETransport {
        { request in
            let response = HTTPURLResponse(
                url: request.url!, statusCode: status, httpVersion: nil, headerFields: nil
            )!
            return (body, response)
        }
    }

    @Test func queryReturnsPartialDataAndErrorsTogether() async throws {
        let mfe = MeridianCrewServicesMFE(
            provider: StubProvider(),
            deps: MFEDependencies(transport: Self.stub(Self.partialResponse))
        )
        _ = try await mfe.load(MFEContext())
        let result = try await mfe.query(MFEContext(inputs: [
            "document": .string("query { x }"),
            "bffUrl": .string("http://stub.invalid/graphql"),
        ]))
        // The envelope policy: the capability answers with both halves.
        #expect(result.data != nil)
        #expect(result.errors == ["boom"])
    }

    @Test func queryReturnsErrorsRatherThanThrowingOnHTTPFailure() async throws {
        let mfe = MeridianCrewServicesMFE(
            provider: StubProvider(),
            deps: MFEDependencies(transport: Self.stub(Data("nope".utf8), status: 503))
        )
        _ = try await mfe.load(MFEContext())
        let result = try await mfe.query(MFEContext(inputs: [
            "document": .string("query { x }"),
            "bffUrl": .string("http://stub.invalid/graphql"),
        ]))
        #expect(result.data == nil)
        #expect(result.errors.count == 1)
    }

    @Test func queryForwardsTheBearerTokenAndHeaders() async throws {
        let seen = SeenRequest()
        let transport: MFETransport = { request in
            await seen.record(request.allHTTPHeaderFields ?? [:])
            let response = HTTPURLResponse(
                url: request.url!, statusCode: 200, httpVersion: nil, headerFields: nil
            )!
            return (Data(#"{"data":{}}"#.utf8), response)
        }
        let mfe = MeridianCrewServicesMFE(
            provider: StubProvider(),
            deps: MFEDependencies(transport: transport)
        )
        _ = try await mfe.load(MFEContext())
        _ = try await mfe.query(MFEContext(
            inputs: ["document": .string("query { x }"), "bffUrl": .string("http://stub.invalid/graphql")],
            jwt: "tok",
            headers: ["X-Request-Id": "abc"]
        ))
        let headers = await seen.headers
        #expect(headers["Authorization"] == "Bearer tok")
        #expect(headers["X-Request-Id"] == "abc")
        #expect(headers["Content-Type"] == "application/json")
    }

    @Test func bffClientThrowsOnTheSamePartialResponse() async throws {
        // Same bytes, opposite policy: a caller decoding into a type must not
        // silently receive half a response. TypeScript splits them the same way
        // (`base-mfe.ts` returns the envelope, `bff.ts` throws).
        let client = BFFClient(
            endpoint: URL(string: "http://stub.invalid/graphql")!,
            transport: Self.stub(Self.partialResponse)
        )
        var thrown: (any Error)?
        do {
            let _: CrewRosterOutputs = try await client.query("query { x }")
        } catch {
            thrown = error
        }
        #expect(thrown is BFFError)
    }

    @Test func transitionTableMatchesContract() {
        // The six states and their edges come from the platform contract.
        #expect(MFELifecycleState.allCases.count == 6)
        #expect(MFELifecycleTransitions.isValid(from: .uninitialized, to: .loading))
        #expect(!MFELifecycleTransitions.isValid(from: .destroyed, to: .loading))
    }
}
