/**
 * mesh-context.js — Generated by seans-mfe-tool
 *
 * Envelop plugin loaded by Mesh via `additionalEnvelopPlugins` in .meshrc.yaml.
 * Injects request-derived context fields into every GraphQL execution context:
 *
 *   jwt        — Bearer token from Authorization header
 *   requestId  — x-request-id header or a generated UUID
 *   userId     — decoded `sub` / `userId` from the JWT payload
 *   headers    — plain object of all request headers
 *                (supports context.headers['x-bff-mode'] for mock-switch)
 *
 * ADR-027: context injection via Envelop plugin, not HTTP handler config arg.
 * graphql-yoga (used by @graphql-mesh/http) always exposes the WHATWG Request
 * as `context.request` (YogaInitialContext), making this approach stable across
 * Mesh v0.100.x patch releases.
 */
'use strict';

const crypto = require('crypto');

function extractUserIdFromToken(authHeader) {
  if (!authHeader) return undefined;
  try {
    const token = authHeader.replace('Bearer ', '');
    const payload = JSON.parse(Buffer.from(token.split('.')[1], 'base64').toString());
    return payload.sub || payload.userId;
  } catch {
    return undefined;
  }
}

module.exports = [
  {
    onContextBuilding({ context, extendContext }) {
      // graphql-yoga always places the WHATWG Request on context.request.
      const req = context.request;
      if (!req) return;

      // Normalise WHATWG Headers → plain object for bracket-access compatibility.
      // mock-switch (ADR-052) reads context.headers['x-bff-mode'].
      const headers = {};
      if (typeof req.headers?.forEach === 'function') {
        req.headers.forEach((value, key) => { headers[key] = value; });
      } else if (req.headers && typeof req.headers === 'object') {
        Object.assign(headers, req.headers);
      }

      const authHeader = headers['authorization'] || headers['Authorization'];

      extendContext({
        jwt: authHeader ? authHeader.replace('Bearer ', '') : undefined,
        requestId: headers['x-request-id'] || crypto.randomUUID(),
        userId: extractUserIdFromToken(authHeader),
        headers,
      });
    },
  },
];
