/**
 * abc-kids-flappy BFF client connector
 * @generated By seans-mfe-tool (ADR-012)
 *
 * Client-side module used by MFE frontend code to query the BFF GraphQL endpoint.
 *
 * Usage:
 *   import { query, mutate } from './bff';
 *   const data = await query<GetUserQuery>(GET_USER, { id });
 */

const BFF_ENDPOINT =
  (typeof process !== 'undefined' && (process.env['BFF_URL'] || process.env['VITE_BFF_URL'])) ||
  'http://localhost:3001/graphql';

export interface BffError {
  message: string;
  locations?: Array<{ line: number; column: number }>;
  path?: string[];
}

export interface BffResponse<T> {
  data?: T;
  errors?: BffError[];
}

export async function query<T>(
  document: string,
  variables?: Record<string, unknown>,
  headers?: Record<string, string>,
): Promise<T> {
  const response = await fetch(BFF_ENDPOINT, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...headers },
    body: JSON.stringify({ query: document, variables }),
  });

  if (!response.ok) {
    throw new Error(`BFF request failed: ${response.status} ${response.statusText}`);
  }

  const json: BffResponse<T> = await response.json() as BffResponse<T>;

  if (json.errors?.length) {
    throw new Error(json.errors.map((e) => e.message).join('\n'));
  }

  return json.data as T;
}

export async function mutate<T>(
  document: string,
  variables?: Record<string, unknown>,
  headers?: Record<string, string>,
): Promise<T> {
  return query<T>(document, variables, headers);
}
