#!/usr/bin/env ts-node
/**
 * Codegen characterization harness — the generator's behaviour freeze (#238 D3).
 *
 * Regenerates every manifest in every reference fleet via `generateAllFiles`
 * (in memory — no disk writes) and produces a stable, sorted
 * `{ manifestDir, files: [{ path, overwrite, sha256 }] }` snapshot.
 *
 * WHAT THIS FREEZES THAT THE OTHER GATES DO NOT: `check:mfe-drift` compares
 * generated bytes against what is on disk, and only for generator-owned files.
 * This compares every file the generator emits — developer-owned included —
 * against a committed baseline. That is the half regeneration never rewrites
 * and therefore the half drift structurally cannot see, which is exactly the
 * half a refactor is most likely to disturb without anyone noticing.
 *
 * Usage:
 *   npm run build:codegen-snapshot         # regenerate the committed baseline
 *   npm run build:codegen-snapshot:check   # verify against it (CI)
 *   npx ts-node scripts/codegen-characterization.ts <outFile>   # ad-hoc capture
 *
 * The baseline is also asserted by `scripts/__tests__/codegen-characterization.test.ts`,
 * so it runs under `npm test` rather than only when someone remembers to.
 *
 * Refs #238 · ADR-043 · ADR-061
 */
import * as path from 'path';
import * as fs from 'fs';
import { createHash } from 'crypto';
import { parseAndValidateDirectory } from '@seans-mfe/dsl';
import { generateAllFiles } from '@seans-mfe/codegen';

// Registers the BFF's file contribution (ADR-091 §6) — without it this gate
// would generate no BFF files and report every real one as orphaned.
import '@seans-mfe/plugin-bff/codegen';

const REPO_ROOT = path.resolve(__dirname, '..');
const EXAMPLES_ROOT = path.join(REPO_ROOT, 'examples');

/**
 * The reference fleets, in snapshot order.
 *
 * Both, not just abc-kids: the generator's remaining framework branches all
 * key on the Angular variant, and three of the platform's four Angular MFEs
 * live in meridian-station. A baseline over abc-kids alone froze 14 of 21 MFEs
 * and exactly one Angular lane.
 */
export const FLEETS = ['abc-kids', 'meridian-station'] as const;

/** Where the committed baseline lives. */
export const FIXTURE_PATH = path.join(REPO_ROOT, 'scripts', '__fixtures__', 'codegen-snapshot.json');

export interface SnapshotFile {
  /** MFE-relative, with the absolute prefix replaced by `<cwd>`. */
  path: string;
  /** `true` = generator-owned (re-stamped every run); `false` = developer-owned. */
  overwrite: boolean;
  sha256: string;
}

export interface SnapshotEntry {
  /** `<fleet>/<mfe>` — fleet-qualified so the two fleets cannot collide. */
  manifestDir: string;
  framework: string;
  bundler: string;
  preservedCapabilities: string[];
  fileCount: number;
  files: SnapshotFile[];
  /** Present only when the manifest could not be parsed or generated. */
  error?: string;
}

/** Every `<fleet>/<mfe>` directory holding an `mfe-manifest.yaml`, sorted. */
function discoverManifestDirs(): Array<{ key: string; cwd: string }> {
  const found: Array<{ key: string; cwd: string }> = [];
  for (const fleet of FLEETS) {
    const fleetRoot = path.join(EXAMPLES_ROOT, fleet);
    if (!fs.existsSync(fleetRoot)) continue;
    const dirs = fs
      .readdirSync(fleetRoot, { withFileTypes: true })
      .filter(
        (d) => d.isDirectory() && fs.existsSync(path.join(fleetRoot, d.name, 'mfe-manifest.yaml')),
      )
      .map((d) => d.name)
      .sort();
    for (const dir of dirs) {
      found.push({ key: `${fleet}/${dir}`, cwd: path.join(fleetRoot, dir) });
    }
  }
  return found;
}

/**
 * Capture the snapshot.
 *
 * The generator writes progress to stdout and stderr (12 `console.*` calls in
 * `@seans-mfe/codegen`), so every consumer has to muzzle it to get clean
 * output. Silenced and restored around the run rather than reassigned
 * globally, so calling this from a test does not blind the test runner.
 * Removing the need for this is Phase 3 of the simplification plan.
 */
export async function captureSnapshot(): Promise<SnapshotEntry[]> {
  const realLog = console.log;
  const realWarn = console.warn;
  const realError = console.error;
  console.log = () => {};
  console.warn = () => {};
  console.error = () => {};

  try {
    const out: SnapshotEntry[] = [];
    for (const { key, cwd } of discoverManifestDirs()) {
      const result = await parseAndValidateDirectory(cwd);
      if (!result.valid || !result.manifest) {
        out.push({
          manifestDir: key,
          framework: 'unknown',
          bundler: 'unknown',
          preservedCapabilities: [],
          fileCount: 0,
          files: [],
          error: 'invalid-manifest',
        });
        continue;
      }

      const manifest = result.manifest;
      const { files, preservedCapabilities } = await generateAllFiles(manifest, cwd, {
        frameworkVariant: undefined,
      });

      const hashed: SnapshotFile[] = files
        .map((f) => ({
          path: f.path.replace(cwd, '<cwd>'),
          overwrite: f.overwrite,
          sha256: createHash('sha256').update(f.content).digest('hex'),
        }))
        .sort((a, b) => a.path.localeCompare(b.path));

      out.push({
        manifestDir: key,
        framework: (manifest as { framework?: string }).framework ?? 'react',
        bundler: (manifest as { bundler?: string }).bundler ?? 'rspack',
        preservedCapabilities: [...preservedCapabilities].sort(),
        fileCount: hashed.length,
        files: hashed,
      });
    }
    return out;
  } finally {
    console.log = realLog;
    console.warn = realWarn;
    console.error = realError;
  }
}

/** Serialize exactly as the committed fixture is stored. */
export function render(snapshot: SnapshotEntry[]): string {
  return JSON.stringify(snapshot, null, 2) + '\n';
}

async function main(): Promise<void> {
  const checkMode = process.argv.includes('--check');
  const positional = process.argv.slice(2).filter((a) => !a.startsWith('--'));
  const outFile = positional[0] ?? FIXTURE_PATH;

  const rendered = render(await captureSnapshot());

  if (checkMode) {
    const existing = fs.existsSync(outFile) ? fs.readFileSync(outFile, 'utf8') : null;
    if (existing !== rendered) {
      process.stderr.write(
        `${path.relative(process.cwd(), outFile)} is stale — the generator's output has ` +
          `changed.\nIf that is intended, run \`npm run build:codegen-snapshot\` and review the ` +
          `diff as part of your change.\n`,
      );
      process.exitCode = 1;
      return;
    }
    process.stdout.write(`${path.relative(process.cwd(), outFile)} is up to date.\n`);
    return;
  }

  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, rendered);
  process.stderr.write(`wrote ${path.relative(process.cwd(), outFile)}\n`);
}

// Only run as a CLI. Importing this module (from the test, or from another
// script) must not generate 21 MFEs as a side effect.
if (require.main === module) {
  main().catch((err: unknown) => {
    process.stderr.write(String(err instanceof Error ? err.stack : err) + '\n');
    process.exit(1);
  });
}
