#!/usr/bin/env ts-node
/**
 * Generates the manifest field reference from the Zod schema (finding B5).
 *
 * Four documents described the manifest language, three of them hand-written
 * and none generated or gated:
 *
 *   docs/DSL/dsl.yaml                644 lines, headed "the complete platform
 *                                    contract that ALL MFEs must conform to",
 *                                    and unaware of providesSlots, framework,
 *                                    bundler and data.mockSwitch.
 *   docs/DSL/dsl-schema-reference.md 855 lines, knew providesSlots but not the
 *                                    other three.
 *   docs/schemas/dsl-manifest.md     current, but hand-maintained.
 *   packages/dsl/src/schema.ts       the one that is actually enforced.
 *
 * The file that claimed the most authority was the most stale: it was stamped
 * v3.2 and the whole slot contract (ADR-066..073) shipped without reaching it.
 *
 * This is the ADR-075 pattern applied to the one page a reader is least able
 * to check: the field table is derived from `schemas/dsl/manifest.schema.json`,
 * which is itself generated from the Zod source of truth, so it cannot drift
 * without failing a gate.
 *
 * Usage:
 *   npm run build:manifest-reference          # write
 *   npm run build:manifest-reference:check    # verify (CI)
 *
 * Refs: docs/generator-extraction-plan.md finding B5 · ADR-065 · ADR-075
 */

import * as fs from 'fs';
import * as path from 'path';

const REPO_ROOT = path.resolve(__dirname, '..');
const SCHEMA = path.join(REPO_ROOT, 'schemas', 'dsl', 'manifest.schema.json');
const OUT = path.join(REPO_ROOT, 'docs', 'schemas', 'manifest-fields.md');
const CHECK = process.argv.includes('--check');

interface JsonSchemaNode {
  type?: string | string[];
  description?: string;
  enum?: unknown[];
  items?: JsonSchemaNode;
  anyOf?: JsonSchemaNode[];
  properties?: Record<string, JsonSchemaNode>;
  required?: string[];
  additionalProperties?: boolean | JsonSchemaNode;
  minLength?: number;
  pattern?: string;
  format?: string;
}

/** A human-readable type for one node, without dumping the whole subtree. */
function describeType(node: JsonSchemaNode): string {
  if (node.enum) return node.enum.map((v) => `\`${String(v)}\``).join(' \\| ');
  if (node.anyOf) {
    const parts = node.anyOf.map(describeType).filter((t) => t !== '`null`');
    return [...new Set(parts)].join(' \\| ');
  }
  const t = Array.isArray(node.type) ? node.type.filter((x) => x !== 'null')[0] : node.type;
  if (t === 'array') return `${describeType(node.items ?? {})}[]`;
  if (t === 'object') {
    const keys = Object.keys(node.properties ?? {});
    if (keys.length === 0) return 'object';
    return `object (${keys.slice(0, 4).join(', ')}${keys.length > 4 ? ', …' : ''})`;
  }
  return t ? `\`${t}\`` : '—';
}

/** Constraints worth stating beside the type. */
function describeConstraints(node: JsonSchemaNode): string {
  const bits: string[] = [];
  if (node.format) bits.push(node.format);
  if (node.pattern) bits.push(`pattern \`${node.pattern}\``);
  if (typeof node.minLength === 'number' && node.minLength > 0) {
    bits.push(`min length ${node.minLength}`);
  }
  return bits.join(', ') || '—';
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\n+/g, ' ').trim();
}

function render(schema: JsonSchemaNode): string {
  const required = new Set(schema.required ?? []);
  const props = Object.entries(schema.properties ?? {});
  const requiredRows = props.filter(([k]) => required.has(k));
  const optionalRows = props.filter(([k]) => !required.has(k));

  const row = ([name, node]: [string, JsonSchemaNode]): string =>
    `| \`${name}\` | ${describeType(node)} | ${describeConstraints(node)} | ${
      escapeCell(node.description ?? '')
    } |`;

  const table = (rows: Array<[string, JsonSchemaNode]>): string =>
    rows.length === 0
      ? '_None._\n'
      : ['| Field | Type | Constraints | Description |', '|---|---|---|---|', ...rows.map(row)].join(
          '\n',
        ) + '\n';

  const nested = props
    .filter(([, node]) => node.properties && Object.keys(node.properties).length > 0)
    .map(([name, node]) => {
      const sub = Object.entries(node.properties ?? {});
      const subRequired = new Set(node.required ?? []);
      return (
        `### \`${name}\`\n\n` +
        (node.description ? `${node.description}\n\n` : '') +
        table(sub.map(([k, v]) => [subRequired.has(k) ? `${k} (required)` : k, v]))
      );
    })
    .join('\n');

  return `<!-- GENERATED by scripts/generate-manifest-reference.ts — do not edit.
     Source of truth: packages/dsl/src/schema.ts (Zod) via schemas/dsl/manifest.schema.json.
     Regenerate with: npm run build:manifest-reference -->

# MFE Manifest — Field Reference

Every field \`mfe-manifest.yaml\` accepts, derived from the Zod schema that
validates it — descriptions included, which live on the Zod fields themselves.

Generated, because the three hand-written documents that described this
language each fell behind it, most severely the one that called itself the
complete platform contract (finding B5 in
\`docs/generator-extraction-plan.md\`).

For *why* the manifest is shaped this way, see \`docs/spec.md\` and the ADRs it
indexes. This page answers only *what is allowed*.

## Required fields

${table(requiredRows)}
## Optional fields

${table(optionalRows)}${nested ? `\n## Nested sections\n\n${nested}` : ''}
---

_${props.length} top-level fields, ${requiredRows.length} required. Generated from
\`schemas/dsl/manifest.schema.json\`._
`;
}

function main(): void {
  if (!fs.existsSync(SCHEMA)) {
    process.stderr.write(
      `${path.relative(REPO_ROOT, SCHEMA)} is absent — run \`npm run build:schema:dsl\` first.\n`,
    );
    process.exitCode = 1;
    return;
  }
  const schema = JSON.parse(fs.readFileSync(SCHEMA, 'utf8')) as JsonSchemaNode;
  const rendered = render(schema);

  if (CHECK) {
    const existing = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null;
    if (existing !== rendered) {
      process.stderr.write(
        `${path.relative(REPO_ROOT, OUT)} is stale — run \`npm run build:manifest-reference\` ` +
          `and commit the result.\n`,
      );
      process.exitCode = 1;
      return;
    }
    process.stdout.write(`${path.relative(REPO_ROOT, OUT)} is up to date.\n`);
    return;
  }

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, rendered);
  process.stdout.write(`wrote ${path.relative(REPO_ROOT, OUT)}\n`);
}

main();
