/**
 * abc-kids-multiplication-quiz BFF client connector
 * @generated By seans-mfe-tool (ADR-012)
 *
 * Client-side module used by MFE frontend code to query the BFF GraphQL endpoint.
 *
 * Usage:
 *   import { query, mutate } from './bff';
 *   const data = await query<GetUserQuery>(GET_USER, { id });
 */

import { BusinessError, httpOutcomeError } from '@seans-mfe-tool/runtime';

const BFF_ENDPOINT =
  (typeof process !== 'undefined' && (process.env['BFF_URL'] || process.env['VITE_BFF_URL'])) ||
  'http://localhost:3003/graphql';

export interface BffError {
  message: string;
  locations?: Array<{ line: number; column: number }>;
  path?: string[];
}

export interface BffResponse<T> {
  data?: T;
  errors?: BffError[];
}

export async function query<T>(
  document: string,
  variables?: Record<string, unknown>,
  headers?: Record<string, string>,
): Promise<T> {
  // A failed request throws the typed error its status maps to (ADR-106): a
  // 503 is a retryable NetworkError, a 404 a non-retryable BusinessError. The
  // query capability classifies the same failure by the same table.
  let response: Response;
  try {
    response = await fetch(BFF_ENDPOINT, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...headers },
      body: JSON.stringify({ query: document, variables }),
    });
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error);
    throw httpOutcomeError(`BFF request failed: ${reason}`, 0);
  }

  if (!response.ok) {
    throw httpOutcomeError(
      `BFF request failed: ${response.status} ${response.statusText}`,
      response.status
    );
  }

  const json: BffResponse<T> = await response.json() as BffResponse<T>;

  if (json.errors?.length) {
    throw new BusinessError(
      json.errors.map((e) => e.message).join('\n'),
      'BFF_GRAPHQL_ERROR'
    );
  }

  return json.data as T;
}

export async function mutate<T>(
  document: string,
  variables?: Record<string, unknown>,
  headers?: Record<string, string>,
): Promise<T> {
  return query<T>(document, variables, headers);
}
