#!/usr/bin/env node
/**
 * Projects seed/station.json (the single source of truth) into each API's
 * NATIVE convention, overwriting the generated *.seed.js data files:
 *
 *   Harbormaster  → snake_case rows, numeric docking ids
 *   StellarLedger → camelCase docs, integer cents, formatted string refs
 *                   (DCK-004021, CRW-0042, ACC-7105)
 *   StationOS     → PascalCase rows, bare integer DockingNo
 *
 * The three projections below ARE the mess the BFF layer exists to clean
 * up — reading this file side by side with the README's "the mess is the
 * point" section shows every renamed key and reformatted id.
 *
 * Run: node scripts/derive-seeds.mjs   (from examples/meridian-station/)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const station = JSON.parse(readFileSync(join(root, 'seed', 'station.json'), 'utf8'));

// The cross-system id formats. Same entity, three dialects.
const dckRef = (id) => `DCK-${String(id).padStart(6, '0')}`;
const crwRef = (id) => `CRW-${String(id).padStart(4, '0')}`;
const lineRef = (docking, line) => `${dckRef(docking)}/${line}`;

const seedFile = (api, model, rows) => {
  const file = join(root, 'apis', api, 'src', 'database', 'seeds', `${model}.seed.js`);
  const banner = `// Generated by scripts/derive-seeds.mjs from seed/station.json — do not hand-edit.\n`;
  writeFileSync(file, `${banner}const ModelSeed = ${JSON.stringify(rows, null, 2)};\n\nmodule.exports = ModelSeed;\n`);
  console.log(`wrote ${api}/src/database/seeds/${model}.seed.js (${rows.length} rows)`);
};

// ── Harbormaster: snake_case, numeric ids, integer 0/1 flags ────────────────
seedFile('harbormaster-api', 'Berth', station.berths.map((b) => ({
  berth_id: b.id,
  berth_class: b.class,
  occupied_flag: b.occupied ? 1 : 0,
  max_mass_kg: b.maxMassKg,
  current_docking_id: b.currentDocking,
})));

seedFile('harbormaster-api', 'Docking', station.dockings.map((d) => ({
  docking_id: d.id,
  berth_id: d.berth,
  vessel_registry_no: d.vessel,
  eta_utc: d.etaUtc,
  departed_utc: d.departedUtc,
  status_code: d.status,
})));

seedFile('harbormaster-api', 'ManifestLine', station.manifestLines.map((m) => ({
  line_id: m.line,
  docking_id: m.docking,
  sku: m.sku,
  description: m.description,
  qty: m.qty,
  declared_mass_kg: m.massKg,
  hazard_class: m.hazard,
})));

seedFile('harbormaster-api', 'Vessel', station.vessels.map((v) => ({
  vessel_registry_no: v.registry,
  vessel_name: v.name,
  operator_name: v.operator,
  max_capacity_kg: v.maxCapacityKg,
})));

// ── StellarLedger: camelCase, cents, formatted string refs ──────────────────
seedFile('stellar-ledger-api', 'Account', station.accounts.map((a) => ({
  accountId: a.id,
  displayName: a.name,
  accountType: a.type,
  standing: a.standing,
  balanceCents: a.balanceCents,
  currency: 'CR',
})));

seedFile('stellar-ledger-api', 'Charge', station.charges.map((c) => ({
  chargeId: c.id,
  dockingRef: dckRef(c.docking),
  accountId: c.account,
  chargeType: c.type,
  amountCents: c.amountCents,
  currency: 'CR',
  status: c.status,
})));

seedFile('stellar-ledger-api', 'Valuation', station.valuations.map((v) => ({
  valuationId: v.id,
  manifestLineRef: lineRef(v.docking, v.line),
  declaredValueCents: v.valueCents,
  currency: 'CR',
  insuranceClass: v.insuranceClass,
})));

seedFile('stellar-ledger-api', 'Settlement', station.settlements.map((s) => ({
  settlementId: s.id,
  merchantId: s.merchantAccount,
  periodStart: s.periodStart,
  periodEnd: s.periodEnd,
  grossCents: s.grossCents,
  feeCents: s.feeCents,
  netCents: s.grossCents - s.feeCents,
  status: s.status,
})));

seedFile('stellar-ledger-api', 'Payroll', station.payroll.map((p) => ({
  payrollId: p.id,
  crewRef: crwRef(p.crew),
  periodEnd: p.periodEnd,
  grossCents: p.grossCents,
  status: p.status,
})));

// ── StationOS: PascalCase, bare integer DockingNo, decimal credits ──────────
seedFile('station-os-api', 'Module', station.modules.map((m) => ({
  ModuleId: m.id,
  ModuleName: m.name,
  DeckZone: m.zone,
  ModuleType: m.type,
})));

seedFile('station-os-api', 'Telemetry', station.telemetry.map((t) => ({
  ReadingId: t.id,
  ModuleId: t.module,
  MetricKind: t.metric,
  MetricValue: t.value,
  RecordedAtUtc: t.atUtc,
  AlertLevel: t.alert,
})));

seedFile('station-os-api', 'Crew', station.crew.map((c) => ({
  CrewId: c.id,
  CrewMemberName: c.name,
  Section: c.section,
  DutyStatus: c.dutyStatus,
  BerthAssignment: c.berthAssignment,
})));

seedFile('station-os-api', 'Certification', station.certifications.map((c) => ({
  CertificationId: c.id,
  CrewId: c.crew,
  CertificationCode: c.code,
  ExpiresOnUtc: c.expiresUtc,
  Status: c.status,
})));

seedFile('station-os-api', 'Passenger', station.passengers.map((p) => ({
  PassengerId: p.id,
  PassengerName: p.name,
  DockingNo: p.docking,
  CabinClass: p.cabin,
  ClearanceStatus: p.clearance,
})));

seedFile('station-os-api', 'Vendor', station.vendors.map((v) => ({
  VendorId: v.id,
  VendorName: v.name,
  ConcourseZone: v.zone,
  CuisineOrCategory: v.category,
  LicenseStatus: v.license,
})));

seedFile('station-os-api', 'Stall', station.stalls.map((s) => ({
  StallId: s.id,
  VendorId: s.vendor,
  ConcourseZone: s.zone,
  StallNo: s.stallNo,
  LeaseCredits: s.leaseCredits,
})));

console.log('\nAll seeds derived from seed/station.json.');
