// Generated by seans-mfe-tool. Do not edit — regenerated on every `remote:generate`.
//
// Declares the developer-owned capability modules beside this file.
//
// Generator-owned so a capability added to the manifest is declared the moment
// regeneration seeds its file. The files themselves are yours.
//
// Each `<capability>_query` module holds the GraphQL document the generated
// `platform::bff_data_provider` sends for that capability (ADR-096 §7).

pub mod crew_roster_query;
pub mod pay_status_query;
