/**
 * BFF Server - GraphQL Mesh + Static Assets
 * Generated by seans-mfe-tool
 * Following ADR-046: GraphQL Mesh with DSL-embedded configuration
 */
import express, { Request, Response, NextFunction } from 'express';
import path from 'path';
import cors from 'cors';
import helmet from 'helmet';
import { createMeshHTTPHandler } from '@graphql-mesh/http';
import { getMesh } from '@graphql-mesh/runtime';
import { findAndParseConfig } from '@graphql-mesh/cli';

const app = express();

// Security middleware
app.use(helmet({
  contentSecurityPolicy: {
    directives: {
      defaultSrc: ["'self'"],
      scriptSrc: ["'self'", "'unsafe-inline'", "'unsafe-eval'", "https://unpkg.com"],
      scriptSrcElem: ["'self'", "'unsafe-inline'", "https://unpkg.com"],
      styleSrc: ["'self'", "'unsafe-inline'", "https://unpkg.com"],
      styleSrcElem: ["'self'", "'unsafe-inline'", "https://unpkg.com"],
      imgSrc: ["'self'", 'data:', 'https:'],
      connectSrc: ["'self'", "https://unpkg.com"],
      workerSrc: ["'self'", 'blob:', "https://unpkg.com"],
      childSrc: ["'self'", 'blob:'],
      fontSrc: ["'self'", 'data:', "https://unpkg.com"],
    },
  },
}));

// CORS configuration
app.use(cors({
  origin: process.env.CORS_ORIGIN || '*',
  credentials: true,
}));

// Health check endpoint
app.get('/health', (req: Request, res: Response) => {
  res.json({
    status: 'healthy',
    name: 'csv-analyzer',
    version: '1.0.0',
    timestamp: new Date().toISOString()
  });
});

// Initialize mesh at startup
let meshHandler: ReturnType<typeof createMeshHTTPHandler> | null = null;

(async () => {
  try {
    const meshConfig = await findAndParseConfig({
      dir: __dirname,
    });
    const mesh = await getMesh(meshConfig);
    meshHandler = createMeshHTTPHandler({
      baseDir: __dirname,
      getBuiltMesh: async () => mesh,
    });
  } catch (error) {
    console.error('Failed to initialize GraphQL Mesh:', error);
  }
})();

// GraphQL BFF endpoint (from Mesh)
// Following REQ-BFF-003: JWT Authentication Forwarding
app.use('/graphql', async (req: Request, res: Response, next: NextFunction) => {
  if (!meshHandler) {
    return res.status(503).json({ error: 'Mesh not ready' });
  }
  return meshHandler(req, res, next);
});

// Static MFE assets
// Following REQ-BFF-004: BFF + Static Assets Same Deployable
app.use(express.static(path.join(__dirname, 'dist')));

// SPA fallback - serve index.html for client-side routing
app.get('*', (req: express.Request, res: express.Response) => {
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

// Error handling
app.use((err: Error, req: express.Request, res: express.Response, next: express.NextFunction) => {
  console.error('Server error:', err);
  res.status(500).json({ 
    error: 'Internal Server Error',
    message: process.env.NODE_ENV === 'development' ? err.message : undefined
  });
});

// Extract user ID from JWT token
function extractUserIdFromToken(authHeader?: string): string | undefined {
  if (!authHeader) return undefined;
  try {
    const token = authHeader.replace('Bearer ', '');
    const payload = JSON.parse(Buffer.from(token.split('.')[1], 'base64').toString());
    return payload.sub || payload.userId;
  } catch {
    return undefined;
  }
}

const port = process.env.PORT || 3002;

app.listen(port, () => {
  console.log(`🚀 csv-analyzer BFF server running on port ${port}`);
  console.log(`   GraphQL endpoint: http://localhost:${port}/graphql`);
  console.log(`   Static assets: http://localhost:${port}/`);
  console.log(`   Health check: http://localhost:${port}/health`);
});

export default app;