// Generated by seans-mfe-tool. Do not edit — regenerated on every `remote:generate`.
//
// One error type for the crate (ADR-099).
//
// The Swift lane declares a struct per failure; Rust's idiom is one enum a
// caller can `match` on. Each variant corresponds to one of those structs, or
// to one of the typed errors in `@seans-mfe/contracts`.

use std::fmt;

use super::mfe_lifecycle::{MfeCapability, MfeLifecycleState};

#[derive(Debug, Clone, PartialEq)]
pub enum MfeError {
    /// A capability was invoked from a state the contract forbids, or a
    /// transition the table does not list was attempted (ADR-042).
    InvalidState {
        from: MfeLifecycleState,
        attempted: MfeCapability,
        allowed: Vec<MfeLifecycleState>,
    },
    /// A capability id this target does not implement. Not a state
    /// violation — the state may be fine; the id is not in the manifest.
    UnknownCapability {
        capability_id: String,
        declared: Vec<String>,
    },
    /// A capability the native lane does not implement. Answering success
    /// instead would claim work that never happened (ADR-096 §Boundaries).
    NotImplemented {
        capability: MfeCapability,
        detail: String,
    },
    /// A handler the manifest names that nothing supplied (ADR-098 §3).
    HandlerNotFound { handler: String, hint: String },
    /// A handler ran and failed. What a host's own handler returns.
    Handler { message: String },
    /// Transport or non-2xx failure. Carries the status when there was one.
    Transport { message: String, status: Option<u16> },
    /// The BFF answered with GraphQL errors, or with no data.
    GraphQl { messages: Vec<String> },
    /// A response that is not the JSON it should be.
    Decode { message: String },
}

impl MfeError {
    /// A handler failure with a message — the common case for host code.
    pub fn handler(message: impl Into<String>) -> Self {
        MfeError::Handler { message: message.into() }
    }
}

impl fmt::Display for MfeError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            MfeError::InvalidState { from, attempted, allowed } => {
                let states: Vec<&str> = allowed.iter().map(|s| s.as_str()).collect();
                write!(
                    f,
                    "Invalid state for {}: in {}, requires one of [{}]",
                    attempted.as_str(),
                    from.as_str(),
                    states.join(", ")
                )
            }
            MfeError::UnknownCapability { capability_id, declared } => write!(
                f,
                "Unknown capability \"{}\": this target declares [{}]",
                capability_id,
                declared.join(", ")
            ),
            MfeError::NotImplemented { capability, detail } => write!(
                f,
                "{} is not implemented in the native lane: {}",
                capability.as_str(),
                detail
            ),
            MfeError::HandlerNotFound { handler, hint } => {
                write!(f, "Handler not found: {}. {}", handler, hint)
            }
            MfeError::Handler { message } => write!(f, "{}", message),
            MfeError::Transport { message, status: Some(status) } => {
                write!(f, "BFF request failed ({}): {}", status, message)
            }
            MfeError::Transport { message, status: None } => {
                write!(f, "BFF request failed: {}", message)
            }
            MfeError::GraphQl { messages } => write!(f, "GraphQL errors: {}", messages.join("; ")),
            MfeError::Decode { message } => write!(f, "Could not decode BFF response: {}", message),
        }
    }
}

impl std::error::Error for MfeError {}
