// Generated by seans-mfe-tool. Do not edit — regenerated on every `remote:generate`.
//
// A minimal executor, for hosts and tests with no async runtime (ADR-099).
//
// The crate's futures are runtime-agnostic — they run on tokio, async-std,
// smol or anything else. `block_on` is here so a synchronous host, and the
// generated tests, can drive them without adding a runtime dependency.

use std::future::Future;
use std::pin::pin;
use std::sync::Arc;
use std::task::{Context, Poll, Wake, Waker};
use std::thread::{self, Thread};

struct ThreadWaker(Thread);

impl Wake for ThreadWaker {
    fn wake(self: Arc<Self>) {
        self.0.unpark();
    }
}

/// Run a future to completion on the current thread.
pub fn block_on<F: Future>(future: F) -> F::Output {
    let mut future = pin!(future);
    let waker = Waker::from(Arc::new(ThreadWaker(thread::current())));
    let mut context = Context::from_waker(&waker);
    loop {
        match future.as_mut().poll(&mut context) {
            Poll::Ready(output) => return output,
            Poll::Pending => thread::park(),
        }
    }
}
