# BFF Layer - Acceptance Criteria (GWT)
# Generated by Implementation Developer Agent
# Reference: docs/graphql-bff-requirements.md, ADR-046

## REQ-BFF-001: DSL Data Section as Mesh Configuration

### Scenario: Extract Mesh config from DSL
```gherkin
Given a valid mfe-manifest.yaml with a data.sources section
  And the data.sources contains at least one OpenAPI handler
When the user runs `mfe bff:build`
Then a .meshrc.yaml file is generated in the current directory
  And it contains all sources from data.sources
  And the sources array matches the DSL structure
```

### Scenario: Missing data section in DSL
```gherkin
Given a mfe-manifest.yaml without a data: section
When the user runs `mfe bff:build`
Then an error message states "No data: section found in manifest"
  And the build process exits with error code 1
```

### Scenario: Empty sources array
```gherkin
Given a mfe-manifest.yaml with data: section but empty sources: []
When the user runs `mfe bff:build`
Then an error message states "At least one OpenAPI source is required"
  And the build process exits with error code 1
```

---

## REQ-BFF-002: Multi-Source Support

### Scenario: Multiple OpenAPI specs merged
```gherkin
Given a mfe-manifest.yaml with three sources in data.sources
  And each source references a different OpenAPI spec
When the user runs `mfe bff:build`
Then .meshrc.yaml contains all three sources
  And mesh build generates a unified GraphQL schema
```

### Scenario: Source with transforms
```gherkin
Given a source with prefix transform configured
When the user runs `mfe bff:build`
Then the generated .meshrc.yaml includes the transform
  And the GraphQL types are prefixed accordingly
```

---

## REQ-BFF-003: JWT Authentication Forwarding

### Scenario: Standard JWT forwarding via operationHeaders
```gherkin
Given a source with operationHeaders configured
  And Authorization header uses {context.jwt} placeholder
When a GraphQL request is made with Authorization header
Then the REST API call includes the forwarded JWT token
```

### Scenario: Request ID forwarding
```gherkin
Given a source with X-Request-ID in operationHeaders
When a GraphQL request includes X-Request-ID header
Then the REST API call includes the same request ID
```

---

## REQ-BFF-004: BFF + Static Assets Same Deployable

### Scenario: Generate combined server
```gherkin
Given a remote MFE project with data: section
When the user runs `mfe bff:init`
Then server.ts serves both /graphql and static assets
  And Dockerfile builds both Mesh artifacts and MFE bundle
```

### Scenario: Standalone BFF (no static)
```gherkin
Given the user runs `mfe bff:init my-bff --no-static`
Then server.ts serves only /graphql endpoint
  And no static asset serving code is included
```

---

## REQ-BFF-005: CLI Command Integration

### Scenario: bff:init creates new project
```gherkin
Given the user runs `mfe bff:init my-bff --specs ./api.yaml`
Then a new directory my-bff is created
  And package.json includes Mesh dependencies
  And server.ts template is generated
  And Dockerfile template is generated
```

### Scenario: bff:init adds to existing project
```gherkin
Given an existing MFE project directory
  And the directory contains mfe-manifest.yaml
When the user runs `mfe bff:init` (no name argument)
Then Mesh dependencies are added to package.json
  And server.ts is created in the project
  And existing files are not overwritten
```

### Scenario: bff:validate checks configuration
```gherkin
Given a mfe-manifest.yaml with valid data: section
When the user runs `mfe bff:validate`
Then each source is validated
  And local OpenAPI spec paths are checked for existence
  And a success message is displayed
```

### Scenario: bff:validate catches invalid transform
```gherkin
Given a mfe-manifest.yaml with unknown transform type
When the user runs `mfe bff:validate`
Then a warning is displayed for the unknown transform
```

### Scenario: bff:dev starts development server
```gherkin
Given a project with valid BFF configuration
When the user runs `mfe bff:dev`
Then .meshrc.yaml is extracted from DSL
  And mesh dev process is started
  And GraphQL playground is available
```

---

## REQ-BFF-006: Production Plugins

### Scenario: Response cache plugin configured
```gherkin
Given a data.plugins section with responseCache
When the user runs `mfe bff:build`
Then .meshrc.yaml includes the responseCache plugin
  And the ttl value is preserved
```

### Scenario: Rate limit plugin configured
```gherkin
Given a data.plugins section with rateLimit
When the user runs `mfe bff:build`
Then .meshrc.yaml includes the rateLimit plugin
  And the configuration is preserved
```

---

## REQ-BFF-007: Transforms for Schema Shaping

### Scenario: Prefix transform applied
```gherkin
Given a source with prefix transform value "User_"
When mesh build completes
Then GraphQL types are prefixed with "User_"
  And Query fields are prefixed with "User_"
```

### Scenario: FilterSchema removes fields
```gherkin
Given a source with filterSchema excluding "Query.!internal*"
When mesh build completes
Then internal queries are not exposed in GraphQL schema
```

---

## REQ-BFF-008: Discovery and Introspection

### Scenario: Introspection enabled by default
```gherkin
Given a running BFF server
When a client sends GraphQL introspection query
Then the full schema is returned
```

### Scenario: Playground available in development
```gherkin
Given serve.playground is true in configuration
When the user navigates to /graphql in browser
Then GraphiQL or Mesh playground is displayed
```

---

## Cross-Cutting Scenarios

### Scenario: Health check endpoint available
```gherkin
Given a running BFF server
When a client requests GET /health
Then a JSON response with status "healthy" is returned
  And the response includes name and version
```

### Scenario: Docker build succeeds
```gherkin
Given a BFF project with valid configuration
When `docker build -t my-bff .` is executed
Then the Docker image builds successfully
  And the image runs and responds on configured port
```
