"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * BFF Server - GraphQL Mesh + Static Assets
 * Generated by seans-mfe-tool
 * Following ADR-046: GraphQL Mesh with DSL-embedded configuration
 * Following ADR-062: Mesh v0.100.x with createBuiltMeshHTTPHandler
 */
const express_1 = __importDefault(require("express"));
const path_1 = __importDefault(require("path"));
const cors_1 = __importDefault(require("cors"));
const helmet_1 = __importDefault(require("helmet"));
const _mesh_1 = require("./.mesh");
const crypto_1 = __importDefault(require("crypto"));
const app = (0, express_1.default)();
// Security middleware
app.use((0, helmet_1.default)({
    contentSecurityPolicy: {
        directives: {
            defaultSrc: ["'self'"],
            scriptSrc: ["'self'", "'unsafe-inline'", "'unsafe-eval'", "https://unpkg.com"],
            scriptSrcElem: ["'self'", "'unsafe-inline'", "https://unpkg.com"],
            styleSrc: ["'self'", "'unsafe-inline'", "https://unpkg.com"],
            styleSrcElem: ["'self'", "'unsafe-inline'", "https://unpkg.com"],
            imgSrc: ["'self'", 'data:', 'https:'],
            connectSrc: ["'self'", "https://unpkg.com"],
            workerSrc: ["'self'", 'blob:', "https://unpkg.com"],
            childSrc: ["'self'", 'blob:'],
            fontSrc: ["'self'", 'data:', "https://unpkg.com"],
        },
    },
}));
// CORS configuration
app.use((0, cors_1.default)({
    origin: process.env.CORS_ORIGIN || '*',
    credentials: true,
}));
// Health check endpoint
app.get('/health', (req, res) => {
    res.json({
        status: 'healthy',
        name: 'csv-analyzer',
        version: '1.0.0',
        timestamp: new Date().toISOString()
    });
});
const meshHandler = (0, _mesh_1.createBuiltMeshHTTPHandler)();
// Add context middleware before GraphQL handler
app.use('/graphql', (req, res, next) => {
    // Attach context to request for Mesh
    req.meshContext = {
        jwt: req.headers.authorization?.replace('Bearer ', ''),
        requestId: req.headers['x-request-id'] || crypto_1.default.randomUUID(),
        userId: extractUserIdFromToken(req.headers.authorization),
    };
    next();
}, meshHandler);
// Static MFE assets
// Following REQ-BFF-004: BFF + Static Assets Same Deployable
app.use(express_1.default.static(path_1.default.join(__dirname, 'dist')));
// SPA fallback - serve index.html for client-side routing
app.get('*', (req, res) => {
    res.sendFile(path_1.default.join(__dirname, 'dist', 'index.html'));
});
// Error handling
app.use((err, req, res, next) => {
    console.error('Server error:', err);
    res.status(500).json({
        error: 'Internal Server Error',
        message: process.env.NODE_ENV === 'development' ? err.message : undefined
    });
});
// Extract user ID from JWT token
function extractUserIdFromToken(authHeader) {
    if (!authHeader)
        return undefined;
    try {
        const token = authHeader.replace('Bearer ', '');
        const payload = JSON.parse(Buffer.from(token.split('.')[1], 'base64').toString());
        return payload.sub || payload.userId;
    }
    catch {
        return undefined;
    }
}
const port = process.env.PORT || 3002;
app.listen(port, () => {
    console.log(`🚀 csv-analyzer BFF server running on port ${port}`);
    console.log(`   GraphQL endpoint: http://localhost:${port}/graphql`);
    console.log(`   Static assets: http://localhost:${port}/`);
    console.log(`   Health check: http://localhost:${port}/health`);
});
exports.default = app;
exports.default = app;
