"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * BFF Server - GraphQL Mesh + Static Assets
 * Generated by seans-mfe-tool
 * Following ADR-046: GraphQL Mesh with DSL-embedded configuration
 */
const express_1 = __importDefault(require("express"));
const path_1 = __importDefault(require("path"));
const helmet_1 = __importDefault(require("helmet"));
const cors_1 = __importDefault(require("cors"));
const runtime_1 = require("@graphql-mesh/runtime");
const cli_1 = require("@graphql-mesh/cli");
const node_1 = require("@graphql-yoga/node");
const app = (0, express_1.default)();
// Security middleware
app.use((0, helmet_1.default)({
    contentSecurityPolicy: {
        directives: {
            defaultSrc: ["'self'"],
            scriptSrc: ["'self'", "'unsafe-inline'", "'unsafe-eval'", "https://unpkg.com"],
            scriptSrcElem: ["'self'", "'unsafe-inline'", "https://unpkg.com"],
            styleSrc: ["'self'", "'unsafe-inline'", "https://unpkg.com"],
            styleSrcElem: ["'self'", "'unsafe-inline'", "https://unpkg.com"],
            imgSrc: ["'self'", 'data:', 'https:'],
            connectSrc: ["'self'", "https://unpkg.com"],
            workerSrc: ["'self'", 'blob:', "https://unpkg.com"],
            childSrc: ["'self'", 'blob:'],
            fontSrc: ["'self'", 'data:', "https://unpkg.com"],
        },
    },
}));
// CORS configuration
app.use((0, cors_1.default)({
    origin: process.env.CORS_ORIGIN || '*',
    credentials: true,
}));
// Health check endpoint
app.get('/health', (req, res) => {
    res.json({
        status: 'healthy',
        name: 'csv-analyzer',
        version: '1.0.0',
        timestamp: new Date().toISOString()
    });
});
// Programmatic Mesh integration: serve GraphQL endpoint from same Express server
let meshSchema;
(async () => {
    const meshConfig = await (0, cli_1.findAndParseConfig)({ dir: __dirname });
    const mesh = await (0, runtime_1.getMesh)(meshConfig);
    meshSchema = mesh.schema;
    console.log('✅ GraphQL Mesh schema loaded successfully');
    // GraphQL endpoint with Yoga
    const yoga = (0, node_1.createYoga)({
        schema: meshSchema,
        graphqlEndpoint: '/graphql',
        graphiql: true,
    });
    app.use('/graphql', yoga);
    const port = process.env.PORT || 3002;
    app.listen(port, () => {
        console.log(`🚀 csv-analyzer BFF server running on port ${port}`);
        console.log(`   GraphQL endpoint: http://localhost:${port}/graphql`);
        console.log(`   Static assets: http://localhost:${port}/`);
        console.log(`   Health check: http://localhost:${port}/health`);
    });
})();
// Static MFE assets
// Following REQ-BFF-004: BFF + Static Assets Same Deployable
app.use(express_1.default.static(path_1.default.join(__dirname, 'dist')));
// SPA fallback - serve index.html for client-side routing
app.get('*', (req, res) => {
    res.sendFile(path_1.default.join(__dirname, 'dist', 'index.html'));
});
// Error handling
app.use((err, req, res, next) => {
    console.error('Server error:', err);
    res.status(500).json({
        error: 'Internal Server Error',
        message: process.env.NODE_ENV === 'development' ? err.message : undefined
    });
});
// Extract user ID from JWT token
// Mesh Compose CLI migration: JWT extraction now handled by mesh serve CLI plugins if needed
// ...existing code...
exports.default = app;
