// Generated by seans-mfe-tool. Do not edit — regenerated on every `remote:generate`.
//
// Contract smoke test (ADR-099). Mirrors the Swift lane's `LifecycleTests`:
// it RUNS the lifecycle machine, the hook engine and both query error
// policies, rather than reading the generated source for them. A text
// assertion can see that the engine was rendered; only running it can see
// that it runs (ADR-098 §Boundaries).
//
// Wrapped in a `#[rustfmt::skip]` module so `cargo fmt` leaves this
// generator-owned file byte-identical to what regeneration writes.

#[rustfmt::skip]
mod contract {

use std::sync::{Arc, Mutex};

use meridian_crew_services::*;

struct StubProvider;

impl MeridianCrewServicesDataProvider for StubProvider {
    fn crew_roster(&self) -> BoxFuture<'_, Result<CrewRosterOutputs, MfeError>> {
        Box::pin(async { Ok(CrewRosterOutputs::default()) })
    }
    fn pay_status(&self) -> BoxFuture<'_, Result<PayStatusOutputs, MfeError>> {
        Box::pin(async { Ok(PayStatusOutputs::default()) })
    }
}

/// A transport that answers with fixed bytes and records what it was sent.
struct StubTransport {
    status: u16,
    body: Vec<u8>,
    seen: Mutex<Option<HttpRequest>>,
}

impl StubTransport {
    fn new(status: u16, body: &str) -> Arc<Self> {
        Arc::new(StubTransport { status, body: body.as_bytes().to_vec(), seen: Mutex::new(None) })
    }
}

impl MfeTransport for StubTransport {
    fn post(&self, request: HttpRequest) -> BoxFuture<'_, Result<HttpResponse, MfeError>> {
        *self.seen.lock().unwrap() = Some(request);
        let response = HttpResponse { status: self.status, body: self.body.clone() };
        Box::pin(async move { Ok(response) })
    }
}

/// A partial GraphQL response — `data` AND `errors`, a normal outcome.
const PARTIAL: &str = r#"{"data":{"x":1},"errors":[{"message":"boom"}]}"#;

fn mfe() -> MeridianCrewServicesMfe {
    MeridianCrewServicesMfe::new(Arc::new(StubProvider), MfeDependencies::default())
}

fn mfe_with(deps: MfeDependencies) -> MeridianCrewServicesMfe {
    MeridianCrewServicesMfe::new(Arc::new(StubProvider), deps)
}

fn query_context() -> MfeContext {
    MfeContext::new()
        .with_input("document", "query { x }")
        .with_input("bffUrl", "http://stub.invalid/graphql")
}

#[test]
fn starts_uninitialized() {
    assert_eq!(mfe().state(), MfeLifecycleState::Uninitialized);
}

#[test]
fn load_moves_to_ready() {
    let mfe = mfe();
    let loaded = block_on(mfe.load(MfeContext::new())).expect("load");
    assert!(loaded.success);
    assert_eq!(mfe.state(), MfeLifecycleState::Ready);
}

#[test]
fn render_requires_ready() {
    let mfe = mfe();
    // render's pre-states are [ready]; from uninitialized this must fail
    // rather than transition.
    let result = block_on(mfe.render(MfeContext::new().with_capability_id("CrewRoster")));
    assert!(matches!(result, Err(MfeError::InvalidState { .. })));
    assert_eq!(mfe.state(), MfeLifecycleState::Uninitialized);
}

#[test]
fn render_after_load_mounts_the_capability() {
    let mfe = mfe();
    block_on(mfe.load(MfeContext::new())).expect("load");
    let rendered = block_on(mfe.render(MfeContext::new().with_capability_id("CrewRoster"))).expect("render");
    assert_eq!(rendered.capability_id, "CrewRoster");
    assert_eq!(mfe.state(), MfeLifecycleState::Ready);
    assert!(mfe.hooks().mounted().lock().unwrap().contains("CrewRoster"));
}

#[test]
fn a_failed_render_enters_the_error_state() {
    let mfe = mfe();
    block_on(mfe.load(MfeContext::new())).expect("load");
    // Not a state violation — the id is unknown — so the error boundary runs
    // and the machine lands in render's error state.
    let result = block_on(mfe.render(MfeContext::new().with_capability_id("NotACapability")));
    assert!(matches!(result, Err(MfeError::UnknownCapability { .. })));
    assert_eq!(mfe.state(), MfeLifecycleState::Error);
}

#[test]
fn mount_rejects_unknown_capability() {
    assert!(matches!(mfe().mount("NotACapability"), Err(MfeError::UnknownCapability { .. })));
}

#[test]
fn describe_reports_manifest_capabilities() {
    let mfe = mfe();
    let described = block_on(mfe.describe(MfeContext::new())).expect("describe");
    assert_eq!(described.name, platform::manifest_metadata::NAME);
    assert_eq!(described.capabilities.len(), platform::manifest_metadata::CAPABILITIES.len());
}

#[test]
fn emit_fails_honestly_rather_than_claiming_delivery() {
    let result = block_on(mfe().emit(MfeContext::new()));
    assert!(matches!(result, Err(MfeError::NotImplemented { capability: MfeCapability::Emit, .. })));
}

fn recorder(fired: &Arc<Mutex<Vec<String>>>, name: &'static str) -> MfeHandler {
    let fired = fired.clone();
    handler(move |_context| {
        let fired = fired.clone();
        async move {
            fired.lock().unwrap().push(name.to_string());
            Ok(())
        }
    })
}

/// The manifest's hooks actually FIRE — the Swift lane shipped a hook engine
/// wired to nothing once, green under every text assertion (ADR-098).
#[test]
fn manifest_hooks_fire() {
    let fired = Arc::new(Mutex::new(Vec::new()));
    let mut deps = MfeDependencies::default();
    deps.custom_handlers.insert("onLoadBegin".to_string(), recorder(&fired, "onLoadBegin"));
    deps.custom_handlers.insert("onLoadComplete".to_string(), recorder(&fired, "onLoadComplete"));
    deps.custom_handlers.insert("onLoadError".to_string(), recorder(&fired, "onLoadError"));
    deps.custom_handlers.insert("onRenderBegin".to_string(), recorder(&fired, "onRenderBegin"));
    deps.custom_handlers.insert("onRenderComplete".to_string(), recorder(&fired, "onRenderComplete"));
    deps.custom_handlers.insert("onRenderError".to_string(), recorder(&fired, "onRenderError"));
    let mfe = mfe_with(deps);
    block_on(mfe.load(MfeContext::new())).expect("load");

    let ran = fired.lock().unwrap().clone();
    assert!(!ran.is_empty(), "no manifest hook fired during load()");
    assert!(ran.contains(&"onLoadBegin".to_string()), "before hook onLoadBegin did not fire");
    assert!(ran.contains(&"onLoadComplete".to_string()), "after hook onLoadComplete did not fire");
}

/// A host's handler wins over the generated stub for the same name.
#[test]
fn host_handler_overrides_generated_stub() {
    let fired = Arc::new(Mutex::new(Vec::new()));
    let mut deps = MfeDependencies::default();
    deps.custom_handlers.insert("onLoadBegin".to_string(), recorder(&fired, "host"));
    let mfe = mfe_with(deps);
    block_on(mfe.load(MfeContext::new())).expect("load");
    assert!(fired.lock().unwrap().contains(&"host".to_string()), "host handler was shadowed by the generated stub");
}

// ---- query transport
//
// `do_query` and `BffClient` share one HTTP path (`GraphQlPost::send`) and
// keep DIFFERENT error policies on purpose. These run the real code over a
// stub transport, so the split is asserted rather than incidental.

#[test]
fn query_returns_partial_data_and_errors_together() {
    let transport = StubTransport::new(200, PARTIAL);
    let mfe = mfe_with(MfeDependencies { transport: Some(transport), ..MfeDependencies::default() });
    block_on(mfe.load(MfeContext::new())).expect("load");
    let result = block_on(mfe.query(query_context())).expect("query");
    // The envelope policy: the capability answers with both halves.
    assert_eq!(result.data, Some(serde_json::json!({ "x": 1 })));
    assert_eq!(result.errors, vec!["boom".to_string()]);
}

#[test]
fn query_returns_errors_rather_than_failing_on_http_failure() {
    let transport = StubTransport::new(503, "nope");
    let mfe = mfe_with(MfeDependencies { transport: Some(transport), ..MfeDependencies::default() });
    block_on(mfe.load(MfeContext::new())).expect("load");
    let result = block_on(mfe.query(query_context())).expect("query");
    assert_eq!(result.data, None);
    assert_eq!(result.errors.len(), 1);
}

#[test]
fn query_without_a_transport_names_the_missing_dependency() {
    let mfe = mfe();
    block_on(mfe.load(MfeContext::new())).expect("load");
    let result = block_on(mfe.query(query_context())).expect("query");
    assert_eq!(result.data, None);
    assert!(result.errors[0].contains("MfeDependencies.transport"), "{:?}", result.errors);
}

#[test]
fn query_forwards_the_bearer_token_and_headers() {
    let transport = StubTransport::new(200, r#"{"data":{}}"#);
    let mfe = mfe_with(MfeDependencies { transport: Some(transport.clone()), ..MfeDependencies::default() });
    block_on(mfe.load(MfeContext::new())).expect("load");
    block_on(mfe.query(query_context().with_jwt("tok").with_header("X-Request-Id", "abc"))).expect("query");

    let seen = transport.seen.lock().unwrap().clone().expect("transport was not called");
    assert_eq!(seen.url, "http://stub.invalid/graphql");
    assert_eq!(seen.headers.get("Authorization").map(String::as_str), Some("Bearer tok"));
    assert_eq!(seen.headers.get("X-Request-Id").map(String::as_str), Some("abc"));
    assert_eq!(seen.headers.get("Content-Type").map(String::as_str), Some("application/json"));
}

#[test]
fn bff_client_fails_on_the_same_partial_response() {
    // Same bytes, opposite policy: a caller decoding into a type must not
    // silently receive half a response.
    let client = BffClient::new("http://stub.invalid/graphql", StubTransport::new(200, PARTIAL));
    let result: Result<serde_json::Value, MfeError> = block_on(client.query("query { x }", None));
    assert!(matches!(result, Err(MfeError::GraphQl { .. })));
}

#[test]
fn the_generated_provider_sends_the_capability_document() {
    let transport = StubTransport::new(200, r#"{"data":{}}"#);
    let mfe = MeridianCrewServicesMfe::with_transport(transport.clone(), MfeDependencies::default());
    block_on(mfe.provider().crew_roster()).expect("provider");
    let seen = transport.seen.lock().unwrap().clone().expect("transport was not called");
    let body: serde_json::Value = serde_json::from_slice(&seen.body).unwrap();
    assert_eq!(body["query"], meridian_crew_services::features::crew_roster_query::DOCUMENT);
}

#[test]
fn transition_table_matches_contract() {
    // The six states and their edges come from the platform contract.
    assert_eq!(MfeLifecycleState::ALL.len(), 6);
    assert!(MfeLifecycleState::Uninitialized.can_transition_to(MfeLifecycleState::Loading));
    assert!(!MfeLifecycleState::Destroyed.can_transition_to(MfeLifecycleState::Loading));
}

} // mod contract
