
/**
 * abckidsmultiplicationquizMFE bootstrap
 *
 * Instantiates abckidsmultiplicationquizMFE and calls load() so the full doLoad lifecycle
 * runs and its console logs are visible in the browser DevTools.
 *
 * This fires once when the Module Federation remote bundle is first imported
 * by the shell (i.e. when remote.tsx is evaluated).
 *
 * @generated By seans-mfe-tool CLI — regenerated on every codegen run.
 *            Do not edit by hand; changes will be overwritten.
 */
import { abckidsmultiplicationquizMFE } from './mfe';

const manifest = {
  "name": "abc-kids-multiplication-quiz",
  "version": "1.0.0",
  "type": "remote",
  "language": "typescript",
  "framework": "angular",
  "bundler": "webpack",
  "description": "Multiplication Quiz — a cat and a dog take turns asking multiplication questions!",
  "owner": "abc-kids-team",
  "tags": [
    "kids",
    "game",
    "math",
    "multiplication",
    "quiz"
  ],
  "category": "games",
  "endpoint": "http://localhost:3003",
  "remoteEntry": "http://localhost:3003/remoteEntry.js",
  "discovery": "http://localhost:3003/.well-known/mfe-manifest.yaml",
  "capabilities": [
    {
      "PlayGame": {
        "type": "domain",
        "description": "Play the multiplication quiz game with cat and dog characters"
      }
    },
    {
      "ShowCover": {
        "type": "domain",
        "description": "Show the multiplication quiz cover card with cat and dog art"
      }
    },
    {
      "GetGameInfo": {
        "type": "domain",
        "description": "Return game metadata including title, age range, and description"
      }
    },
    {
      "Load": {
        "type": "platform",
        "lifecycle": {
          "before": [
            {
              "onLoadBegin": {
                "handler": "onLoadBegin",
                "description": "Log load lifecycle entry"
              }
            }
          ],
          "after": [
            {
              "onLoadComplete": {
                "handler": "onLoadComplete",
                "description": "Log load success and available components"
              }
            }
          ],
          "error": [
            {
              "onLoadError": {
                "handler": "onLoadError",
                "description": "Log load failure",
                "contained": true
              }
            }
          ]
        }
      }
    },
    {
      "Render": {
        "type": "platform",
        "lifecycle": {
          "before": [
            {
              "onRenderBegin": {
                "handler": "onRenderBegin",
                "description": "Log render lifecycle entry"
              }
            }
          ],
          "after": [
            {
              "onRenderComplete": {
                "handler": "onRenderComplete",
                "description": "Log render success"
              }
            }
          ],
          "error": [
            {
              "onRenderError": {
                "handler": "onRenderError",
                "description": "Log render failure",
                "contained": true
              }
            }
          ]
        }
      }
    }
  ],
  "dependencies": {
    "runtime": {
      "@angular/core": "^17.0.0",
      "@angular/common": "^17.0.0",
      "@angular/platform-browser": "^17.0.0",
      "rxjs": "^7.8.0",
      "zone.js": "~0.14.0"
    }
  }
};

export const mfe = new abckidsmultiplicationquizMFE(manifest);

export const mfeReady: Promise<void> = mfe
  .load({
    requestId: `bootstrap-${Date.now()}`,
    timestamp: new Date(),
    inputs: {
      remoteEntry: manifest.remoteEntry,
    },
  })
  .then((result) => {
    console.log(
      '[abckidsmultiplicationquizMFE] bootstrap load() complete \u2014 status:',
      result.status,
      '\u2014 components:',
      result.availableComponents
    );
  })
  .catch((err) => {
    console.error('[abckidsmultiplicationquizMFE] bootstrap load() failed:', err);
  });
