#!/usr/bin/env bash
# Generated by scripts/generate-games.mjs — builds the whole ABC Kids fleet
# with bounded peak disk usage:
#   1. seans-mfe-tool-cli:latest   (pre-compiled runtime; SKIP_CLI=1 to skip)
#   2. abc-kids-game-base:latest   (shared dependency pack — ONE npm install)
#   3. every service, sequentially (COMPOSE_BAKE=false avoids 13 parallel
#      installs exhausting the Docker VM disk)
set -euo pipefail
cd "$(dirname "$0")/.."

if [[ "${SKIP_CLI:-0}" != "1" ]]; then
  echo "==> 1/3 seans-mfe-tool-cli:latest (set SKIP_CLI=1 if already fresh)"
  (cd ../.. && npm run build && npm run docker:build:cli)
fi

echo "==> 2/3 abc-kids-game-base:latest (shared dependency pack)"
docker build -t abc-kids-game-base:latest ./game-base

echo "==> 3/3 service images (sequential; one failure does not block the fleet)"
SERVICES=(
  abc-kids-shell
  abc-kids-flappy
  abc-kids-hockey
  abc-kids-multiplication-quiz
  abc-kids-home
  abc-kids-counting-stars
  abc-kids-letter-pop
  abc-kids-shape-sorter
  abc-kids-color-mixer
  abc-kids-animal-sounds
  abc-kids-memory-match
  abc-kids-rocket-math
  abc-kids-word-builder
  abc-kids-rhythm-tap
  abc-kids-maze-runner
)
FAILED=()
BUILT=()
for svc in "${SERVICES[@]}"; do
  echo "--- $svc"
  if COMPOSE_BAKE=false docker compose -f docker-compose.yaml -f docker-compose.games.yaml build "$svc"; then
    BUILT+=("$svc")
  else
    echo "!!! $svc build failed — continuing with the rest of the fleet"
    FAILED+=("$svc")
  fi
done

echo "==> starting everything that built"
if [[ ${#BUILT[@]} -gt 0 ]]; then
  docker compose -f docker-compose.yaml -f docker-compose.games.yaml up -d --no-build "${BUILT[@]}"
fi

if [[ ${#FAILED[@]} -gt 0 ]]; then
  echo ""
  echo "==> done WITH FAILURES — these services did not build/start:"
  printf '    %s\n' "${FAILED[@]}"
  exit 1
fi
echo "==> done — full fleet built and started"
