#!/usr/bin/env bash
# Generated by scripts/generate-games.mjs — registers every ABC Kids game
# with the control-plane registry (ADR-054/ADR-055) from
# control-plane/rules.json. Each game is multi-capability (ADR-056): three
# routes map state to a capability — abc.play.<game> -> PlayGame into
# abc-kids-home/main, abc.show/abc.info -> ShowCover/GetGameInfo into
# abc-kids-home/info. The registration does NOT pin
# moduleFederation.component, so the resolved capability per route drives
# which component the LayoutManager mounts.
#
# The rules are data, so CI can check them before deploy (ADR-073):
#   seans-mfe-tool slots:validate --rules control-plane/rules.json --manifests .
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(dirname "$HERE")"
RULES="${RULES:-$ROOT/control-plane/rules.json}"
REGISTRY=${REGISTRY:-http://localhost:4000}

if [ ! -f "$RULES" ]; then
  echo "rules file not found: $RULES" >&2
  exit 1
fi

count="$(jq 'length' "$RULES")"
for i in $(seq 0 $((count - 1))); do
  doc="$(jq -c ".[$i]" "$RULES")"
  name="$(printf '%s' "$doc" | jq -r '.registration.name')"
  caps="$(printf '%s' "$doc" | jq -r '[.routes[].resolve.capability] | unique | join("/")')"
  curl -fsS -X POST "$REGISTRY/mfes" -H "Content-Type: application/json" -d "$doc" > /dev/null
  echo " registered $name ($caps)"
done

echo "All 13 games + home registered. Compose the home with:"
echo "  ./scripts/home.sh"
echo "...then pick a game in the UI, or drive it directly:"
echo "  ./scripts/play.sh counting-stars"
